# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5437/servicedirectory
spring.datasource.username=testuser
spring.datasource.password=testpassword

# Liquibase

# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml
# Hibernate
spring.jpa.hibernate.ddl-auto=validate

# No auto-population for org units
eshg.population.default-number-of-entities-to-populate.org-unit=0

server.port=8083

logging.level.org.zalando.logbook=TRACE
