// Copyright 2026 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

import com.bmuschko.gradle.docker.tasks.image.DockerPushImage
import com.bmuschko.gradle.docker.tasks.image.DockerTagImage

plugins {
    id "com.bmuschko.docker-remote-api"
}

def getImageBaseName() {
    if (project.hasProperty("dockerImageBaseName")) {
        return project.property("dockerImageBaseName")
    }
    return "ga-lotse"
}

def getImageName() {
    return "${getImageBaseName()}/${project.name}"
}

static def getRepoDigest(String imageNameWithTag) {
  def commandLine = ['docker', 'inspect', '--format={{index .RepoDigests 0}}', imageNameWithTag]
  def stdout = new StringBuilder()
  def stderr = new StringBuilder()

  def process = commandLine.execute()
  process.consumeProcessOutput(stdout, stderr)
  process.waitFor()

  assert stderr.toString().isEmpty(): "Could not get repo digest! Docker returned:\n${stderr.toString()}"

  def digest = stdout.toString().trim()
  assert !digest.isEmpty(): "Unexpected empty output from command!"

  return digest
}

def assertTagNameIsGiven() {
    assert project.hasProperty("tagName"): "tagName is necessary"
}

def getTagName() {
    return project.findProperty("tagName")
}

def getImageNameWithTag() {
    return "${getImageName()}:${getTagName()}"
}

def getImageNameWithLatestTag() {
    return "${getImageName()}:latest"
}

// Export methods by turning them into closures
ext {
    getImageName = this.&getImageName
    getTagName = this.&getTagName
    getImageNameWithTag = this.&getImageNameWithTag
    getImageNameWithLatestTag = this.&getImageNameWithLatestTag
}

tasks.register('pushDockerImage', DockerPushImage) {
    dependsOn 'buildDockerImage'

    if (getTagName() != null) {
        images.add(getImageNameWithTag())
    }

    doFirst {
        assertTagNameIsGiven()
    }

    if (project.hasProperty('updateLatestTag') && project.property('updateLatestTag').toBoolean()) {
        finalizedBy 'pushDockerImageAsLatest'
    }
}

tasks.register('tagDockerImageAsLatest', DockerTagImage) {
    dependsOn 'buildDockerImage'
    imageId.set(getImageNameWithTag())
    repository.set(getImageName())
    tag.set('latest')
}

tasks.register('pushDockerImageAsLatest', DockerPushImage) {
    dependsOn 'tagDockerImageAsLatest'
    shouldRunAfter 'pushDockerImage'
    images.add(getImageNameWithLatestTag())
}

tasks.register("signDockerImage", Exec) {
  doFirst {
    assertTagNameIsGiven()
  }

  def argProv = {
    [
      'sign', getRepoDigest(getImageNameWithTag()),
      '--annotations', "com.gitlab.ci.pipeline.id=${System.getenv("CI_PIPELINE_ID")}".toString(),
      '--annotations', "com.gitlab.ci.pipeline.url=${System.getenv("CI_PIPELINE_URL")}".toString(),
      '--annotations', "com.gitlab.ci.job.id=${System.getenv("CI_JOB_ID")}".toString(),
      '--annotations', "com.gitlab.ci.job.url=${System.getenv("CI_JOB_URL")}".toString(),
      '--annotations', "com.gitlab.ci.commit.sha=${System.getenv("CI_COMMIT_SHA")}".toString(),
      '--annotations', "com.gitlab.ci.commit.ref.name=${System.getenv("CI_COMMIT_REF_NAME")}".toString(),
      '--annotations', "com.gitlab.ci.project.path=${System.getenv("CI_PROJECT_PATH")}".toString(),
      '--annotations', "org.opencontainers.image.source=${System.getenv("CI_PROJECT_URL")}".toString(),
      '--annotations', "org.opencontainers.image.revision=${System.getenv("CI_COMMIT_SHA")}".toString()
    ]
  } as CommandLineArgumentProvider
  executable 'cosign'
  argumentProviders.add(argProv)
}

tasks.register("verifyImageSignature", Exec) {
    def certificateIdentity = project.findProperty("certificateIdentity")
    def certificateOidcIssuer = project.findProperty("certificateOidcIssuer")

    commandLine 'cosign', 'verify', getImageNameWithTag(),
            '--certificate-identity', certificateIdentity ?: "",
            '--certificate-oidc-issuer', certificateOidcIssuer ?: ""

    doFirst {
        assertTagNameIsGiven()
        assert project.hasProperty("certificateIdentity"): "certificateIdentity is necessary"
        assert project.hasProperty("certificateOidcIssuer"): "certificateOidcIssuer is necessary"
    }
}
