import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

plugins {
    id "eshg.java-lib"
    id "com.bmuschko.docker-remote-api"
    id "docker-compose"
    id "eshg.image-push-sign"
}

def dockerBuildContext = file(layout.buildDirectory.dir('docker'))

tasks.register('copyResourcesToBuildContext', Copy) {
    from layout.projectDirectory
    include('Dockerfile')
    into dockerBuildContext
}

tasks.register('buildDockerImage', DockerBuildImage) {
    dependsOn 'copyResourcesToBuildContext'
    inputDir.set(dockerBuildContext)
    dockerFile.set(inputDir.file("Dockerfile"))

    if (project.hasProperty("tagName")) {
        images.add(getImageNameWithTag())
    } else {
        images.add(getImageNameWithLatestTag())
    }
}

tasks.named("composeUp").configure {
    // change default behavior of dockerCompose plugin:
    // instead of starting ALL compose services
    // starte NONE, when startedServices list is empty
    it.enabled = dockerCompose.startedServices.get().size() > 0
}

tasks.named("composeBuild").configure {
    // change default behavior of dockerCompose plugin:
    // instead of starting ALL compose services
    // starte NONE, when startedServices list is empty
    it.enabled = dockerCompose.startedServices.get().size() > 0
}

dockerCompose {
    startedServices = []
}
