plugins {
  id 'next-app'
  id 'reverse-proxy'
  id 'next-loading-files'
}

next {
  port = '3000'
  sonarProjectKey = project.findProperty("sonar-project-key-employee-portal")
}

nextLoadingFiles {
  includeDirs = ['(baseModule)', '(businessModules)']
}

reverseProxy {
  serviceName = "employee-portal-reverse-proxy"
  mainConfigFile = "employee-portal.conf"
}
