// Copyright 2025 cronn GmbH
// SPDX-License-Identifier: AGPL-3.0-only

plugins {
  id 'next-app'
  id 'reverse-proxy'
  id 'next-loading-files'
}

next {
  port = '3000'
  sonarProjectKey = project.findProperty("sonar-project-key-employee-portal")
}

def serviceWorkerDir = layout.buildDirectory.dir("serviceWorker")

nextLoadingFiles {
  includeDirs = ['(baseModule)', '(businessModules)']
}

reverseProxy {
  serviceName = "employee-portal-reverse-proxy"
  mainConfigFile = "employee-portal.conf"
}

tasks.named('nextBuild').configure {
  outputs.dir serviceWorkerDir
}

tasks.register('copyServiceWorkerBuild', Copy) {
  dependsOn 'nextBuild'
  from serviceWorkerDir
  into "${nextBuildDirectory}/standalone/apps/employee-portal/public"
}

tasks.named('copyPublicBuildAssets').configure {
  dependsOn 'copyServiceWorkerBuild'
}
