// Copyright 2025 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.session:spring-session-data-redis'
    implementation 'org.apache.commons:commons-lang3'
    implementation 'com.google.guava:guava:latest.release'
    implementation 'io.swagger.core.v3:swagger-annotations-jakarta:latest.release'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation project(':lib-security-config')
    implementation project(':lib-matrix-client')
    implementation project(':lib-commons')
    implementation project(':lib-keycloak')
    implementation project(':util-commons')
    implementation project(':rest-client-commons')
    runtimeOnly project(':rest-service-commons')

    testImplementation project(':test-commons')
    testImplementation project(':lib-base-client')
    testImplementation project(':test-helper-commons')

    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.jsoup:jsoup:latest.release'
}

dockerCompose {
    startedServices = [
        'auth-employee-portal',
        'auth-citizen-portal',
        'auth-cache'
    ]
}

// auth should only start when Keycloak is up and provisioned by base
tasks.named("composeUp").configure {
    dependsOn project(":base").tasks.named("composeUp")
}

evaluationDependsOn(':synapse')

tasks.named("test") {
    dependsOn project(':synapse').tasks.named("composeUp")
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-auth') ?: "unspecified"
}
