spring.datasource.url=jdbc:postgresql://localhost:5447/medical_registry
spring.datasource.username=testuser
spring.datasource.password=testpassword
spring.jpa.hibernate.ddl-auto=create

# The port should match the one specified in the configuration annotated with @OpenAPIDefinition.
server.port=8097

logging.level.org.zalando.logbook=TRACE

spring.security.oauth2.client.registration.module-client.client-id=system-medical-registry
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

# TODO remove from main application.properties once the documents are finalized
#  and move the properties to the properties file specific to the health departments
#  e.g. application-health-department-frankfurt.properties.
# Also move the pdf files to the test resources dir src/test/resources
de.eshg.medical-registry.privacy-notice-location=classpath:privacy-notice.pdf
de.eshg.medical-registry.privacy-policy-location=classpath:privacy-policy.pdf