eshg.population.default-number-of-entities-to-populate.medical-registry-procedure=30

spring.datasource.url=jdbc:postgresql://localhost:5447/medical_registry
spring.datasource.username=testuser
spring.datasource.password=testpassword
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

# The port should match the one specified in the configuration annotated with @OpenAPIDefinition.
server.port=8097

logging.level.org.zalando.logbook=TRACE

spring.security.oauth2.client.registration.module-client.client-id=system-medical-registry
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

de.eshg.opening-hours.enabled=false

de.eshg.department-info.use-department-info-from-base-module=true

de.eshg.lib.procedure.search-guard.enabled=false
