/*
 * Copyright 2025 SCOOP Software GmbH, cronn GmbH
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package de.eshg.travelmedicine.util;

public enum TravelMedicineProgressEntryType {
  CERTIFICATE_FOR_HEALTH_INSURANCE,
  VACCINATION_APPLIED,
  VACCINATION_EDIT,
  PERSON_UPDATED,
  PERSON_SYNCHRONIZED,
  NEW_APPOINTMENT,
  FOLLOWUP_APPOINTMENT,
  CANCEL_APPOINTMENT,
  REBOOK_APPOINTMENT,
  ANSWER_MEDICAL_HISTORY,
  ANSWER_INFORMATION_STATEMENT,
  ADD_INFORMATION_STATEMENT,
  REMOVE_INFORMATION_STATEMENT,
  RESET_INFORMATION_STATEMENT,
}
