// Copyright 2026 SCOOP Software GmbH, cronn GmbH
// SPDX-License-Identifier: AGPL-3.0-only

plugins {
  id 'next-app'
  id 'reverse-proxy'
}

next {
  port = '3002'
  sonarProjectKey = project.findProperty("sonar-project-key-admin-portal")
}

reverseProxy {
  serviceName = "admin-portal-reverse-proxy"
  mainConfigFile = "admin-portal.conf"
}
