plugins {
    id 'eshg.java-lib'
    id 'java-test-fixtures'
}

dependencies {
    implementation 'org.slf4j:slf4j-api'

    testImplementation project(':test-commons')

    testFixturesImplementation project(':test-commons')
    testFixturesImplementation project(':test-helper-commons-spring')
    testFixturesApi testFixtures(project(':lib-service-directory-admin-api'))
    testFixturesApi 'org.testcontainers:testcontainers'
}
