spring.application.name=eshg-backend-local-service-directory
spring.security.oauth2.resourceserver.jwt.issuer-uri=${eshg.lsd-keycloak.client.url}/realms/${eshg.lsd-keycloak.client.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${eshg.lsd-keycloak.client.url}/realms/${eshg.lsd-keycloak.client.realm}/protocol/openid-connect/certs
eshg.lsd-keycloak.client.realm=eshg-lsd
eshg.lsd-keycloak.setup.realm-display-name=ESHG Local Service Directory
eshg.lsd-keycloak.client.url=${eshg.keycloak.internal.url}
eshg.lsd-keycloak.setup.admin-user.user=admin
eshg.lsd-keycloak.setup.admin-client.client-id=system-local-service-directory
eshg.lsd-keycloak.client.client-id=eshg-actor
# TODO: throw out everything into a test-helper properties that is not for production
eshg.lsd-keycloak.setup.event-expiration=P90D
eshg.lsd-keycloak.setup.session-timeout=PT15M
# Note: Keep the port in-sync with de.eshg.lsd.config.ApiDocsConfig
server.port=8089
