eshg.lsd-keycloak.client.client-secret=youWannaBuyAGreatSnowmanForCheap
spring.ssl.bundle.jks.lsd.keystore.location=classpath:keystore.p12
spring.ssl.bundle.jks.lsd.keystore.password=password
spring.ssl.bundle.jks.lsd.keystore.type=PKCS12
spring.ssl.bundle.jks.lsd.key.alias=ssl
spring.ssl.bundle.jks.lsd.key.password=password
