/*
 * Copyright 2026 cronn GmbH
 * SPDX-License-Identifier: Apache-2.0
 */

package de.eshg.lib.procedure.model;

public enum ProcedureActionType {
  APPOINTMENTS_BOOKED,
  APPOINTMENTS_CANCELED,
  APPOINTMENTS_RESCHEDULED,
  APPOINTMENTS_RESCHEDULED_AT_LEAST_ONCE,
  APPOINTMENTS_RESCHEDULED_AT_LEAST_TWICE,
  DOCUMENTS_ACCEPTED,
  DOCUMENTS_PROVIDED,
  DOCUMENTS_REJECTED,
  DOCUMENTS_REQUESTED,
  INVITATIONS_SENT,
  SUBMITTED_ANAMNESIS,
  SUBMITTED_DECLARATIONS,
  SUBMITTED_INFORMATION_SHEETS,
}
