de.eshg.opening-hours.de[0]=Mo - Do 07:30 - 16:00 Uhr
de.eshg.opening-hours.de[1]=Nur nach Terminabsprache.
de.eshg.opening-hours.de[2]=Fr 07:30 - 14:00 Uhr
de.eshg.opening-hours.de[3]=Nur nach Terminabsprache.

de.eshg.opening-hours.en[0]=Mon - Thu 07:30 AM - 4:00 PM
de.eshg.opening-hours.en[1]=By appointment only.
de.eshg.opening-hours.en[2]=Fri 07:30 AM - 2:00 PM
de.eshg.opening-hours.en[3]=By appointment only.

de.eshg.department-info.privacy-notice=classpath:templates/documents/privacy_notice.pdf
