de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[REGULAR_EXAMINATION]=60m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[ENTRY_LEVEL]=60m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[CAN_CHILD]=60m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[SPECIAL_NEEDS]=90m
de.eshg.lib.appointmentblock.locationSelectionMode=HEALTH_DEPARTMENT
de.eshg.schoolentry.directProcedureTypeAssignmentOnImport=false

de.eshg.department-info.privacy-notice=classpath:templates/documents/privacy_notice_sek.pdf

de.eshg.opening-hours.de[0]=Mo - Mi
de.eshg.opening-hours.de[1]=08:00 - 12:00 Uhr und
de.eshg.opening-hours.de[2]=
de.eshg.opening-hours.de[3]=13:30 - 16:00 Uhr
de.eshg.opening-hours.de[4]=Do
de.eshg.opening-hours.de[5]=08:00 - 12:00 Uhr und
de.eshg.opening-hours.de[6]=
de.eshg.opening-hours.de[7]=13:30 - 17:30 Uhr
de.eshg.opening-hours.de[8]=Fr
de.eshg.opening-hours.de[9]=08:00 - 13:00 Uhr
de.eshg.opening-hours.de[10]=Sprechzeiten nur nach Terminabsprache (telefonisch oder per E-Mail)

de.eshg.opening-hours.en[0]=Mon - Wed
de.eshg.opening-hours.en[1]=08:00 am - 12:00 pm and
de.eshg.opening-hours.en[2]=
de.eshg.opening-hours.en[3]=1:30 pm to 4:00 pm
de.eshg.opening-hours.en[4]=Thu
de.eshg.opening-hours.en[5]=08:00 am to 12:00 pm and
de.eshg.opening-hours.en[6]=
de.eshg.opening-hours.en[7]=1:30 pm 5:30 pm
de.eshg.opening-hours.en[8]=Fri
de.eshg.opening-hours.en[9]=08:00 am - 1:00 pm
de.eshg.opening-hours.en[10]=Office hours by appointment only (by telephone or email)

de.eshg.schoolentry.pdf-document-accent-color=#21BBEF
