de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[REGULAR_EXAMINATION]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[ENTRY_LEVEL]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[CAN_CHILD]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[SPECIAL_NEEDS]=60m
de.eshg.lib.appointmentblock.locationSelectionMode=HEALTH_DEPARTMENT
de.eshg.schoolentry.directProcedureTypeAssignmentOnImport = true

de.eshg.opening-hours.de[0]=Mo - Do 08:00 - 12:00 Uhr sowie Mo, Di und Do 13:00 - 16:00 Uhr
de.eshg.opening-hours.de[1]=Nur nach Terminabsprache.
de.eshg.opening-hours.de[2]=Fr 08:00 - 13:00 Uhr
de.eshg.opening-hours.de[3]=Nur nach Terminabsprache.

de.eshg.opening-hours.en[0]=Mon - Thu 08:00 AM - 12:00 PM and Mon, Tue, Thu 1:00 PM - 4:00 PM
de.eshg.opening-hours.en[1]=By appointment only.
de.eshg.opening-hours.en[2]=Fri 08:00 AM - 1:00 PM
de.eshg.opening-hours.en[3]=By appointment only.

de.eshg.schoolentry.pdf-document-accent-color=#80cc28

de.eshg.department-info.privacy-notice=classpath:templates/documents/privacy_notice_odenwaldkreis.pdf
