de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[REGULAR_EXAMINATION]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[ENTRY_LEVEL]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[CAN_CHILD]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[SPECIAL_NEEDS]=60m

# opening hours for health department frankfurt are configured in application.properties
