# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5435/schoolentry
spring.datasource.username=testuser
spring.datasource.password=testpassword
spring.jpa.hibernate.ddl-auto=validate

spring.config.import=classpath:/school-entry-hibernate-common.properties

# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

# Note: Keep the port in-sync with de.eshg.schoolentry.config.OpenApiConfiguration
server.port=8082

logging.level.org.zalando.logbook=TRACE

spring.security.oauth2.client.registration.module-client.client-id=system-school-entry
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

eshg.citizen-portal.reverse-proxy.url=http://localhost:4001

# F�r alle Kinder, die bis einschlie�lich 1. Juli geboren sind und damit bis zum 30. Juni das sechste Lebensjahr vollenden, beginnt am 1. August die Schulpflicht.
# See https://kultus.hessen.de/schulsystem/schulformen-und-bildungsgaenge/grundschule/grundschule
de.eshg.schoolentry.max-date-of-birth-for-regular-school-entry=--07-01
de.eshg.schoolentry.max-date-of-birth-for-regular-school-entry-is-inclusive=true

de.eshg.schoolentry.pdf-document-accent-color=#21BBEF

de.eshg.schoolentry.privacy-notice-location=classpath:templates/documents/privacy_notice.pdf
de.eshg.schoolentry.privacy-policy-location=classpath:templates/documents/privacy_policy.pdf

eshg.population.default-number-of-entities-to-populate.school-entry-procedure=50
eshg.population.default-number-of-entities-to-populate.appointment-block-group=50

de.eshg.schoolentry.bulkCreateAppointmentsMinLeadTime=P4W
de.eshg.schoolentry.citizens.freeAppointmentsMinLeadTime=P2W
de.eshg.schoolentry.citizens.freeAppointmentsMaxLeadTime=P6W

de.eshg.lib.appointmentblock.createAppointmentBlockForCurrentUser=false
de.eshg.lib.appointmentblock.overwrite-appointment-type-configuration-with-properties=true
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[REGULAR_EXAMINATION]=45m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[ENTRY_LEVEL]=45m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[CAN_CHILD]=45m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[SPECIAL_NEEDS]=45m

de.eshg.schoolentry.opening-hours.de[0]=Mo - Do 07:30 - 16:00 Uhr
de.eshg.schoolentry.opening-hours.de[1]=Nur nach Terminabsprache.
de.eshg.schoolentry.opening-hours.de[2]=Fr 07:30 - 14:00 Uhr
de.eshg.schoolentry.opening-hours.de[3]=Nur nach Terminabsprache.

de.eshg.schoolentry.opening-hours.en[0]=Mon - Thu 07:30 AM - 4:00 PM
de.eshg.schoolentry.opening-hours.en[1]=By appointment only.
de.eshg.schoolentry.opening-hours.en[2]=Fri 07:30 AM - 2:00 PM
de.eshg.schoolentry.opening-hours.en[3]=By appointment only.
