de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[REGULAR_EXAMINATION]=40m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[ENTRY_LEVEL]=60m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[CAN_CHILD]=40m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[SPECIAL_NEEDS]=40m
de.eshg.lib.appointmentblock.locationSelectionMode=HEALTH_DEPARTMENT
de.eshg.schoolentry.directProcedureTypeAssignmentOnImport=false

de.eshg.department-info.privacy-notice=classpath:templates/documents/privacy_notice_wiesbaden.pdf

de.eshg.opening-hours.de[0]=Mo - Fr 08:00 - 12:00 Uhr
de.eshg.opening-hours.de[1]=Sprechstunde nur nach Terminabsprache.

de.eshg.opening-hours.en[0]=Mon - Fri 08:00 AM - 12:00 PM
de.eshg.opening-hours.en[1]=By appointment only.

de.eshg.schoolentry.pdf-document-accent-color=#FFFFFF
