de.eshg.schoolentry.feature-toggle.enabled-new-features=\
  MEDICAL_REPORT,\
  MERGE_PROCEDURES_ON_IMPORT,\
  CLOSE_PROCEDURE,\
  SEARCH_BY_KNOWLEDGE_FACTORS,\
  SCHOOL_YEAR,\
  SCHOOL_INFO_LETTER,\
  DELETE_PROCEDURE,\
  WAITING_ROOM,\
  REOPEN_PROCEDURE
