plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':lib-base-client')
    implementation project(':lib-procedures')
    implementation project(':lib-appointmentblock')
    implementation project(':lib-calendar')
    implementation project(':business-module-persistence-commons')
    implementation project(":lib-document-generator")
    implementation project(':lib-scheduling')
    implementation project(':rest-oauth-client-commons')
    implementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'
    implementation 'com.google.guava:guava'

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':lib-document-generator'))
    testImplementation testFixtures(project(':lib-procedures'))
}

dockerCompose {
    startedServices = [
        'sti-protection',
        'sti-protection-db'
    ]
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-sti-protection') ?: "unspecified"
}

