plugins {
    id "eshg.java-lib"
    id "eshg.base-test-dependency"
    id "java-test-fixtures"
}

dependencies {
    api project(':lib-commons')
    api project(':lib-procedures-api')
    api project(':lib-four-eyes-principle')
    api project(':lib-notification')
    api project(':lib-auditlog')
    api project(':business-module-persistence-commons')

    implementation project(':lib-commons')
    implementation project(':base-api')
    implementation project(':business-module-commons')
    implementation project(':rest-oauth-client-commons')
    implementation project(':file-commons')
    implementation project(':lib-xdomea')

    implementation 'jakarta.persistence:jakarta.persistence-api'
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.data:spring-data-jpa'
    implementation 'org.springframework:spring-aspects'
    implementation 'org.hibernate.validator:hibernate-validator'
    implementation 'org.springframework:spring-webmvc'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.hibernate.orm:hibernate-core'
    implementation 'org.hibernate.orm:hibernate-envers'
    implementation 'de.cronn:reflection-util:latest.release'
    implementation 'org.apache.commons:commons-text:latest.release'

    implementation platform('org.apache.tika:tika-bom:latest.release')
    implementation 'org.apache.tika:tika-core'
    implementation 'org.apache.tika:tika-parser-pdf-module'
    implementation 'com.drewnoakes:metadata-extractor:latest.release'
    implementation 'org.eclipse.angus:jakarta.mail:latest.release'
    implementation 'org.verapdf:validation-model-jakarta:latest.release'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-hibernate6'

    implementation 'org.bouncycastle:bcpkix-jdk18on:latest.release'
    implementation 'org.bouncycastle:bcmail-jdk18on:latest.release'

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    testFixturesImplementation project(':test-commons')
    testFixturesImplementation 'org.springframework.boot:spring-boot-test'
    testFixturesImplementation 'org.springframework.data:spring-data-jpa'
    testFixturesImplementation 'org.assertj:assertj-core'

    testImplementation project(':rest-oauth-client-commons')
    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':base-api'))
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation "org.testcontainers:junit-jupiter"
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.instancio:instancio-core:latest.release'
    testImplementation 'org.apache.commons:commons-text:latest.release'
    testImplementation 'org.apache.commons:commons-collections4:latest.release'

    testRuntimeOnly project(':lib-base-client')
    testRuntimeOnly 'org.postgresql:postgresql'
    testRuntimeOnly 'com.h2database:h2'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add("-AaddSuppressWarningsAnnotation=true")
}
