// Copyright 2025 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

import org.gradle.api.file.RegularFile
import org.gradle.api.provider.Property
import org.apache.commons.io.FilenameUtils
import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

import java.nio.file.Files

plugins {
  id 'workspace-package'
  id 'tsup'
}

typescript {
  // ⚠⚠⚠ Note ⚠⚠⚠: Please adjust the tsconfig.json when changing includes/excludes here
  include = ['src/**/*.ts']
}

interface ApiPackagePluginConfiguration {
  RegularFileProperty getInputSpec()
}

def apiPackageExtension = project.extensions.create('apiPackage', ApiPackagePluginConfiguration)

def openapiGroupName = 'openapi'
def srcDir = layout.projectDirectory.dir('src')

static String emulateSymlinkIfNecessary(java.nio.file.Path path) {
  if (Files.isSymbolicLink(path)) {
    return path.toString()
  } else if (Files.isRegularFile(path)) {
    // Try to emulate git symlinks on Windows
    def lines = Files.readAllLines(path)
    if (lines.size() == 1) {
      String symlink = lines.get(0)
      return path.getParent().resolve(symlink)
    } else {
      // Required for the opencode pipeline
      return path.toString();
    }
  } else {
    throw new IllegalArgumentException("${path} is neither a symlink nor a regular file")
  }
}

def generateTaskProvider = tasks.register('generate', GenerateTask) {
  group = openapiGroupName
  dependsOn rootProject.tasks.installDependencies
  generatorName = 'typescript-fetch'
  inputSpec = emulateSymlinkIfNecessary(apiPackageExtension.inputSpec.get().asFile.toPath())
  outputDir = srcDir.asFile.path
  modelNamePrefix = 'Api'
  additionalProperties = [
    'supportsES6'                : 'true',
    'withInterfaces'             : 'true',
    'useSingleRequestParameter'  : 'false',
    // We need the "modern" discriminator behavior for the discriminator columns.
    // See https://blog.cronn.de/en/java/rest/2024/01/02/grand-cronn-pet-hotel.html
    // However, it seems to be not as battle tested and thus it generates duplicated imports that we fix via fixDuplicateImports()
    'legacyDiscriminatorBehavior': 'false',
    // Override default enum suffix 'Enum'
    'enumNameSuffix'             : ''
  ]

  doFirst {
    delete srcDir
  }

  doLast {
    // See the comment at the "legacyDiscriminatorBehavior" property
    fixDuplicateImports(srcDir)
  }
}

def cleanTaskProvider = tasks.register('cleanGeneratedFiles', Delete) {
  group = openapiGroupName
  delete srcDir
}

// Fix/workaround for https://github.com/OpenAPITools/openapi-generator/issues/15637
private void fixDuplicateImports(Directory outputDir) {
  fileTree("${outputDir}/models").matching {
    include "**/*.ts"
  }.visit { FileVisitDetails details ->
    details.file.text = details.file.text.replaceAll(/(?m)import \{(\s*.*?FromJSONTyped,?)+\s*\} from '\.\/index';/, "// removed duplicate import here")

    // Self imports, needed when discriminator for self exists
    def importName = FilenameUtils.removeExtension(details.file.name)
    details.file.text = details.file.text.replaceAll(/(?m)import type \{\s+$importName\s+} from '\.\/$importName';/, "// removed self import here")
    details.file.text = details.file.text.replaceAll(/(?m)import \{\s+(?:\w+(?:FromJSON|FromJSONTyped|ToJSON),\s+){3}} from '\.\/$importName';/, "// removed self import here")
  }
}

tasks.register('assemble') {
  group = 'package'
  dependsOn 'compile'
  dependsOn 'bundle'
}

tasks.register('build') {
  group = 'package'
  dependsOn 'check'
  dependsOn 'assemble'
}

def typesDir = layout.buildDirectory.dir('types')
def configDir = rootProject.layout.projectDirectory.dir('config')

tasks.named('compile').configure {
  dependsOn generateTaskProvider
  inputs.file configDir.file('tsconfig.lib.json')
  outputs.dir typesDir

  doFirst {
    delete typesDir
  }
}

tasks.named('bundle').configure {
  dependsOn generateTaskProvider
  inputs.file configDir.file('tsconfig.lib.json')
}

tasks.named('clean').configure {
  dependsOn cleanTaskProvider
}
