// Copyright 2025 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

import com.github.gradle.node.pnpm.task.PnpmTask

plugins {
  id 'source-checks'
  id 'vitest'
  id 'tsup'
}

prettier {
  include = ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.json']
  additionalExcludes = ['data/test']
}

eslint {
  include = ['src/**/*.ts', 'src/**/*.tsx']
}

typescript {
  // ⚠⚠⚠ Note ⚠⚠⚠: Please adjust the tsconfig.json when changing includes/excludes here
  include = ['**/*.ts', '**/*.tsx', '*.js']
}

def configDir = rootProject.layout.projectDirectory.dir('config')
def typesDir = project.layout.buildDirectory.dir('types')

tasks.register('assemble') {
  group = 'package'
  dependsOn 'compile'
  dependsOn 'bundle'
}

tasks.register('build') {
  group = 'package'
  dependsOn 'check'
  dependsOn 'assemble'
}

tasks.named('compile').configure {
  outputs.dir typesDir

  doFirst {
    delete typesDir
  }
}

tasks.named('lint').configure {
  inputs.file configDir.file('eslint.next.js')
}

tasks.named('lintFix').configure {
  inputs.file configDir.file('eslint.next.js')
}

tasks.named('compile').configure {
  inputs.file configDir.file('tsconfig.lib.json')
}

tasks.named('bundle').configure {
  mustRunAfter 'format', 'lintFix'
  inputs.file configDir.file('tsconfig.lib.json')
}

tasks.named('test').configure {
  inputs.file configDir.file('tsconfig.lib.json')
}
