// Copyright 2026 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.github.gradle.node.pnpm.task.PnpmTask
import com.github.gradle.node.task.NodeTask
import de.eshg.frontend.PnpmTaskWithNpmDependencies
import de.eshg.frontend.PnpmTaskWithProjectDependencies

plugins {
  id 'source-checks'
  id 'vitest'
  id 'com.bmuschko.docker-remote-api'
  id 'org.sonarqube'
  id "eshg.image-push-sign"
}

interface NextPluginConfiguration {
  Property<String> getPort()
  Property<String> getSonarProjectKey()
}

def srcDir = "${projectDir}/src"
def nextDir = "${projectDir}/.next"
def nextBuildDir = layout.buildDirectory.dir("nextApp")

def nextExtension = project.extensions.create('next', NextPluginConfiguration)
def dockerBuildDir = layout.buildDirectory.dir('docker')
def projectPath = file(rootDir).relativePath(projectDir)

prettier {
  include = ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.json']
  additionalExcludes = ['next-env.d.ts', '.next', 'data/test']
}

eslint {
  include = ['src/**/*.ts', 'src/**/*.tsx', 'src/**/*.js']
}

typescript {
  // ⚠⚠⚠ Note ⚠⚠⚠: Please adjust the tsconfig.json when changing includes/excludes here
  include = ['**/*.ts', '**/*.tsx', '**/*.js']
  additionalExcludes = ['next-env.d.ts', '.next']
}

ext {
  nextBuildDirectory = nextBuildDir.get()
}

tasks.named('lint').configure {
  inputs.files "${rootDir}/config/eslint.next.js"
}

tasks.named('lintFix').configure {
  inputs.files "${rootDir}/config/eslint.next.js"
}

tasks.named('test').configure {
  inputs.file "${rootDir}/config/tsconfig.next.json"
}

tasks.register('copyStaticBuildAssets', Copy) {
  from("${nextDir}/static")
  into "${nextBuildDir.get()}/standalone/${projectPath}/.next/static"
}

tasks.register('copyPublicBuildAssets', Copy) {
  from("${projectDir}/public")
  into "${nextBuildDir.get()}/standalone/${projectPath}/public"
}

tasks.register('nextBuild', PnpmTaskWithProjectDependencies) {
  def bundlerArgs = project.hasProperty('turbo') ? ['--turbo'] : []
  inputs.file "${rootDir}/config/tsconfig.base.json"
  inputs.file "${projectDir}/tsconfig.json"
  inputs.file "${rootDir}/config/next.base.ts"
  inputs.file "${projectDir}/next.config.ts"
  inputs.files fileTree(srcDir)

  outputs.dir "${nextDir}/server"
  outputs.dir "${nextDir}/standalone"
  outputs.dir "${nextDir}/static"

  outputs.cacheIf { true }

  args = ['next', 'build'] + bundlerArgs
}

tasks.register('assemble', Copy) {
  dependsOn 'nextBuild'
  finalizedBy 'copyStaticBuildAssets'
  finalizedBy 'copyPublicBuildAssets'

  from (nextDir) {
    include 'standalone/**'
  }

  into nextBuildDir
}

tasks.register('build') {
  dependsOn 'check'
  dependsOn 'assemble'
}

tasks.register('analyzeBundle', PnpmTaskWithNpmDependencies) {
  dependsOn 'prepareEnvironment'
  inputs.files fileTree(srcDir)

  outputs.files fileTree(nextDir) {
    include 'analyze'
  }
  environment = ['ANALYZE_BUNDLE': 'true']
  args = ['next', 'build']
}

tasks.register('createDockerfile', Dockerfile) {
  dependsOn 'assemble'

  def groupName = 'nodejs'
  def userName = 'nextjs'

  from(nodeDockerImage)

  workingDir('/app')

  environmentVariable('NODE_ENV', 'production')
  environmentVariable('NEXT_TELEMETRY_DISABLED', '1')

  runCommand("addgroup --system --gid 10001 ${groupName}")
  runCommand("adduser --system --shell /usr/sbin/nologin --home /app --ingroup ${groupName} --uid 10001 ${userName}")

  user("${userName}:${groupName}")

  environmentVariable('PORT', nextExtension.port.get())
  exposePort(nextExtension.port.get() as int)

  copyFile(new Dockerfile.CopyFile('standalone', './').withChown("${userName}:${groupName}"))

  defaultCommand(
    'node',
    "${projectPath}/server.js"
  )
}

tasks.register('copyAssetsToDockerBuildDir', Copy) {
  dependsOn 'assemble'
  mustRunAfter 'copyStaticBuildAssets'
  mustRunAfter 'copyPublicBuildAssets'

  from(file(nextBuildDir)) {
    include 'standalone/**'
  }

  into dockerBuildDir
}

def buildDockerImage = tasks.register('buildDockerImage', DockerBuildImage) {
  dependsOn 'createDockerfile'
  inputs.files(tasks.named('copyAssetsToDockerBuildDir'))

  if (getTagName() != null) {
    images.add(getImageNameWithTag())
  } else {
    images.add(getImageNameWithLatestTag())
  }
}

rootProject.tasks.named('composeUp').configure {
  dependsOn buildDockerImage
}

tasks.register('run', NodeTask) {
  dependsOn 'assemble'

  environment = ['HOSTNAME': '0.0.0.0', 'PORT': nextExtension.port.get()]
  script = file("${nextBuildDir.get()}/standalone/${projectPath}/server.js")
}

tasks.register('runDev', PnpmTask) {
  dependsOn 'prepareEnvironment'
  def bundlerArgs = project.hasProperty('webpack') ? [] : ['--turbo']
  args = ['next', 'dev', '--port', nextExtension.port.get()] + bundlerArgs
}

tasks.named('clean').configure {
  delete nextDir
}

tasks.named('sonar').configure {
  dependsOn rootProject.tasks.named('nodeSetup')
}

sonar {
  properties {
    property 'sonar.sources', './src/'
    property 'sonar.tests', './src/'
    property 'sonar.test.inclusions', [
      '**/*.test.tsx',
      '**/*.test.ts'
    ]
    property 'sonar.projectKey', nextExtension.sonarProjectKey.get()
    property 'sonar.qualitygate.wait', true
    property 'sonar.gradle.skipCompile', true
    property 'sonar.nodejs.executable', node.getResolvedNodeDir().get().file('bin/node')
  }
}
