plugins {
  id 'com.github.node-gradle.node'
}

node {
  version = '22.15.0'
  pnpmVersion = '10.10.0'
  download = true
  workDir = file("${rootProject.projectDir}/.gradle/nodejs")
  pnpmWorkDir = file("${rootProject.projectDir}/.gradle/pnpm")
}

ext {
  nodeDockerImage = "node:${node.version.get()}-alpine@sha256:ad1aedbcc1b0575074a91ac146d6956476c1f9985994810e4ee02efd932a68fd"
}

tasks.register('cleanDependencies', Delete) {
  group = 'workspace'
  delete "${projectDir}/node_modules"
}

def isRootProject() {
  project.name == rootProject.name
}

// prevent duplicate node installation in subprojects
tasks.named('nodeSetup').configure {
  onlyIf('run only in root project') {
    isRootProject()
  }
}

// prevent duplicate pnpm installation in subprojects
tasks.named('pnpmSetup').configure {
  onlyIf('run only in root project') {
    isRootProject()
  }
}
