plugins {
  id 'com.github.node-gradle.node'
}

def gradleDir = rootProject.layout.projectDirectory.dir('.gradle')
def nodeSetupDir = gradleDir.dir('nodejs')
def pnpmSetupDir = gradleDir.dir('pnpm')

node {
  version = '22.15.1'
  pnpmVersion = '10.11.0'
  download = true
  workDir = nodeSetupDir
  pnpmWorkDir = pnpmSetupDir
}

ext {
  nodeDockerImage = "node:${node.version.get()}-alpine@sha256:152270cd4bd094d216a84cbc3c5eb1791afb05af00b811e2f0f04bdc6c473602"
}

def cleanDependenciesTask = tasks.register('cleanDependencies', Delete) {
  group = 'workspace'
  delete "${projectDir}/node_modules"
}

def cleanNodeSetupTask = tasks.register('cleanNodeSetup', Delete) {
  delete nodeSetupDir
  onlyIf('run only in root project') {
    isRootProject()
  }
}

def cleanPnpmSetupTask = tasks.register('cleanPnpmSetup', Delete) {
  delete pnpmSetupDir
  onlyIf('run only in root project') {
    isRootProject()
  }
}

tasks.register('clean', Delete) {
  dependsOn cleanDependenciesTask
  dependsOn cleanNodeSetupTask
  dependsOn cleanPnpmSetupTask
  delete project.layout.buildDirectory
}

def isRootProject() {
  project.name == rootProject.name
}

// prevent duplicate node installation in subprojects
tasks.named('nodeSetup').configure {
  onlyIf('run only in root project') {
    isRootProject()
  }
}

// prevent duplicate pnpm installation in subprojects
tasks.named('pnpmSetup').configure {
  onlyIf('run only in root project') {
    isRootProject()
  }
}
