plugins {
  id 'com.github.node-gradle.node'
}

node {
  version = '20.18.0'
  pnpmVersion = '9.12.1'
  download = true
  workDir = file("${rootProject.projectDir}/.gradle/nodejs")
  pnpmWorkDir = file("${rootProject.projectDir}/.gradle/pnpm")
}

ext {
  nodeDockerImage = "node:${node.version.get()}-alpine@sha256:c13b26e7e602ef2f1074aef304ce6e9b7dd284c419b35d89fcf3cc8e44a8def9"
}

tasks.register('cleanDependencies', Delete) {
  delete "${projectDir}/node_modules"
}

def isRootProject() {
  project.name == rootProject.name
}

// prevent duplicate node installation in subprojects
tasks.named('nodeSetup').configure {
  onlyIf('run only in root project') {
    isRootProject()
  }
}

// prevent duplicate pnpm installation in subprojects
tasks.named('pnpmSetup').configure {
  onlyIf('run only in root project') {
    isRootProject()
  }
}
