// Copyright 2025 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

import com.github.gradle.node.pnpm.task.PnpmTask
import de.eshg.frontend.IncludesAndExcludes
import de.eshg.frontend.TypescriptDefaults

plugins {
  id 'workspace-package'
}

def prettierExtension = project.extensions.create('prettier', IncludesAndExcludes)
def eslintExtension = project.extensions.create('eslint', IncludesAndExcludes)

def getPrettierInputs = {
  return fileTree(projectDir) {
    include prettierExtension.include.get()
    exclude TypescriptDefaults.getAllExcludes(prettierExtension.additionalExcludes)
  }
}

def getPrettierInputArgs = (ConfigurableFileTree formattedFiles) -> {
  def includes = formattedFiles.patterns.includes
  def excludes = formattedFiles.patterns.excludes.collect { exclude -> "!$exclude" }
  return excludes + includes
}

def getEslintInputs = {
  return fileTree(projectDir) {
    include eslintExtension.include.get()
    exclude TypescriptDefaults.getAllExcludes(eslintExtension.additionalExcludes)
  }
}

def getEslintInputArgs = (ConfigurableFileTree lintedFiles) -> {
  def includes = lintedFiles.patterns.includes
  def excludes = lintedFiles.patterns.excludes.collect { exclude ->
    {
      return ['--ignore-pattern', exclude]
    }
  }.flatten()
  return excludes + includes
}

def prettierCacheFile = "${projectDir}/build/.prettiercache"
def defaultPrettierArgs = [
  '--no-error-on-unmatched-pattern',
  '--cache',
  "--cache-location=${prettierCacheFile}"
]

tasks.register('format', PnpmTask) {
  group = 'verification'
  dependsOn rootProject.tasks.installDependencies
  mustRunAfter 'compile', 'lintFix'
  inputs.file "${rootDir}/.editorconfig"
  inputs.file "${rootDir}/.prettierrc"
  if (file("${projectDir}/.prettierignore").exists()) {
    inputs.file "${projectDir}/.prettierignore"
  }
  def formattedFiles = getPrettierInputs()
  inputs.files formattedFiles
  outputs.files formattedFiles
  outputs.file prettierCacheFile
  args = ['prettier', '--write', '--list-different'] + defaultPrettierArgs + getPrettierInputArgs(formattedFiles)
}

tasks.register('formatCheck', PnpmTask) {
  group = 'verification'
  dependsOn rootProject.tasks.installDependencies
  inputs.file "${rootDir}/.editorconfig"
  inputs.file "${rootDir}/.prettierrc"
  if (file("${projectDir}/.prettierignore").exists()) {
    inputs.file "${projectDir}/.prettierignore"
  }
  def formattedFiles = getPrettierInputs()
  inputs.files formattedFiles
  outputs.file prettierCacheFile
  args = ['prettier', '--check'] + defaultPrettierArgs + getPrettierInputArgs(formattedFiles)
}

def eslintConfigFiles = [
  "${rootDir}/config/eslint.base.js",
  "${projectDir}/eslint.config.js"
]

def eslintCacheFile = "${projectDir}/build/.eslintcache"
def defaultEslintArgs = [
  '--max-warnings=0',
  '--no-error-on-unmatched-pattern',
  '--cache',
  "--cache-location=${eslintCacheFile}"
]

tasks.register('lint', PnpmTask) {
  group = 'verification'
  dependsOn 'prepareEnvironment'
  dependsOn 'compile'
  inputs.files eslintConfigFiles
  def inputFiles = getEslintInputs()
  inputs.files inputFiles
  outputs.file eslintCacheFile
  args = ['eslint'] + defaultEslintArgs + getEslintInputArgs(inputFiles)
}

tasks.register('lintFix', PnpmTask) {
  group = 'verification'
  dependsOn 'prepareEnvironment'
  dependsOn 'compile'
  inputs.files eslintConfigFiles
  def inputFiles = getEslintInputs()
  inputs.files inputFiles
  outputs.file eslintCacheFile
  args = ['eslint', '--fix'] + defaultEslintArgs + getEslintInputArgs(inputFiles)
}

tasks.register('fix') {
  group = 'verification'
  dependsOn 'format'
  dependsOn 'lintFix'
}

tasks.named('check').configure {
  group = 'verification'
  dependsOn 'formatCheck'
  dependsOn 'lint'
}
