// Copyright 2025 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

import com.github.gradle.node.pnpm.task.PnpmTask
import de.eshg.frontend.PnpmTaskWithProjectDependencies

plugins {
  id 'workspace-package'
}

def srcDir = project.layout.projectDirectory.dir('src')
def libDir = project.layout.buildDirectory.dir('lib')

def isBundlingActive() {
  if (!project.hasProperty('skipBundle')) {
    return true
  }

  def skippedProjects = project.property('skipBundle').toString().split(",")
  return !skippedProjects.contains(project.name)
}

tasks.register('bundle', PnpmTaskWithProjectDependencies) {
  group = 'package'

  outputs.cacheIf { true }

  inputs.file "${rootDir}/config/tsup.base.ts"
  inputs.file "${projectDir}/tsconfig.json"
  inputs.file "${projectDir}/tsup.config.ts"
  inputs.files fileTree(srcDir)
  outputs.dir libDir

  args = ['tsup']

  onlyIf {
    isBundlingActive()
  }
}

tasks.register('dev', PnpmTask) {
  group = 'package'
  dependsOn rootProject.tasks.installDependencies
  args = ['tsup', '--watch']
}
