import com.github.gradle.node.pnpm.task.PnpmTask

plugins {
  id 'workspace-package'
}

def testEnvironment = ['TZ': 'UTC']
def testConfigFiles = [
  "${rootDir}/config/tsconfig.base.json",
  "${rootDir}/config/vitest.base.ts",
  "${projectDir}/tsconfig.json",
  "${projectDir}/vitest.config.ts"
]
def testSrcDir = "${projectDir}/src"

tasks.named('check').configure { dependsOn 'test' }

tasks.register('test', PnpmTask) {
  dependsOn 'prepareEnvironment'
  environment = testEnvironment
  inputs.files testConfigFiles
  inputs.dir testSrcDir
  outputs.upToDateWhen { true }
  // Pass with no tests to avoid writing a dummy test within the new portal tests.
  // This parameter can be removed once we have tests in each portal project.
  args = ['vitest', 'run', '--passWithNoTests', '--silent']
}

tasks.register('testWatch', PnpmTask) {
  dependsOn 'prepareEnvironment'
  environment = testEnvironment
  args = ['vitest', 'watch']
}
