// Copyright 2025 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

import com.github.gradle.node.pnpm.task.PnpmTask
import de.eshg.frontend.ProjectReferences

plugins {
  id 'typescript'
}

tasks.register('prepareEnvironment') {
  dependsOn rootProject.tasks.installDependencies
  dependsOn ProjectReferences.getDependencies(project).collect { projectName ->
    project(projectName).tasks.named('assemble')
  }
}

tasks.register('check') {
  group = 'verification'
  dependsOn 'compile'
}

tasks.register('addWorkspaceDependency', PnpmTask) {
  group = 'workspace'
  def saveDevArg = project.hasProperty('dev') ? ['--save-dev'] : []
  args = project.hasProperty('package') ? ['add', "@eshg/${project.property('package')}@workspace:*"] + saveDevArg : []

  finalizedBy rootProject.tasks.updateProjectReferences
}

tasks.register('inspect', PnpmTask) {
  group = 'maintenance'
  args = ['dlx', 'knip']
}

tasks.register('inspectFix', PnpmTask) {
  group = 'maintenance'
  args = ['dlx', 'knip', '--fix']
}
