import com.github.gradle.node.pnpm.task.PnpmTask

plugins {
  id 'typescript'
}

tasks.register('prepareEnvironment') {
  dependsOn rootProject.tasks.installDependencies

  def gradleDependenciesJson = project.layout.projectDirectory.file("gradleDependencies.json").asFile
  if (gradleDependenciesJson.exists()) {
    def gradleDependencies = new groovy.json.JsonSlurper().parseText(gradleDependenciesJson.text)
    dependsOn gradleDependencies.dependencies.collect {
      project(it).tasks.named('assemble')
    }
  }
}

tasks.register('check') {
  group = 'verification'
  dependsOn 'compileCheck'
}

tasks.register('clean', Delete) {
  dependsOn 'cleanDependencies'
  delete layout.buildDirectory
}

tasks.register('addWorkspaceDependency', PnpmTask) {
  group = 'workspace'
  args = project.hasProperty('package') ? ['add', "@eshg/${project.property('package')}@workspace:*"] : []

  finalizedBy rootProject.tasks.updateProjectReferences
}
