# Copyright 2025 cronn GmbH
# SPDX-License-Identifier: AGPL-3.0-only

variables:
  GRADLE_BASE_IMAGE: gradle:8.14.3-jdk21-jammy@sha256:07d6a8466f384729663705497a041076c400e6d63ff4b07f6657b25c2e0c96e9

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

stages:
  - build
  - release

🎉 create:release:
  stage: release
  needs: [ ]
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  release:
    tag_name: $CI_COMMIT_TAG
    name: "Release $CI_COMMIT_TAG"
    description: "Release created by the pipeline"
  script:
    - echo "Creating a release"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

🏗 build:frontend:
  stage: build
  needs: [ ]
  image: ${GRADLE_BASE_IMAGE}
  script:
    # Dont build the pdf converter client because Docker in docker doesnt work
    - gradle --no-daemon build -x test -x lint -x formatCheck -x :pdf-converter-portal:build -x :lib-gs-wasm:build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

🏗 build:backend:
  image: ${GRADLE_BASE_IMAGE}
  stage: build
  needs: [ ]
  script:
    - cd backend
    - gradle --continue build -x test -x findUnusedValidationFiles -x composeUp -x buildDockerImage -PuseDependencyProxy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
