// Copyright 2025 cronn GmbH
// SPDX-License-Identifier: AGPL-3.0-only

import com.github.gradle.node.pnpm.task.PnpmTask
import groovy.io.FileVisitResult
import org.jetbrains.gradle.ext.JUnit

buildscript {
  apply from: "${rootDir}/gradle/buildscriptRepository.gradle"

  dependencies {
    classpath 'com.github.node-gradle:gradle-node-plugin:latest.release'
  }
}

plugins {
  id 'com.avast.gradle.docker-compose'
  id 'org.jetbrains.gradle.plugin.idea-ext' version 'latest.release'
  id 'org.sonarqube' version 'latest.release' apply false
  id 'meta-updater'
}

if (project.hasProperty('projectVersion')) {
  version = "${projectVersion}"
}

dockerCompose {
  projectName = "frontend"
}

apply from: "startLocal.gradle"

//CAUTION: run ./gradlew wrapper (twice) after changes to this task!
//See https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper
wrapper {
  gradleVersion = '9.1.0'
  distributionType = Wrapper.DistributionType.ALL
}

Set<File> collectDataTestDirectoriesToExclude() {
  def dataTestOutput = java.nio.file.Path.of("data/test/output")
  def dataTestTmp = java.nio.file.Path.of("data/test/tmp")
  Set<String> directoriesToSkip = ['node_modules', '.next', '.gradle', 'build', 'out']
  Set<File> dataTestDirectoriesToExclude = new TreeSet<>()
  project.file(project.rootDir).traverse(
    type: groovy.io.FileType.DIRECTORIES,
    maxDepth: 5,
    preDir: { dir ->
      if (directoriesToSkip.contains(dir.name)) {
        return FileVisitResult.SKIP_SUBTREE
      }
    }) { File dir ->
    def path = dir.toPath()
    if (path.endsWith(dataTestOutput) || path.endsWith(dataTestTmp)) {
      dataTestDirectoriesToExclude.add(dir)
    }
  }
  return dataTestDirectoriesToExclude
}

idea {
  module {
    excludeDirs = collectDataTestDirectoriesToExclude()
    downloadJavadoc = true
    downloadSources = true
  }
  project {
    settings {
      compiler {
        javac {
          javacAdditionalOptions = "-parameters"
        }
      }
      runConfigurations {
        defaults(JUnit) {
          vmParameters = "-ea -Xmx512m -Duser.country=de -Duser.language=en -Duser.timezone=Europe/Berlin -Deshg.testcontainers.enabled=false"
        }
      }
    }
  }
}

allprojects {
  group = 'de.eshg.frontend'

  apply from: "${rootDir}/gradle/repository.gradle"
  apply plugin: 'node'

  // see https://docs.gradle.org/current/userguide/dependency_locking.html#lock_all_configurations_in_one_build_execution
  tasks.register('resolveAndLockAll') {
    notCompatibleWithConfigurationCache('Filters configurations at execution time')
    doFirst {
      assert gradle.startParameter.writeDependencyLocks: "$path must be run from the command line with the `--write-locks` flag"
    }
    doLast {
      configurations.findAll {
        // Add any custom filtering on the configurations to be resolved
        it.canBeResolved
      }.each { it.resolve() }
    }
  }
}

subprojects {
  // Note: Unfortunately we cannot define the buildscript repository in the allprojects block
  // Gradle requires to define the buildscript of the root project pretty much at the beginning of this file.
  // We also must not redefine the buildscript, thus we end up defining it just for the subprojects
  buildscript {
    apply from: "${rootDir}/gradle/buildscriptRepository.gradle"
  }
}

def depsInputs = [
  "${rootDir}/pnpm-workspace.yaml",
  "${rootDir}/pnpm-lock.yaml"
]
def nodeModulesDir = "node_modules"

def installDependencies = tasks.register('installDependencies', PnpmTask) {
  description = "Install missing dependencies based on the pnpm-lock.yaml file"
  inputs.files depsInputs
  outputs.dir nodeModulesDir
  subprojects {
    outputs.dir "${projectDir}/${nodeModulesDir}"
  }
  args = ['install', '--frozen-lockfile']
}

tasks.register('updateLockfile', PnpmTask) {
  group = 'maintenance'
  description = "Install missing dependencies and update the lock file. Use this to add new dependencies."
  inputs.files depsInputs
  outputs.dir nodeModulesDir
  subprojects {
    outputs.dir "${projectDir}/${nodeModulesDir}"
  }
  args = ['install', '--recursive']
}

tasks.register('updateDependencies', PnpmTask) {
  dependsOn 'updateSvgSanitizer'
  dependsOn 'updatePerformanceTestPdf2Json'
  group = 'maintenance'
  description = "Update ALL npm dependencies to the latest release"
  inputs.files depsInputs
  outputs.dir nodeModulesDir
  subprojects {
    outputs.dir "${projectDir}/${nodeModulesDir}"
  }
  args = ['dlx', 'taze', 'major', '--write', '--update', '--recursive', '--include-locked']
}

tasks.register('updateSvgSanitizer', PnpmTask) {
  group = 'maintenance'
  description = 'Update ALL npm dependencies of the svg-sanitizer to the latest release'
  workingDir =  rootProject.layout.projectDirectory.dir('backend/svg-sanitizer/resources')
  args = ['dlx', 'taze', 'major', '--write', '--update', '--include-locked']
}

tasks.register('updatePerformanceTestPdf2Json', PnpmTask) {
  group = 'maintenance'
  description = 'Update ALL npm dependencies of the pdf2json package to the latest release'
  workingDir =  rootProject.layout.projectDirectory.dir('performance-test/src/infrastructure/pdf2json')
  args = ['dlx', 'taze', 'major', '--write', '--update', '--include-locked']
}

tasks.register('outdatedDependencies', PnpmTask) {
  group = 'maintenance'
  description = 'List all outdated npm dependencies'
  args = ['outdated', '--recursive']
}

tasks.register('dedupeDependencies', PnpmTask) {
  group = 'maintenance'
  description = 'Remove older dependencies in the lockfile if a newer version can be used.'
  args = ['dedupe']
}

tasks.register('generateSbom', PnpmTask) {
  dependsOn installDependencies

  def sbomFile = layout.buildDirectory.file("sbom.json").get().asFile
  sbomFile.parentFile.mkdirs()
  def arguments = ['cdxgen', '.', '--type', 'javascript', '--no-recurse', '--output', sbomFile.path]

  if (project.hasProperty("submitToDependencyTrack")) {
    def host = project.property('dependency-track-api-url') as String
    def apiKey = project.property('dependency-track-api-key') as String
    def projectId = project.property('dependency-project-id') as String

    arguments += ['--server-url', host, '--api-key', apiKey, '--project-id', projectId]
  }

  args = arguments
}