# Copyright 2025 cronn GmbH
# SPDX-License-Identifier: AGPL-3.0-only

packages:
  - "e2e"
  - "performance-test"
  - "apps/*"
  - "packages/*"

catalogs:
  next:
    "next": "15.3.3"
    "@next/bundle-analyzer": "15.3.3"
    "eslint-config-next": "15.3.3"

  react:
    "react": "19.1.0"
    "@types/react": "19.1.5"
    "react-dom": "19.1.0"
    "@types/react-dom": "19.1.5"

  joy:
    "@mui/joy": "5.0.0-beta.52"
    "@mui/icons-material": "5.17.1"
    "@mui/material": "npm:@mui/joy@5.0.0-beta.52"
    "@emotion/cache": "11.14.0"
    "@emotion/react": "11.14.0"
    "@emotion/styled": "11.14.0"
    "@fontsource/poppins": "5.2.6"
    "@fontsource/source-code-pro": "5.2.5"

  i18next:
    "i18next": "25.2.1"
    "i18next-resources-to-backend": "1.2.1"
    "react-i18next": "15.5.2"

  fullcalendar:
    "@fullcalendar/core": "6.1.17"
    "@fullcalendar/daygrid": "6.1.17"
    "@fullcalendar/interaction": "6.1.17"
    "@fullcalendar/list": "6.1.17"
    "@fullcalendar/react": "6.1.17"
    "@fullcalendar/timegrid": "6.1.17"

  eslint:
    "eslint": "9.27.0"
    "typescript-eslint": "8.33.0"
    "@eslint/compat": "1.2.9"
    "@eslint/eslintrc": "3.3.1"
    "@eslint/js": "9.27.0"
    "eslint-config-prettier": "10.1.5"
    "eslint-plugin-import": "2.31.0"
    "eslint-plugin-unused-imports": "4.1.4"
    "eslint-plugin-promise": "7.2.1"

  prettier:
    "prettier": "3.5.3"
    "@trivago/prettier-plugin-sort-imports": "5.2.2"

  vite:
    "vite": "6.3.5"

  vitest:
    "vitest": "3.1.4"
    "@vitest/coverage-istanbul": "3.1.4"
    "@vitejs/plugin-react": "4.5.0"
    "vite-tsconfig-paths": "5.1.4"

  common:
    "typescript": "5.8.3"
    "@types/node": "22.15.21"
    "@tanstack/react-query": "5.77.2"
    "@tanstack/eslint-plugin-query": "5.78.0"
    "@tanstack/react-table": "8.21.3"
    "date-fns": "4.1.0"
    "formik": "2.4.6"
    "react-error-boundary": "6.0.0"
    "remeda": "2.22.3"
    "valibot": "1.1.0"
    "use-debounce": "10.0.4"
    "uuid": "11.1.0"
    "drauu": "0.4.3"
    "tsup": "8.5.0"
    "zustand": "5.0.5"
    "@keycloak/keycloak-admin-client": "26.2.4"
    "@cronn/vitest-file-snapshots": "0.7.0"
    "tsx": "4.19.4"

# add new dependencies with exact version instead of semver ranges
saveExact: true
# do not use symlinks because they cause issues on Windows system
# see https://github.com/vercel/next.js/issues/50803
nodeLinker: "hoisted"
ignoredBuiltDependencies:
  - esbuild
  - sharp
  - sqlite3
  - unrs-resolver
