# Copyright 2025 cronn GmbH
# SPDX-License-Identifier: AGPL-3.0-only

packages:
  - "employee-portal"
  - "citizen-portal"
  - "admin-portal"
  - "e2e"
  - "lib-portal"
  - "performance-test"
  - "packages/*"

catalogs:
  next:
    "next": "15.2.4"
    "@next/bundle-analyzer": "15.2.4"
    "eslint-config-next": "15.2.4"

  react:
    "react": "19.0.0"
    "@types/react": "19.0.12"
    "react-dom": "19.0.0"
    "@types/react-dom": "19.0.4"

  joy:
    "@mui/joy": "5.0.0-beta.52"
    "@mui/icons-material": "5.17.1"
    "@mui/material": "npm:@mui/joy@5.0.0-beta.52"
    "@emotion/cache": "11.14.0"
    "@emotion/react": "11.14.0"
    "@emotion/styled": "11.14.0"
    "@fontsource/poppins": "5.2.5"
    "@fontsource/source-code-pro": "5.2.5"

  i18next:
    "i18next": "24.2.3"
    "i18next-resources-to-backend": "1.2.1"
    "react-i18next": "15.4.1"

  fullcalendar:
    "@fullcalendar/core": "6.1.15"
    "@fullcalendar/daygrid": "6.1.15"
    "@fullcalendar/interaction": "6.1.15"
    "@fullcalendar/list": "6.1.15"
    "@fullcalendar/react": "6.1.15"
    "@fullcalendar/timegrid": "6.1.15"

  eslint:
    "eslint": "9.23.0"
    "typescript-eslint": "8.28.0"
    "@eslint/compat": "1.2.7"
    "@eslint/eslintrc": "3.3.1"
    "@eslint/js": "9.23.0"
    "eslint-config-prettier": "10.1.1"
    "eslint-plugin-import": "2.31.0"
    "eslint-plugin-unused-imports": "4.1.4"
    "eslint-plugin-promise": "7.2.1"

  prettier:
    "prettier": "3.5.3"
    "@trivago/prettier-plugin-sort-imports": "5.2.2"

  vitest:
    "vitest": "3.0.9"
    "@vitest/coverage-istanbul": "3.0.9"
    "@vitejs/plugin-react": "4.3.4"
    "vite-tsconfig-paths": "5.1.4"

  common:
    "typescript": "5.8.2"
    "@types/node": "22.13.13"
    "@tanstack/react-query": "5.69.0"
    "@tanstack/eslint-plugin-query": "5.68.0"
    "@tanstack/react-table": "8.21.2"
    "date-fns": "4.1.0"
    "formik": "2.4.6"
    "react-error-boundary": "5.0.0"
    "remeda": "2.21.2"
    "server-only": "0.0.1"
    "valibot": "1.0.0"
    "use-debounce": "10.0.4"
    "uuid": "11.1.0"
    "drauu": "0.4.3"
    "tsup": "8.4.0"
    "zustand": "5.0.3"
    "resolve-tspaths": "0.8.23"
    "@keycloak/keycloak-admin-client": "26.1.4"
    "@cronn/vitest-file-snapshots": "0.3.0"

# add new dependencies with exact version instead of semver ranges
saveExact: true
# do not use symlinks because they cause issues on Windows system
# see https://github.com/vercel/next.js/issues/50803
nodeLinker: "hoisted"
ignoredBuiltDependencies:
  - esbuild
  - sharp
