# Copyright 2025 cronn GmbH
# SPDX-License-Identifier: AGPL-3.0-only

packages:
  - "e2e"
  - "performance-test"
  - "apps/*"
  - "packages/*"

catalogs:
  next:
    "next": "15.4.7"
    "@next/bundle-analyzer": "15.4.7"
    "eslint-config-next": "15.4.7"

  react:
    "react": "19.2.0"
    "@types/react": "19.2.2"
    "react-dom": "19.2.0"
    "@types/react-dom": "19.2.2"

  joy:
    "@mui/joy": "5.0.0-beta.52"
    "@mui/icons-material": "5.17.1"
    "@mui/material": "npm:@mui/joy@5.0.0-beta.52"
    "@emotion/cache": "11.14.0"
    "@emotion/react": "11.14.0"
    "@emotion/styled": "11.14.1"
    "@fontsource/poppins": "5.2.7"
    "@fontsource/source-code-pro": "5.2.7"

  i18next:
    "i18next": "25.6.0"
    "i18next-resources-to-backend": "1.2.1"
    "react-i18next": "16.2.1"

  fullcalendar:
    "@fullcalendar/core": "6.1.19"
    "@fullcalendar/daygrid": "6.1.19"
    "@fullcalendar/interaction": "6.1.19"
    "@fullcalendar/list": "6.1.19"
    "@fullcalendar/react": "6.1.19"
    "@fullcalendar/timegrid": "6.1.19"

  eslint:
    "eslint": "9.38.0"
    "typescript-eslint": "8.46.2"
    "@eslint/compat": "1.4.0"
    "@eslint/eslintrc": "3.3.1"
    "@eslint/js": "9.38.0"
    "eslint-config-prettier": "10.1.8"
    "eslint-plugin-import": "2.32.0"
    "eslint-plugin-unused-imports": "4.3.0"
    "eslint-plugin-promise": "7.2.1"

  prettier:
    "prettier": "3.6.2"
    "@trivago/prettier-plugin-sort-imports": "5.2.2"

  vite:
    "vite": "7.1.12"

  vitest:
    "vitest": "4.0.4"
    "@vitest/coverage-istanbul": "4.0.4"
    "@vitejs/plugin-react": "5.1.0"
    "vite-tsconfig-paths": "5.1.4"
    "@cronn/vitest-file-snapshots": "0.15.0"

  playwright:
    "@playwright/test": "1.56.1"
    "@axe-core/playwright": "4.11.0"
    "axe-core": "4.11.0"
    "axe-html-reporter": "2.2.11"
    "@cronn/playwright-file-snapshots": "0.24.1"

  common:
    "typescript": "5.9.3"
    "@types/node": "22.18.13"
    "@tanstack/react-query": "5.90.5"
    "@tanstack/eslint-plugin-query": "5.91.2"
    "@tanstack/react-table": "8.21.3"
    "date-fns": "4.1.0"
    "formik": "2.4.6"
    "react-error-boundary": "6.0.0"
    "remeda": "2.32.0"
    "valibot": "1.1.0"
    "use-debounce": "10.0.6"
    "uuid": "13.0.0"
    "drauu": "0.4.3"
    "tsup": "8.5.0"
    "zustand": "5.0.8"
    "@keycloak/keycloak-admin-client": "26.4.2"

    "tsx": "4.20.6"
    "pdf-parse-new": "1.4.1"

# add new dependencies with exact version instead of semver ranges
saveExact: true
# do not use symlinks because they cause issues on Windows system
# see https://github.com/vercel/next.js/issues/50803
nodeLinker: "hoisted"
minimumReleaseAge: 1440
strictDepBuilds: true
ignoredBuiltDependencies:
  - esbuild
  - sharp
  - "@appthreat/sqlite3"
  - unrs-resolver
