= GA-Lotse
:source-highlighter: rouge

The Einheitliche Software für die hessischen Gesundheitsämter or GA-Lotse (Gesundheitsamt-Lotse) is a software project with the aim to assist the Hessian public health services in their daily business with a modern and unifying software.

== Documentation

Find detailed information in our https://gitlab.opencode.de/ga-lotse/ga-lotse-documentation[documentation].

== Quick start guide

This guide will help you get a test instance of GA-Lotse running locally. Follow the steps below to ensure you have the required software and choose your preferred method to launch the microservices.

=== Prerequisites

Before starting, make sure you have the following software installed:

* Java 21
* Docker

=== Starting the GA-Lotse architecture

For a fast setup, you can use the pre-configured Gradle tasks as specified in chapter link:docs/gradle.adoc#_root_project_tasks[Root project tasks].

NOTE: These tasks will launch all microservices simultaneously and are therefore resource intensive.

To run the Gradle tasks, execute:

----
./gradlew <task-name>
----

Replace `<task-name>` with the appropriate task as detailed in the documentation.

NOTE: To make the startup more sequential and robust, the Gradle property `-Pslow' can be added to the execute statement.

=== Starting Services Separately

If you wish to conserve resources, you can start the services individually. See the instructions available in chapter link:docs/frontend.adoc#_getting_started[Getting started] on starting each microservice separately.

=== Portal Localhost Ports

Once the services are running, the portals will be accessible at the following localhost ports:

* Employee Portal: http://localhost:4000
* Citizen Portal: http://localhost:4001
* Admin Portal: http://localhost:4002
* PDF Converter Portal: http://localhost:3004
* Keycloak: http://localhost:9090
* port mappings for all services see link:backend/README.md[backend readme].

Login information for the test users can be found in the link:backend/README.md[backend readme].

NOTE: For a local setup, the admin portal/service directory are started, but the full functionality of the service mesh is not started, i.e., communication rules in the admin portal have no impact on the actual microservice communication.

== Reporting issues
If you find any issues, please report it in this repository.

We appreciate your help in improving the project!

== Module documentation

- link:backend/README.md[Backend]
- link:./apps/employee-portal/README.adoc[Employee Portal]
- link:./apps/citizen-portal/README.adoc[Citizen Portal]
- link:./apps/admin-portal/README.adoc[Admin Portal]


== Further information

- link:https://docs.gradle.org[Getting started with gradle]
- link:docs/dependency-management.adoc[Dependency Management]
- link:docs/e2e-tests.adoc[E2E Tests]
- link:docs/sharing-code.adoc[Sharing Code]
- link:reverse-proxy/README.md[Reverse Proxy]
- link:docs/content-security-policy-header.adoc[Content Security Policy (CSP) Header]
- link:docs/flaky-tests.adoc[Flaky Tests]
- link:docs/migration.adoc[Migration Guide]
- link:docs/authoring-libraries.adoc[Authoring Libraries]

== Licensing

This repository contains code that is licensed under both the **GNU Affero General Public License v3 (AGPL-3.0)** and the **Apache License 2.0**.

=== General Licensing Rules

- **GNU AGPL v3**: This license applies to all files, unless otherwise specified. For the full license text, please refer to the `LICENSE-AGPL-3.0-only.txt` file.

- **Apache License 2.0**: This license applies to all files located in or below a directory that contains a `README_LICENSE.adoc` declaring the use of the Apache License 2.0. For the complete license text, see the `LICENSE-APACHE-2.0.txt` file.

=== Contribution Guidelines

When contributing to this project, please specify the applicable license according to the rules outlined above. This helps us properly incorporate your code into the project.

== Cooperation

image:docs/assets/ga-ffm_logo.svg[width=120]

Hessisches Ministerium für Familie, Senioren, Sport, Gesundheit und Pflege

image:docs/assets/funded_by_eu.svg[width=300]
