rootProject.name = 'ga-lotse-code'

includeBuild 'backend'

include 'e2e'
include 'performance-test'
include 'k8s'

// include all projects under '/apps' and '/packages' as project
def apps = new File("$rootDir/apps").listFiles()
def packages = new File("$rootDir/packages").listFiles()
def allProjects = apps + packages
allProjects.each {
  def packageName = it.name
  def packagePath = it.path

  if (it.isDirectory() && new File("${packagePath}/package.json").exists()) {
    include packageName
    // explicitly set nested projectDir to prevent creating pseudo-project ':packages'
    project(":${packageName}").projectDir = file(packagePath)
  }
}

