/*
 * Copyright 2026 cronn GmbH
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package de.eshg.schoolentry.util;

/*
Note: All enum constants must have corresponding translations in the frontend.
 */
public enum SchoolEntrySystemProgressEntryType {
  MERGED_DATA_FROM_SCHOOL_LIST,
  MERGED_DATA_FROM_CITIZEN_LIST,
  PROCEDURE_MODIFIED,
  PROCEDURE_TYPE_MODIFIED,
  APPOINTMENT_MODIFIED,
  APPOINTMENT_RESCHEDULED_BY_CITIZEN,
  SCHOOL_MODIFIED,
  LABELS_MODIFIED,
  CHILD_MODIFIED,
  CHILD_SYNCED_WITH_CENTRAL_FILE,
  CUSTODIAN_SYNCED_WITH_CENTRAL_FILE,
  CUSTODIAN_ADDED,
  CUSTODIAN_MODIFIED,
  CUSTODIAN_REMOVED,
  ANAMNESIS_MODIFIED,
  ANAMNESIS_ADDED_BY_CITIZEN,
  HEARING_TEST_MODIFIED,
  EYE_EXAMINATION_MODIFIED,
  SOPESS_EXAMINATION_MODIFIED,
  DEVELOPMENT_SCREENING_MODIFIED,
  VACCINATION_STATUS_MODIFIED,
  MEDICAL_REPORT_GENERATED,
  SCHOOL_INFO_LETTER_GENERATED
}
