// Copyright 2025 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':lib-base-client')
    implementation project(':lib-config')
    implementation project(':lib-appointmentblock')
    implementation project(':business-module-commons')
    implementation project(':business-module-persistence-commons')
    implementation project(':lib-document-generator')
    implementation project(':lib-procedures')
    implementation project(':lib-calendar')

    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':lib-appointmentblock'))

    implementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    testImplementation testFixtures(project(':lib-document-generator'))
}

dockerCompose {
    startedServices = [
        'prostitute-protection',
        'prostitute-protection-db'
    ]
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-prostitute-protection') ?: "unspecified"
}
