# Copyright 2025 cronn GmbH
# SPDX-License-Identifier: Apache-2.0

services:
  eshg-service-base:
    environment:
      - DOCKER_HOSTNAME=${DOCKER_HOSTNAME:-localhost}
      - spring.profiles.active=${ACTIVE_SPRING_PROFILES:-local,test-helper}
      - eshg.keycloak.internal.url=http://keycloak:8080
      - eshg.population.enabled=${POPULATION_ENABLED:-true}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  eshg-postgres-base:
    image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX:-docker.io}/postgres:16.3@sha256:d0f363f8366fbc3f52d172c6e76bc27151c3d643b870e1062b4e8bfe65baf609
    restart: unless-stopped
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h127.0.0.1 -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "local"
