# Copyright 2025 cronn GmbH
# SPDX-License-Identifier: Apache-2.0

services:
  eshg-service-base:
    environment:
      - DOCKER_HOSTNAME=${DOCKER_HOSTNAME:-localhost}
      - spring.profiles.active=${ACTIVE_SPRING_PROFILES:-local,dev-config,test-helper}
      - eshg.keycloak.internal.url=http://keycloak:8080
      - eshg.population.enabled=${POPULATION_ENABLED:-true}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  eshg-postgres-base:
    image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX:-docker.io}/postgres:15.8@sha256:eb3747f5d0a92195ca486d2f15d9a4ee5e9461b0332fe87fbc59069490a5c659
    restart: unless-stopped
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h127.0.0.1 -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "local"
