# This variable needs to be set for the warning
# > 'org.eclipse.swt.${osgi.platform}' does not match a valid id pattern.
# to vanish.
# This happens only because the spring dependency management plugin tries to
# find variables that might be overriden in the current build, but it does not
# influence gradle's dependency resolution. Because of that the correct platform
# DOES NOT matter, and we can just choose one.
systemProp.osgi.platform=win32.win32.x86

# https://docs.gradle.org/current/userguide/build_environment.html
# https://docs.gradle.org/current/userguide/config_gradle.html#sec:configuring_jvm_memory
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=384m