// Copyright 2026 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

import org.gradle.api.initialization.resolve.RepositoriesMode

rootProject.name = 'backend'

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
    repositories {
        mavenCentral()
        maven {
            url = 'https://mvn.topobyte.de'
        }
        maven {
            url = 'https://mvn.slimjars.com'
        }
    }

    versionCatalogs {
        libs {
            version('swagger-core-jakarta', '2.2.38') // see ISSUE-9929
            library('swagger-core-jakarta', 'io.swagger.core.v3','swagger-core-jakarta').versionRef('swagger-core-jakarta')

            version('keycloak-client', '26.0.8')
            version('keycloak-server', '26.5.2')

            library('keycloak-client-admin-client', 'org.keycloak', 'keycloak-admin-client').versionRef('keycloak-client')

            library('keycloak-server-common', 'org.keycloak', 'keycloak-common').versionRef('keycloak-server')
            library('keycloak-server-core', 'org.keycloak', 'keycloak-core').versionRef('keycloak-server')
            library('keycloak-server-server-spi', 'org.keycloak', 'keycloak-server-spi').versionRef('keycloak-server')
            library('keycloak-server-server-spi-private', 'org.keycloak', 'keycloak-server-spi-private').versionRef('keycloak-server')
            library('keycloak-server-services', 'org.keycloak', 'keycloak-services').versionRef('keycloak-server')
            bundle('keycloak-server', [
                'keycloak-server-core',
                'keycloak-server-common',
                'keycloak-server-server-spi',
                'keycloak-server-server-spi-private',
                'keycloak-server-services',
            ])
        }
    }
}

include 'api-commons'
include 'auditlog'
include 'auditlog-api'
include 'auth'
include 'base'
include 'base-api'
include 'business-module-commons'
include 'business-module-persistence-commons'
include 'central-repository'
include 'chat-management'
include 'compliance-test'
include 'dental'
include 'file-commons'
include 'inspection'
include 'keycloak'
include 'keycloak-api'
include 'lib-aggregation'
include 'lib-appointmentblock'
include 'lib-appointmentblock-api'
include 'lib-auditlog'
include 'lib-base-client'
include 'lib-calendar'
include 'lib-calendar-api'
include 'lib-central-repository-api'
include 'lib-central-repository-client'
include 'lib-commons'
include 'lib-contact'
include 'lib-contact-api'
include 'lib-config'
include 'lib-document-generator'
include 'lib-editor'
include 'lib-editor-api'
include 'lib-four-eyes-principle'
include 'lib-four-eyes-principle-api'
include 'lib-keycloak'
include 'lib-lsd-api'
include 'lib-matrix-client'
include 'lib-mutex'
include 'lib-notification'
include 'lib-notification-api'
include 'lib-procedures'
include 'lib-procedures-api'
include 'lib-relay'
include 'lib-scheduling'
include 'lib-school-entry-client'
include 'lib-security-config'
include 'lib-security-config-urls'
include 'lib-service-directory-admin-api'
include 'lib-service-directory-api'
include 'lib-statistics'
include 'lib-statistics-api'
include 'lib-xdomea'
include 'lib-xlsx-import'
include 'local-service-directory'
include 'logging-commons'
include 'measles-protection'
include 'medical-registry'
include 'official-medical-service'
include 'opendata'
include 'prostitute-protection'
include 'infection-briefing'
include 'relay-server'
include 'rest-client-commons'
include 'rest-oauth-client-commons'
include 'rest-service-commons'
include 'rest-service-errors'
include 'school-entry'
include 'school-entry-api'
include 'service-commons'
include 'service-directory'
include 'spatz'
include 'statistics'
include 'sti-protection'
include 'svg-sanitizer'
include 'synapse'
include 'test-commons'
include 'test-helper-commons'
include 'test-helper-commons-api'
include 'test-helper-commons-spring'
include 'travel-medicine'
include 'util-commons'
