logging.level.org.zalando.logbook=TRACE

# we handle errors from HttpClientConnect and HttpServerOperations separately
logging.level.reactor.netty.http.client.HttpClientConnect=OFF
logging.level.reactor.netty.http.server.HttpServerOperations=OFF

logbook.format.style=http

eshg.spatz.inbound.listening-host=0.0.0.0
eshg.spatz.inbound.handler-port=8443
eshg.spatz.inbound.target-port=8080
eshg.spatz.inbound.force-client-auth=true
eshg.spatz.outbound.listening-host=127.0.0.1
eshg.spatz.outbound.handler-port=80
eshg.spatz.outbound.target-port=8443
eshg.spatz.http.max-connections=500
eshg.spatz.http.channel-eviction-interval=PT5M
eshg.spatz.http.channel-pool-dispose-interval=PT5M
eshg.spatz.http.channel-pool-inactivity=PT15M
eshg.spatz.relay.enabled=true
eshg.spatz.relay.listen-host=127.0.0.1
eshg.spatz.relay.listen-port=8888

eshg.lsd.baseUrl=http://local-service-directory
eshg.lsd-keycloak.client.url=http://keycloak
eshg.lsd-keycloak.actor.user=inspection
eshg.lsd-keycloak.actor.password=pah8diiX5Dahyequaraeph2neigietheH1IeLoi9Pha6equeeWoo2eushai1Oe5b
eshg.lsd-keycloak.client.client-id=eshg-actor
eshg.lsd-keycloak.client.client-secret=youWannaBuyAGreatSnowmanForCheap
eshg.lsd-keycloak.client.realm=eshg-lsd

eshg.spatz.dns.port=53
eshg.spatz.dns.forwardRequestAllowList=
eshg.spatz.self-signed.enabled=false

spring.ssl.bundle.pem.certificatevalidation.truststore.certificate=
server.max-http-request-header-size=20KB

management.server.port=8079
management.endpoint.health.probes.enabled=true
management.endpoint.health.group.readiness.include=dns,outboundServer,inboundServer,certificateDistributed
