#logging.level.org.springframework=DEBUG
eshg.spatz.self-signed.enabled=false

eshg.spatz.ssl.truststore.certificate=../resources/spatz/certs/ca.crt
eshg.spatz.ssl.keystore.certificate=../resources/spatz/certs/relay-server/fullchain.pem
eshg.spatz.ssl.keystore.private-key=../resources/spatz/certs/relay-server/server.key
eshg.spatz.dns.upstream-host=10.5.5.5
eshg.spatz.dns.static-hosts[0]=service-directory
eshg.spatz.dns.static-hosts[1]=local-service-directory
eshg.spatz.dns.static-hosts[2]=keycloak
eshg.spatz.dns.static-hosts[3]=relay-server

eshg.spatz.actor.hostname=foobar

eshg.spatz.relay.url=ws://relay-server:8090/signalling
eshg.spatz.relay.listen-host=127.0.0.1
eshg.spatz.relay.listen-port=8888

