spring.datasource.url=jdbc:postgresql://localhost:5451/prostitute_protection
spring.datasource.username=testuser
spring.datasource.password=testpassword

server.port=8102

spring.security.oauth2.client.registration.module-client.client-id=system-prostitute-protection
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

spring.jpa.hibernate.ddl-auto=validate

# Liquibase
# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

logging.level.org.zalando.logbook=TRACE
