spring.datasource.url=jdbc:postgresql://localhost:5451/prostitute_protection
spring.datasource.username=testuser
spring.datasource.password=testpassword

server.port=8102

spring.security.oauth2.client.registration.module-client.client-id=system-prostitute-protection
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

spring.jpa.hibernate.ddl-auto=validate

de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[PROSTITUTE_PROTECTION_CONSULTATION]=30m

de.eshg.opening-hours.de[0]=Nur nach Terminabsprache.
de.eshg.opening-hours.en[0]=By appointment only.

eshg.population.default-number-of-entities-to-populate.appointment-block-group=0
eshg.population.default-number-of-entities-to-populate.prostitute-protection-procedure=0

# Liquibase
# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

logging.level.org.zalando.logbook=TRACE
