plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':business-module-persistence-commons')
    implementation project(':lib-matrix-client')
    implementation 'commons-codec:commons-codec:1.16.1' // keycloak-admin-client forces version 1.16.1

    implementation "org.zalando:logbook-api:latest.release"
    implementation "org.zalando:logbook-spring:latest.release"
    implementation 'org.springframework.retry:spring-retry'
    runtimeOnly project(':rest-service-commons')

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation project(':lib-base-client')
    testImplementation testFixtures(project(':business-module-persistence-commons'))
}

dockerCompose {
    startedServices = [
        'chat-management',
        'chat-management-db',
    ]
}

// The chat-management:composeUp task should automatically start Synapse as well,
// even though there is no strict dependency
tasks.named("composeUp").configure {
    dependsOn project(":synapse").tasks.named("composeUp")
}

evaluationDependsOn(':synapse')

tasks.named("test") {
    dependsOn project(':synapse').tasks.named("composeUp")
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-chat-management') ?: "unspecified"
}
