plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':lib-base-client')
    implementation project(':business-module-persistence-commons')
    implementation 'commons-codec:commons-codec:1.16.1'

    implementation "org.zalando:logbook-api:latest.release"
    implementation "org.zalando:logbook-spring:latest.release"
    runtimeOnly project(':rest-service-commons')

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation testFixtures(project(':business-module-persistence-commons'))
}

dockerCompose {
    startedServices = [
        'chat-management',
        'chat-management-db',
    ]
}

// chat-management should only start when Synapse is up
tasks.named("composeUp").configure {
    def synapseUp = project(":synapse").tasks.named("composeUp")
    dependsOn synapseUp
    mustRunAfter synapseUp
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-chat-management') ?: "unspecified"
}
