# Copyright 2024 cronn GmbH
# SPDX-License-Identifier: AGPL-3.0-only

openapi: 3.0.1
info:
  description: This is the API for the chat-management module
  title: Chat Management Module API
  version: "0.1"
servers:
- url: http://localhost:8088
paths:
  /feature-toggles:
    get:
      operationId: getFeatureToggles
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/GetFeatureTogglesResponse"
          description: OK
      tags:
      - ChatFeatureToggles
  /test-helper/enabled-new-features/{featureToDisable}:
    delete:
      operationId: disableNewFeature
      parameters:
      - in: path
        name: featureToDisable
        required: true
        schema:
          $ref: "#/components/schemas/ChatFeature"
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/enabled-new-features/{featureToEnable}:
    post:
      operationId: enableNewFeature
      parameters:
      - in: path
        name: featureToEnable
        required: true
        schema:
          $ref: "#/components/schemas/ChatFeature"
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/population:
    post:
      operationId: populateDefaults
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DefaultPopulationResponse"
          description: OK
      tags:
      - TestHelper
  /test-helper/request-interceptor:
    post:
      operationId: interceptNextRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InsertRequestInterceptionTestHelperRequest"
        required: true
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/request-interceptor/barriers:
    post:
      operationId: addBarrier
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestHelperInterceptionRequestFilter"
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AddBarrierTestHelperResponse"
          description: OK
      tags:
      - TestHelper
  /test-helper/request-interceptor/barriers/{barrierId}/await:
    post:
      operationId: awaitBarrier
      parameters:
      - in: path
        name: barrierId
        required: true
        schema:
          type: integer
          format: int64
      - in: query
        name: timeoutInMillis
        required: false
        schema:
          type: integer
          format: int64
          minimum: 0
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/request-interceptor/reset:
    post:
      operationId: resetInterceptionsAndBarriers
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/reset:
    post:
      operationId: reset
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TestHelperClockUpdateResponse"
          description: OK
      tags:
      - TestHelper
  /test-helper/set-clock:
    patch:
      operationId: setClock
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestHelperClockSetRequest"
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TestHelperClockUpdateResponse"
          description: OK
      tags:
      - TestHelper
  /test-helper/wind-clock:
    patch:
      operationId: windClockForward
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestHelperClockWindForwardRequest"
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TestHelperClockUpdateResponse"
          description: OK
      tags:
      - TestHelper
  /user-settings:
    get:
      operationId: getOrCreateDefaultUserSettings
      parameters:
      - in: query
        name: userId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserSettingsResponse"
          description: OK
      tags:
      - UserSettings
    post:
      operationId: createOrUpdateUserSettings
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSettingsRequest"
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserSettingsResponse"
          description: OK
      tags:
      - UserSettings
components:
  schemas:
    AddBarrierTestHelperResponse:
      type: object
      properties:
        barrierId:
          type: integer
          format: int64
          minimum: 1
      required:
      - barrierId
    ChatFeature:
      type: string
      enum:
      - CHAT_BASE
    DefaultPopulationResponse:
      type: object
      properties:
        populations:
          type: array
          items:
            $ref: "#/components/schemas/Population"
    GetFeatureTogglesResponse:
      type: object
      properties:
        disabledOldFeatures:
          type: array
          items:
            $ref: "#/components/schemas/ChatFeature"
          uniqueItems: true
        enabledNewFeatures:
          type: array
          items:
            $ref: "#/components/schemas/ChatFeature"
          uniqueItems: true
      required:
      - disabledOldFeatures
      - enabledNewFeatures
    HttpMethod:
      type: string
      enum:
      - GET
      - HEAD
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
      - TRACE
    InsertRequestInterceptionTestHelperRequest:
      type: object
      properties:
        filter:
          $ref: "#/components/schemas/TestHelperInterceptionRequestFilter"
        type:
          $ref: "#/components/schemas/InterceptionType"
      required:
      - type
    InterceptionType:
      type: string
      enum:
      - BAD_REQUEST
      - UNAUTHORIZED
      - FORBIDDEN
      - NOT_FOUND
      - INTERNAL_SERVER_ERROR
    Population:
      type: object
      properties:
        numberOfPopulatedEntities:
          type: integer
          format: int32
        populatorName:
          type: string
        totalNumberOfEntities:
          type: integer
          format: int64
      required:
      - numberOfPopulatedEntities
      - totalNumberOfEntities
    TestHelperClockSetRequest:
      type: object
      properties:
        newInstant:
          type: string
          format: date-time
      required:
      - newInstant
    TestHelperClockUpdateResponse:
      type: object
      properties:
        instant:
          type: string
          format: date-time
      required:
      - instant
    TestHelperClockWindForwardRequest:
      type: object
      properties:
        days:
          type: integer
          format: int32
          minimum: 0
        hours:
          type: integer
          format: int32
          minimum: 0
        minutes:
          type: integer
          format: int32
          minimum: 0
        months:
          type: integer
          format: int32
          minimum: 0
        seconds:
          type: integer
          format: int32
          minimum: 0
        weeks:
          type: integer
          format: int32
          minimum: 0
      required:
      - days
      - hours
      - minutes
      - months
      - seconds
      - weeks
    TestHelperInterceptionRequestFilter:
      type: object
      properties:
        httpMethodFilter:
          $ref: "#/components/schemas/HttpMethod"
        queryPatternFilter:
          type: string
        urlPatternFilter:
          type: string
    UserSettingsRequest:
      type: object
      properties:
        accountDeactivated:
          type: boolean
        chatConsentAsked:
          type: boolean
        chatUsageEnabled:
          type: boolean
        sharePresence:
          type: boolean
        showReadConfirmation:
          type: boolean
        showTypingNotification:
          type: boolean
        userId:
          type: string
      required:
      - userId
    UserSettingsResponse:
      type: object
      properties:
        accountDeactivated:
          type: boolean
        chatConsentAsked:
          type: boolean
        chatUsageEnabled:
          type: boolean
        sharePresence:
          type: boolean
        showReadConfirmation:
          type: boolean
        showTypingNotification:
          type: boolean
        userId:
          type: string
      required:
      - userId
