// Copyright 2026 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':lib-base-client')
    implementation project(':business-module-commons')
    implementation project(':business-module-persistence-commons')
    implementation project(':lib-procedures')
    implementation project(':lib-appointmentblock')
    implementation project(':rest-oauth-client-commons')

    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':base-api'))

    implementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'
    runtimeOnly 'org.postgresql:postgresql'

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'
}

dockerCompose {
    startedServices = [
        'infection-briefing',
        'infection-briefing-db'
    ]
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-infection-briefing') ?: "unspecified"
}
