plugins {
    id "eshg.java-lib"
}

dependencies {
    implementation project(':business-module-persistence-commons')

    testImplementation project(':test-commons')
    testImplementation testFixtures(project(':business-module-persistence-commons'))

    testRuntimeOnly 'org.postgresql:postgresql'
}

