plugins {
    id "eshg.java-lib"
}

dependencies {
    api 'net.javacrumbs.shedlock:shedlock-spring:latest.release'

    implementation project(':lib-commons')
    implementation project(':test-helper-commons')

    implementation 'jakarta.persistence:jakarta.persistence-api'
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'net.javacrumbs.shedlock:shedlock-provider-jdbc-template:latest.release'
}
