# Common
spring.application.name=eshg-backend-inspection
server.port=8081
# Logging
logging.level.org.zalando.logbook=TRACE
spring.jackson.serialization.indent_output=true
# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5434/inspection
spring.datasource.username=inspection
spring.datasource.password=inspection

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

# AuditLog client credentials
spring.security.oauth2.client.registration.module-client.client-id=system-inspection
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

# Default values for object types
de.eshg.inspection.object-types.routineInterval=730
de.eshg.inspection.object-types.complaintInterval=365
de.eshg.inspection.object-types.standardDuration=3
de.eshg.inspection.object-types.standardBufferTime=120
de.eshg.inspection.object-types.defaultObjectTypes=\
  Ambulante medizinische Einrichtung,\
  Ambulante operative Einrichtung,\
  Krankenhaus,\
  Sterilgutaufbereitung,\
  Kritischer Bereich in einem Krankenhaus,\
  Kosmetische Einrichtung,\
  Soziale Einrichtung,\
  Wasserversorgung

# start WebSearchJob every night at 01:00am
eshg.inspection.scheduling.job.websearch.cron=0 0 1 * * *

# maximum number of rows for xlsx import
de.eshg.inspection.import.max-number-of-import-rows=1000

# hash algorithm for checksums for inspection results and signatures
de.eshg.inspection.hash-algorithm=BLAKE2B_512

# test data population
eshg.population.default-number-of-entities-to-populate.text_block=20
eshg.population.default-number-of-entities-to-populate.checklist_definition=5
eshg.population.default-number-of-entities-to-populate.inspection=7

# Base URL for nominatim requests, which is used for fetching geo information
de.eshg.inspection.geo.nominatim.baseUrl=https://nominatim.openstreetmap.org/search?

de.eshg.inspection.checklist.max.image.sidelength=1920
de.eshg.inspection.signature.max.image.sidelength=1920

de.eshg.opening-hours.enabled=false

de.eshg.inspection.facility-file-number-method=INSPECTION_FRANKFURT
