plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':business-module-commons')
    implementation project(':business-module-persistence-commons')
    implementation project(':lib-appointmentblock')
    implementation project(':lib-calendar')
    implementation project(':lib-base-client')
    implementation project(':lib-procedures')
    implementation project(':lib-config')
    implementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'

    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':lib-auditlog'))
    testImplementation testFixtures(project(':lib-appointmentblock'))

    runtimeOnly 'org.postgresql:postgresql'
}

dockerCompose {
    startedServices = [
        'meds-abroad',
        'meds-abroad-db'
    ]
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-meds-abroad') ?: "unspecified"
}
