// Copyright 2025 cronn GmbH
// SPDX-License-Identifier: AGPL-3.0-only

plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':lib-base-client')
    implementation project(':lib-school-entry-client')
    implementation project(':lib-procedures')
    implementation project(':lib-appointmentblock')
    implementation project(':lib-calendar')
    implementation project(':lib-document-generator')
    implementation project(':lib-config')
    implementation project(':business-module-persistence-commons')
    implementation project(':file-commons')
    implementation project(":lib-statistics")
    implementation project(':rest-oauth-client-commons')

    implementation 'org.apache.poi:poi:latest.release'
    implementation 'org.apache.poi:poi-ooxml:latest.release'
    // explicitly tell gradle to use the latest release of commons-compress (currently 1.28.0),
    // because otherwise gradle chooses the version from poi-ooxml`s dependencies (currently 1.27.1)
    // which is not compatible with the current version of tika 3.2.2 (e.g. https://issues.apache.org/jira/browse/TIKA-4469 )
    implementation 'org.apache.commons:commons-compress:latest.release'
    implementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':lib-document-generator'))
    testImplementation testFixtures(project(':lib-procedures'))
    testImplementation testFixtures(project(':lib-auditlog'))
    testImplementation testFixtures(project(':lib-appointmentblock'))
    testImplementation testFixtures(project(':lib-statistics'))
}

dockerCompose {
    startedServices = [
        'measles-protection',
        'measles-protection-db'
    ]
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-measles-protection') ?: "unspecified"
}

evaluationDependsOn(':school-entry')

tasks.named("test") {
    dependsOn(project(":school-entry").tasks.named("composeUp"))
}
