# Copyright 2025 SCOOP Software GmbH, cronn GmbH
# SPDX-License-Identifier: AGPL-3.0-only

image:
  registry: "k3d-ga-lotse-registry:5050"
  repository: "ga-lotse"
  pullPolicy: Always
  tag: "latest"

thirdPartyImages:
  kubectl:
    name: rancher/kubectl
    tag: "1.33.5@sha256:6f157ad0ff43d31320ab7bf4015271a97466f13c49f03c5108b57b47a312d2c2"
    registry: "docker.io"
    pullPolicy: IfNotPresent
  nginx:
    name: nginx
    tag: "1.29.0@sha256:776b2e787034135a7614429eee7f07e7421cfe37718b1e89de3b41366ea2335d"
    registry: "docker.io"
    pullPolicy: IfNotPresent
  redis:
    name: redis
    tag: "8.4.0-alpine3.22@sha256:6cbef353e480a8a6e7f10ec545f13d7d3fa85a212cdcc5ffaf5a1c818b9d3798"
    registry: "docker.io"
    pullPolicy: IfNotPresent
  postgres:
    name: postgres
    tag: "15.12@sha256:8f6fbd24a12304d2adc332a2162ee9ff9d6044045a0b07f94d6e53e73125e11c"
    registry: "docker.io"
    pullPolicy: IfNotPresent
  maildev:
    name: maildev/maildev
    tag: "2.2.1@sha256:180ef51f65eefebb0e7122d8308813c1fd7bff164bc440ce5a3c2feee167a810"
    registry: "docker.io"
    pullPolicy: IfNotPresent

volumes:
  customStorageClass: false

backup:
  enabled: false

dns:
  upstream: 10.43.0.10

ingress:
  type: "traefik"

monitoring:
  httpChecks:
    enabled: false
  serviceMonitor:
    enabled: false

# Attention: The namespace / orgUnit / domains are forced to a
# frankfurt like setup independently of the actual production config
domains:
  clusterLocalSuffix: .frankfurt.svc.cluster.local
  centralservices:
    servicedirectory: service-directory.central.svc.cluster.local
    relayserver: relay-server.central.svc.cluster.local
    centralrepository: centralrepository.central.svc.cluster.local
    pdfaconverterportal: pcp.central.svc.cluster.local
  hosts:
    lsd: lsd.frankfurt.svc.cluster.local
    employeeportal: ep.frankfurt.svc.cluster.local
    citizenportal: cp.frankfurt.svc.cluster.local
    maildev: mail.frankfurt.svc.cluster.local
    keycloak: keycloak.frankfurt.svc.cluster.local
    keycloakInternal: keycloak.frankfurt.svc.cluster.local
  clusterIssuer: local-ca
  internalClusterIssuer: local-ca

keycloak:
  database:
    selfmanaged: true
    k8sDeployment: true

maildev:
  enabled: true

employeeportalauth:
  cache:
    selfmanaged: true

citizenportalauth:
  cache:
    selfmanaged: true

synapse:
  database:
    selfmanaged: true
    k8sDeployment: true

auditlog:
  database:
    selfmanaged: true
    k8sDeployment: true

businessmoduleDefaults:
  database:
    selfmanaged: true
    k8sDeployment: true

businessmodules:
  base:
    smtp:
      ssl: false
    setupAdmin:
      username: dummy_setup_admin
      email: dummy_setup_admin@maildev.lotse

development:
  injectSelfSignedCA: true

initContainerSecurityContext:
  seLinuxOptions:
    type: "container_init_t"

podSecurityContext:
  seLinuxOptions:
    type: "container_t"
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
