spring.datasource.url=jdbc:postgresql://localhost:5439/measles_protection
spring.datasource.username=testuser
spring.datasource.password=testpassword
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

# The port should match the one specified in the configuration annotated with @OpenAPIDefinition.
server.port=8086

logging.level.org.zalando.logbook=TRACE

spring.security.oauth2.client.registration.module-client.client-id=system-measles-protection
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[PROOF_SUBMISSION]=10m

eshg.population.default-number-of-entities-to-populate.measles-protection-procedure=10
eshg.population.default-number-of-entities-to-populate.appointment-block-group=0

de.eshg.opening-hours.enabled=false
