de.eshg.department-info.use-department-info-from-base-module=false
de.eshg.department-info.privacy-notice=classpath:templates/documents/privacy_notice.pdf
de.eshg.department-info.name=Testing Amt
de.eshg.department-info.abbreviation=TA
de.eshg.department-info.street=Testerstraﬂe
de.eshg.department-info.houseNumber=123
de.eshg.department-info.postalCode=12345
de.eshg.department-info.city=Test Stadt
de.eshg.department-info.country=DE
de.eshg.department-info.phoneNumber=+49 123 12345678
de.eshg.department-info.homepage=www.test-amt-test.xyz
de.eshg.department-info.email=mail@test-amt-test.xyz
de.eshg.department-info.latitude=51.0647
de.eshg.department-info.longitude=12.0128
