de.eshg.measles-protection.privacy-notice-location=classpath:templates/documents/privacy_notice.pdf
de.eshg.measles-protection.privacy-policy-location=classpath:templates/documents/privacy_policy.pdf
