plugins {
    id "eshg.java-lib"
    id "java-test-fixtures"
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.hibernate.orm:hibernate-envers'
    api 'com.fasterxml.jackson.datatype:jackson-datatype-hibernate6'

    api project(':business-module-commons')

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    implementation 'org.liquibase:liquibase-core'
    implementation 'de.cronn:reflection-util:latest.release'
    implementation 'commons-io:commons-io:latest.release'

    runtimeOnly 'de.cronn:liquibase-postgres-enum-extension:latest.release'

    testFixturesApi testFixtures(project(':business-module-commons'))
    testFixturesImplementation project(':test-commons')
    testFixturesImplementation project(':rest-service-commons')
    testFixturesImplementation 'org.springframework.boot:spring-boot-test'
    testFixturesImplementation 'de.cronn:postgres-snapshot-util:latest.release'
    testFixturesApi 'de.cronn:liquibase-changelog-generator-postgresql:latest.release'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add("-AaddSuppressWarningsAnnotation=true")
}
