# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5438/travelmedicine
spring.datasource.username=testuser
spring.datasource.password=testpassword
spring.jpa.hibernate.ddl-auto=validate

# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

server.port=8085

logging.level.org.zalando.logbook=TRACE

spring.security.oauth2.client.registration.module-client.client-id=system-travel-medicine
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[CONSULTATION]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[VACCINATION]=15m

de.eshg.lib.appointmentblock.createAppointmentBlockForCurrentUser=false

eshg.population.default-number-of-entities-to-populate.appointment-block-group=0

eshg.citizen-portal.reverse-proxy.url=http://localhost:4001

de.eshg.travel-medicine.notification.fromAddress=info.reisemedizin@stadt-frankfurt.de
de.eshg.travel-medicine.notification.greeting=Ihr Impfberatungsteam der Stadt Frankfurt

de.eshg.department-info.privacy-notice=classpath:pdf_templates/privacy_notice.pdf

de.eshg.opening-hours.de[0]=Sprechzeiten nur nach Terminvereinbarung:
de.eshg.opening-hours.de[1]=Mo bis Do | 08:00 bis 12:00 Uhr
de.eshg.opening-hours.de[2]=Telefonische Terminvereinbarung:
de.eshg.opening-hours.de[3]=Mo bis Mi | 14:00 bis 15:00 Uhr\nFr | 08:00 bis 10:00 Uhr

de.eshg.opening-hours.en[0]=Consultation hours only with appointment:
de.eshg.opening-hours.en[1]=Mon to Thu | 08:00 a.m. to 12:00 p.m.
de.eshg.opening-hours.en[2]=Make an appointment by telephone:
de.eshg.opening-hours.en[3]=Mon to Wed | 02:00 p.m. to 03:00 p.m.\nFri | 08:00 a.m. to 10:00 a.m.


# standard notifications (by mail)

de.eshg.travel-medicine.notification.templates.path=notifications/default/de

de.eshg.travel-medicine.notification.template.new_citizen_procedure.subject=Bestätigung Ihrer Terminbuchung
de.eshg.travel-medicine.notification.template.new_citizen_procedure.body=classpath:${de.eshg.travel-medicine.notification.templates.path}/new_citizen_procedure.txt

de.eshg.travel-medicine.notification.template.booking_by_citizen.subject=Bestätigung: Ihr Termin wurde gebucht!
de.eshg.travel-medicine.notification.template.booking_by_citizen.body=classpath:${de.eshg.travel-medicine.notification.templates.path}/booking_by_citizen.txt

de.eshg.travel-medicine.notification.template.booking_by_employee.subject=Buchung: Ihr Termin wurde gebucht!
de.eshg.travel-medicine.notification.template.booking_by_employee.body=classpath:${de.eshg.travel-medicine.notification.templates.path}/booking_by_employee.txt

de.eshg.travel-medicine.notification.template.cancellation_by_citizen.subject=Bestätigung: Ihr Termin wurde abgesagt!
de.eshg.travel-medicine.notification.template.cancellation_by_citizen.body=classpath:${de.eshg.travel-medicine.notification.templates.path}/cancellation_by_citizen.txt

de.eshg.travel-medicine.notification.template.cancellation_by_employee.subject=Terminabsage: Ihr Termin wurde abgesagt!
de.eshg.travel-medicine.notification.template.cancellation_by_employee.body=classpath:${de.eshg.travel-medicine.notification.templates.path}/cancellation_by_employee.txt

de.eshg.travel-medicine.notification.template.rebooking_by_citizen.subject=Bestätigung: Ihr Termin wurde umgebucht!
de.eshg.travel-medicine.notification.template.rebooking_by_citizen.body=classpath:${de.eshg.travel-medicine.notification.templates.path}/rebooking_by_citizen.txt

de.eshg.travel-medicine.notification.template.rebooking_by_employee.subject=Umbuchung: Ihr Termin wurde umgebucht!
de.eshg.travel-medicine.notification.template.rebooking_by_employee.body=classpath:${de.eshg.travel-medicine.notification.templates.path}/rebooking_by_employee.txt

de.eshg.travel-medicine.notification.template.new_information_statement.subject=Neuer Aufklärungsbogen: Es steht ein neuer Aufklärungsbogen bereit!
de.eshg.travel-medicine.notification.template.new_information_statement.body=classpath:${de.eshg.travel-medicine.notification.templates.path}/new_information_statement.txt

de.eshg.travel-medicine.notification.template.new_follow_up_appointment.subject=Neuer Folgetermin wurde eingestellt!
de.eshg.travel-medicine.notification.template.new_follow_up_appointment.body=classpath:${de.eshg.travel-medicine.notification.templates.path}/new_follow_up_appointment.txt
