de.eshg.travel-medicine.notification.fromAddress=info.reisemedizin@stadt-frankfurt.de
de.eshg.travel-medicine.notification.greeting=Ihr Impfberatungsteam der Stadt Frankfurt

de.eshg.department-info.use-department-info-from-base-module=false
de.eshg.department-info.privacy-notice=classpath:pdf_templates/privacy_notice.pdf
de.eshg.department-info.name=Travel Medicine Department
de.eshg.department-info.abbreviation=TMD
de.eshg.department-info.street=Wanderluststraﬂe
de.eshg.department-info.houseNumber=202
de.eshg.department-info.postalCode=12345
de.eshg.department-info.city=Wandern Stadt
de.eshg.department-info.country=DE
de.eshg.department-info.phoneNumber=+49 123 12345678
de.eshg.department-info.homepage=www.travel-medicine.de
de.eshg.department-info.email=travel@medicine.de
de.eshg.department-info.latitude=51.0647
de.eshg.department-info.longitude=12.0128

de.eshg.opening-hours.de[0]=Sprechzeiten nur nach Terminvereinbarung:
de.eshg.opening-hours.de[1]=Mo bis Do 08:00 bis 12:00 Uhr
de.eshg.opening-hours.de[2]=Telefonische Terminvereinbarung:
de.eshg.opening-hours.de[3]=Mo bis Mi 14:00 bis 15:00 Uhr\nFr 08:00 bis 10:00 Uhr

de.eshg.opening-hours.en[0]=Consultation hours only with appointment:
de.eshg.opening-hours.en[1]=Mon to Thu 08:00 a.m. to 12:00 p.m.
de.eshg.opening-hours.en[2]=Make an appointment by telephone:
de.eshg.opening-hours.en[3]=Mon to Wed 02:00 p.m. to 03:00 p.m.\nFri 08:00 a.m. to 10:00 a.m.
