de.eshg.travel-medicine.notification.fromAddress=untersuchungstermine-ga@odenwaldkreis.de
de.eshg.travel-medicine.notification.greeting=Ihr Gesundheitsamt des Odenwaldkreises

de.eshg.opening-hours.de[0]=Mo - Do 08:00 - 12:00 Uhr sowie Mo, Di und Do 13:00 - 16:00 Uhr
de.eshg.opening-hours.de[1]=Nur nach Terminabsprache.
de.eshg.opening-hours.de[2]=Fr 08:00 - 13:00 Uhr
de.eshg.opening-hours.de[3]=Nur nach Terminabsprache.

de.eshg.opening-hours.en[0]=Mon - Thu 08:00 AM - 12:00 PM and Mon, Tue, Thu 1:00 PM - 4:00 PM
de.eshg.opening-hours.en[1]=By appointment only.
de.eshg.opening-hours.en[2]=Fri 08:00 AM - 1:00 PM
de.eshg.opening-hours.en[3]=By appointment only.

de.eshg.department-info.use-department-info-from-base-module=false
de.eshg.department-info.street=Albert-Schweitzer-Str.
de.eshg.department-info.houseNumber=8
de.eshg.department-info.postalCode=64711
de.eshg.department-info.city=Erbach

de.eshg.department-info.privacy-notice=classpath:pdf_templates/privacy_notice_odenwaldkreis.pdf
