de.eshg.travel-medicine.notification.fromAddress=info.reisemedizin@stadt-frankfurt.de
de.eshg.travel-medicine.notification.greeting=Ihr Impfberatungsteam der Stadt Frankfurt

de.eshg.department-info.use-privacy-documents-from-base-module=false
de.eshg.department-info.privacy-notice=classpath:pdf_templates/privacy_notice.pdf

de.eshg.opening-hours.de[0]=Sprechzeiten nur nach Terminvereinbarung:
de.eshg.opening-hours.de[1]=Mo bis Do 08:00 bis 12:00 Uhr
de.eshg.opening-hours.de[2]=Telefonische Terminvereinbarung:
de.eshg.opening-hours.de[3]=Mo bis Mi 14:00 bis 15:00 Uhr\nFr 08:00 bis 10:00 Uhr

de.eshg.opening-hours.en[0]=Consultation hours only with appointment:
de.eshg.opening-hours.en[1]=Mon to Thu 08:00 a.m. to 12:00 p.m.
de.eshg.opening-hours.en[2]=Make an appointment by telephone:
de.eshg.opening-hours.en[3]=Mon to Wed 02:00 p.m. to 03:00 p.m.\nFri 08:00 a.m. to 10:00 a.m.
