# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5438/travelmedicine
spring.datasource.username=testuser
spring.datasource.password=testpassword
spring.jpa.hibernate.ddl-auto=validate

# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

server.port=8085

logging.level.org.zalando.logbook=TRACE

spring.security.oauth2.client.registration.module-client.client-id=system-travel-medicine
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[CONSULTATION]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[VACCINATION]=15m

de.eshg.lib.appointmentblock.createAppointmentBlockForCurrentUser=false

eshg.citizen-portal.reverse-proxy.url=http://localhost:4001

de.eshg.travel-medicine.notification.fromAddress=info.reisemedizin@stadt-frankfurt.de
de.eshg.travel-medicine.notification.greeting=Ihr Impfberatungsteam der Stadt Frankfurt

# can be set individually to overwrite base department infos
# de.eshg.travel-medicine.department-info.name=
# de.eshg.travel-medicine.department-info.abbreviation=
# de.eshg.travel-medicine.department-info.street=
# de.eshg.travel-medicine.department-info.houseNumber=
# de.eshg.travel-medicine.department-info.postalCode=
# de.eshg.travel-medicine.department-info.city=
# de.eshg.travel-medicine.department-info.country=
# de.eshg.travel-medicine.department-info.phoneNumber=
# de.eshg.travel-medicine.department-info.homepage=
# de.eshg.travel-medicine.department-info.email=
# de.eshg.travel-medicine.department-info.latitude=
# de.eshg.travel-medicine.department-info.longitude=
