# **************************************************************************************** #
#    Make sure any health-department specific configuration is present in the database     #
#                    See de.eshg.config.EshgConfigurationService                           #
#                                                                                          #
#                      !!! These properties are only defaults !!!                          #
#  !!! Changes and new properties will not be migrated to already populated databases !!!  #
#             !!! All changes need database migrations via liquibase !!!                   #
# **************************************************************************************** #

de.eshg.travel-medicine.notification.fromAddress=info.reisemedizin@stadt-frankfurt.de
de.eshg.travel-medicine.notification.greeting=Ihr Impfberatungsteam der Stadt Frankfurt

de.eshg.department-info.use-privacy-documents-from-base-module=false
de.eshg.department-info.privacy-notice=classpath:pdf_templates/privacy_notice.pdf

# can be set individually to overwrite base department infos
# de.eshg.travel-medicine.department-info.name=
# de.eshg.travel-medicine.department-info.abbreviation=
# de.eshg.travel-medicine.department-info.street=
# de.eshg.travel-medicine.department-info.houseNumber=
# de.eshg.travel-medicine.department-info.postalCode=
# de.eshg.travel-medicine.department-info.city=
# de.eshg.travel-medicine.department-info.country=
# de.eshg.travel-medicine.department-info.phoneNumber=
# de.eshg.travel-medicine.department-info.homepage=
# de.eshg.travel-medicine.department-info.email=
# de.eshg.travel-medicine.department-info.latitude=
# de.eshg.travel-medicine.department-info.longitude=

de.eshg.opening-hours.de[0]=Sprechzeiten nur nach Terminvereinbarung:
de.eshg.opening-hours.de[1]=Mo bis Do | 08:00 bis 12:00 Uhr
de.eshg.opening-hours.de[2]=Telefonische Terminvereinbarung:
de.eshg.opening-hours.de[3]=Mo bis Mi | 14:00 bis 15:00 Uhr\nFr | 08:00 bis 10:00 Uhr

de.eshg.opening-hours.en[0]=Consultation hours only with appointment:
de.eshg.opening-hours.en[1]=Mon to Thu | 08:00 a.m. to 12:00 p.m.
de.eshg.opening-hours.en[2]=Make an appointment by telephone:
de.eshg.opening-hours.en[3]=Mon to Wed | 02:00 p.m. to 03:00 p.m.\nFri | 08:00 a.m. to 10:00 a.m.

de.eshg.travel-medicine.notification.templates.path=notifications/ga_frankfurt/de

de.eshg.travel-medicine.notification.template.new_citizen_procedure.subject=Bestätigung Ihrer Terminbuchung
de.eshg.travel-medicine.notification.template.booking_by_citizen.subject=Bestätigung: Ihr Termin wurde gebucht!
de.eshg.travel-medicine.notification.template.booking_by_employee.subject=Buchung: Ihr Termin wurde gebucht!
de.eshg.travel-medicine.notification.template.cancellation_by_citizen.subject=Bestätigung: Ihr Termin wurde abgesagt!
de.eshg.travel-medicine.notification.template.cancellation_by_employee.subject=Terminabsage: Ihr Termin wurde abgesagt!
de.eshg.travel-medicine.notification.template.rebooking_by_citizen.subject=Bestätigung: Ihr Termin wurde umgebucht!
de.eshg.travel-medicine.notification.template.rebooking_by_employee.subject=Umbuchung: Ihr Termin wurde umgebucht!
de.eshg.travel-medicine.notification.template.new_information_statement.subject=Neuer Aufklärungsbogen: Es steht ein neuer Aufklärungsbogen bereit!
de.eshg.travel-medicine.notification.template.new_follow_up_appointment.subject=Neuer Folgetermin wurde eingestellt!

# **************************************************************************************** #
#    Make sure any health-department specific configuration is present in the database     #
#                    See de.eshg.config.EshgConfigurationService                           #
#                                                                                          #
#                      !!! These properties are only defaults !!!                          #
#  !!! Changes and new properties will not be migrated to already populated databases !!!  #
#             !!! All changes need database migrations via liquibase !!!                   #
# **************************************************************************************** #
