// Copyright 2025 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

plugins {
    id "eshg.java-lib"
    id "java-test-fixtures"
}

dependencies {
    api project(":lib-contact-api")
    implementation project(":base-api")

    implementation 'org.springframework.boot:spring-boot-autoconfigure'

    implementation project(':business-module-commons')

    testFixturesImplementation project(':test-commons')
    testFixturesImplementation 'org.assertj:assertj-core'
    testFixturesImplementation 'org.springframework.boot:spring-boot-test'
}
