# Setting these defaults in application.properties prevents overwrite from
# @TestProperty imported files due to Spring precedence of properties!
eshg.keycloak.bund-id-test-realm.enabled=false
eshg.keycloak.citizen-realm.bund-id-idp.enabled=false
