eshg.keycloak.bund-id-test-realm.enabled=false
eshg.keycloak.citizen-realm.bund-id-idp.enabled=true
eshg.keycloak.citizen-realm.bund-id-idp.entity-id=https://int.id.bund.de/idp
eshg.keycloak.citizen-realm.bund-id-idp.single-sign-on-service-url=https://int.id.bund.de/idp/profile/SAML2/POST/SSO
