/**
 * Copyright 2025 cronn GmbH
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { ChipProps } from "@mui/joy";

import { EnumMap, buildEnumOptions } from "@eshg/lib-portal";
import {
  ApiConsultation,
  ApiConsultationType,
  ApiCountryCode,
  ApiDocumentType,
  ApiPersonLanguage,
  ApiProcedureProperty,
  ApiProcedureStatus,
  ApiTaskType,
} from "@eshg/prostitute-protection-api";

export const systemProgressEntryTypeTitles: Record<string, string> = {
  PROCEDURE_DETAILS_MODIFIED: "Vorgangsdaten bearbeitet",
  PERSON_DETAILS_MODIFIED: "Personendaten bearbeitet",
  CONSULTATION_MODIFIED: "Beratung bearbeitet",
  REGISTRATION_CONSULTATION_CERTIFICATE_GENERATED:
    "Beratungszertifikat_Anmeldung erstellt",
  CONSULTATION_CERTIFICATE_GENERATED: "Beratungszertifikat erstellt",
} as const;

export const taskTypes = [ApiTaskType.ProstituteProtection];

export const keyDocumentTypes: Record<string, string> = {
  CONSULTATION_CERTIFICATE: "Beratungszertifikat",
  REGISTRATION_CONSULTATION_CERTIFICATE: "Beratungszertifikat_Anmeldung",
};

export const PERSON_FIELD_NAME = {
  firstName: "Vorname",
  lastName: "Nachname",
  dateOfBirth: "Geburtsdatum",
  alias: "Alias",
  otherLanguages: "Weitere Sprachen",
  gender: "Geschlecht",
  countryOfBirth: "Geburtsland",
  nationality: "Staatsangehörigkeit",
  documentType: "Ausweisdokument",
  hasSufficientGermanLanguageSkills: "Ausreichende Deutschkenntnisse",
} as const;

export const ADDITIONAL_DATA_FIELD_NAME = {
  appointment: "Termin",
  consultationType: "Beratungstyp",
  procedureStatus: "Status",
  consultant: "Bearbeiter:in",
  createdBy: "Angelegt von",
} as const;

export const APPOINTMENT_FORM_LABELS = {
  appointmentDate: "Datum und Zeit",
  appointmentDuration: "Termindauer in Minuten",
} as const;

export const CONSULTATION_FIELD_NAME: Record<
  keyof Omit<ApiConsultation, "version">,
  string
> = {
  legalAdvices: "Rechtsberatung",
  healthAndSocialInsurance: "Kranken- und Sozialversicherung",
  consultingServices: "Beratungsangebote",
  emergencyHelp: "Hilfe in Notsituationen",
  taxLiability: "Steuerpflicht",
  clearing: "Beratungsbedarf / Clearing",
  informationMaterial: "Infomaterial",
  predicament: "Notlage / Zwangslage",
  diseasePrevention: "Krankheitsverhütung",
  birthControl: "Empfängnisregelung",
  pregnancy: "Schwangerschaft",
  alcoholAndDrugUsage: "Alkohol- / Drogengebrauch",
  referral: "Weitervermittlung § 19",
  supervisedConsultation: "Beratung unter Aufsicht",
  remark: "Anmerkungen",
  interpreterConsulted: "Dolmetscher hinzugezogen",
  interpreterFirstName: PERSON_FIELD_NAME.firstName,
  interpreterLastName: PERSON_FIELD_NAME.lastName,
  languageOfConsultation: "Sprache der Beratung",
} as const;

export const DOCUMENT_TYPE_VALUES: Record<ApiDocumentType, string> = {
  [ApiDocumentType.IdentificationCard]: "Personalausweis",
  [ApiDocumentType.Passport]: "Reisepass",
  [ApiDocumentType.ResidencePermit]: "Aufenthaltstitel",
  [ApiDocumentType.TolerancePermit]: "Duldung",
  [ApiDocumentType.Other]: "Sonstige",
};

export const CONSULTATION_TYPE_VALUES: Record<ApiConsultationType, string> = {
  [ApiConsultationType.Initial]: "Erstberatung",
  [ApiConsultationType.FollowUp]: "Folgeberatung",
} as const;

export const LANGUAGE_VALUE: Record<ApiPersonLanguage, string> = {
  [ApiPersonLanguage.Bulgarian]: "Bulgarisch",
  [ApiPersonLanguage.Chinese]: "Chinesisch",
  [ApiPersonLanguage.German]: "Deutsch",
  [ApiPersonLanguage.English]: "Englisch",
  [ApiPersonLanguage.French]: "Französisch",
  [ApiPersonLanguage.Greek]: "Griechisch",
  [ApiPersonLanguage.Italian]: "Italienisch",
  [ApiPersonLanguage.Polish]: "Polnisch",
  [ApiPersonLanguage.Portuguese]: "Portugiesisch",
  [ApiPersonLanguage.Romanian]: "Rumänisch",
  [ApiPersonLanguage.Russian]: "Russisch",
  [ApiPersonLanguage.SerboCroatian]: "Serbokroatisch",
  [ApiPersonLanguage.Slovakian]: "Slowakisch",
  [ApiPersonLanguage.Spanish]: "Spanisch",
  [ApiPersonLanguage.Thai]: "Thai",
  [ApiPersonLanguage.Czech]: "Tschechisch",
  [ApiPersonLanguage.Turkish]: "Türkisch",
  [ApiPersonLanguage.Ukrainian]: "Ukrainisch",
  [ApiPersonLanguage.Hungarian]: "Ungarisch",
  [ApiPersonLanguage.Unknown]: "Unbekannt",
} as const;

export const LANGUAGE_OPTIONS = buildEnumOptions(LANGUAGE_VALUE, false);

export const NATIONALITY_VALUES: Record<ApiCountryCode, string> = {
  [ApiCountryCode.Ad]: "andorranisch",
  [ApiCountryCode.Ae]: "emiratisch",
  [ApiCountryCode.Af]: "afghanisch",
  [ApiCountryCode.Ag]: "antiguanisch",
  [ApiCountryCode.Ai]: "anguillanisch",
  [ApiCountryCode.Al]: "albanisch",
  [ApiCountryCode.Am]: "armenisch",
  [ApiCountryCode.Ao]: "angolanisch",
  [ApiCountryCode.Aq]: "antarktisch",
  [ApiCountryCode.Ar]: "argentinisch",
  [ApiCountryCode.As]: "amerikanisch-samoanisch",
  [ApiCountryCode.At]: "österreichisch",
  [ApiCountryCode.Au]: "australisch",
  [ApiCountryCode.Aw]: "arubanisch",
  [ApiCountryCode.Ax]: "åländisch",
  [ApiCountryCode.Az]: "aserbaidschanisch",
  [ApiCountryCode.Ba]: "bosnisch-herzegowinisch",
  [ApiCountryCode.Bb]: "barbadisch",
  [ApiCountryCode.Bd]: "bangladeschisch",
  [ApiCountryCode.Be]: "belgisch",
  [ApiCountryCode.Bf]: "burkinisch",
  [ApiCountryCode.Bg]: "bulgarisch",
  [ApiCountryCode.Bh]: "bahrainisch",
  [ApiCountryCode.Bi]: "burundisch",
  [ApiCountryCode.Bj]: "beninisch",
  [ApiCountryCode.Bl]: "St. Barthélemy",
  [ApiCountryCode.Bm]: "bermudisch",
  [ApiCountryCode.Bn]: "bruneiisch",
  [ApiCountryCode.Bo]: "bolivianisch",
  [ApiCountryCode.Bq]: "karibisch-niederländisch",
  [ApiCountryCode.Br]: "brasilianisch",
  [ApiCountryCode.Bs]: "bahamaisch",
  [ApiCountryCode.Bt]: "bhutanisch",
  [ApiCountryCode.Bv]: "Bouvetinsel",
  [ApiCountryCode.Bw]: "botswanisch",
  [ApiCountryCode.By]: "belarussisch",
  [ApiCountryCode.Bz]: "belizisch",
  [ApiCountryCode.Ca]: "kanadisch",
  [ApiCountryCode.Cc]: "Kokosinseln",
  [ApiCountryCode.Cd]: "kongolesisch (Demokratische Republik Kongo)",
  [ApiCountryCode.Cf]: "zentralafrikanisch",
  [ApiCountryCode.Cg]: "kongolesisch",
  [ApiCountryCode.Ch]: "schweizerisch",
  [ApiCountryCode.Ci]: "ivorisch",
  [ApiCountryCode.Ck]: "Cookinseln",
  [ApiCountryCode.Cl]: "chilenisch",
  [ApiCountryCode.Cm]: "kamerunisch",
  [ApiCountryCode.Cn]: "chinesisch",
  [ApiCountryCode.Co]: "kolumbianisch",
  [ApiCountryCode.Cr]: "costa-ricanisch",
  [ApiCountryCode.Cu]: "kubanisch",
  [ApiCountryCode.Cv]: "kap-verdisch",
  [ApiCountryCode.Cw]: "curaçaoisch",
  [ApiCountryCode.Cx]: "Weihnachtsinsel",
  [ApiCountryCode.Cy]: "zyprisch",
  [ApiCountryCode.Cz]: "tschechisch",
  [ApiCountryCode.De]: "deutsch",
  [ApiCountryCode.Dj]: "dschibutisch",
  [ApiCountryCode.Dk]: "dänisch",
  [ApiCountryCode.Dm]: "dominicanisch",
  [ApiCountryCode.Do]: "dominikanisch",
  [ApiCountryCode.Dz]: "algerisch",
  [ApiCountryCode.Ec]: "ecuadorianisch",
  [ApiCountryCode.Ee]: "estnisch",
  [ApiCountryCode.Eg]: "ägyptisch",
  [ApiCountryCode.Eh]: "westsaharisch",
  [ApiCountryCode.Er]: "eritreisch",
  [ApiCountryCode.Es]: "spanisch",
  [ApiCountryCode.Et]: "äthiopisch",
  [ApiCountryCode.Fi]: "finnisch",
  [ApiCountryCode.Fj]: "fidschianisch",
  [ApiCountryCode.Fk]: "Falklandinseln",
  [ApiCountryCode.Fm]: "mikronesisch",
  [ApiCountryCode.Fo]: "färöisch",
  [ApiCountryCode.Fr]: "französisch",
  [ApiCountryCode.Ga]: "gabunisch",
  [ApiCountryCode.Gb]: "britisch",
  [ApiCountryCode.Gd]: "grenadisch",
  [ApiCountryCode.Ge]: "georgisch",
  [ApiCountryCode.Gf]: "französisch-guayanisch",
  [ApiCountryCode.Gg]: "Guernsey",
  [ApiCountryCode.Gh]: "ghanaisch",
  [ApiCountryCode.Gi]: "gibraltarisch",
  [ApiCountryCode.Gl]: "grönländisch",
  [ApiCountryCode.Gm]: "gambisch",
  [ApiCountryCode.Gn]: "guineisch",
  [ApiCountryCode.Gp]: "guadeloupisch",
  [ApiCountryCode.Gq]: "äquatorialguineisch",
  [ApiCountryCode.Gr]: "griechisch",
  [ApiCountryCode.Gs]: "südgeorgisch",
  [ApiCountryCode.Gt]: "guatemaltekisch",
  [ApiCountryCode.Gu]: "guamisch",
  [ApiCountryCode.Gw]: "guinea-bissauisch",
  [ApiCountryCode.Gy]: "guyanisch",
  [ApiCountryCode.Hk]: "Hongkong",
  [ApiCountryCode.Hm]: "Heard- und McDonald-Inseln",
  [ApiCountryCode.Hn]: "honduranisch",
  [ApiCountryCode.Hr]: "kroatisch",
  [ApiCountryCode.Ht]: "haitianisch",
  [ApiCountryCode.Hu]: "ungarisch",
  [ApiCountryCode.Id]: "indonesisch",
  [ApiCountryCode.Ie]: "irisch",
  [ApiCountryCode.Il]: "israelisch",
  [ApiCountryCode.Im]: "manx",
  [ApiCountryCode.In]: "indisch",
  [ApiCountryCode.Io]: "britisch-indischer Ozean",
  [ApiCountryCode.Iq]: "irakisch",
  [ApiCountryCode.Ir]: "iranisch",
  [ApiCountryCode.Is]: "isländisch",
  [ApiCountryCode.It]: "italienisch",
  [ApiCountryCode.Je]: "Jersey",
  [ApiCountryCode.Jm]: "jamaikanisch",
  [ApiCountryCode.Jo]: "jordanisch",
  [ApiCountryCode.Jp]: "japanisch",
  [ApiCountryCode.Ke]: "kenianisch",
  [ApiCountryCode.Kg]: "kirgisisch",
  [ApiCountryCode.Kh]: "kambodschanisch",
  [ApiCountryCode.Ki]: "kiribatisch",
  [ApiCountryCode.Km]: "komorisch",
  [ApiCountryCode.Kn]: "St. Kitts und Nevis",
  [ApiCountryCode.Kp]: "nordkoreanisch",
  [ApiCountryCode.Kr]: "südkoreanisch",
  [ApiCountryCode.Kw]: "kuwaitisch",
  [ApiCountryCode.Ky]: "caymanisch",
  [ApiCountryCode.Kz]: "kasachisch",
  [ApiCountryCode.La]: "laotisch",
  [ApiCountryCode.Lb]: "libanesisch",
  [ApiCountryCode.Lc]: "St. Lucianisch",
  [ApiCountryCode.Li]: "liechtensteinisch",
  [ApiCountryCode.Lk]: "sri-lankisch",
  [ApiCountryCode.Lr]: "liberianisch",
  [ApiCountryCode.Ls]: "lesothisch",
  [ApiCountryCode.Lt]: "litauisch",
  [ApiCountryCode.Lu]: "luxemburgisch",
  [ApiCountryCode.Lv]: "lettisch",
  [ApiCountryCode.Ly]: "libysch",
  [ApiCountryCode.Ma]: "marokkanisch",
  [ApiCountryCode.Mc]: "monegassisch",
  [ApiCountryCode.Md]: "moldauisch",
  [ApiCountryCode.Me]: "montenegrinisch",
  [ApiCountryCode.Mf]: "St. Martin",
  [ApiCountryCode.Mg]: "madagassisch",
  [ApiCountryCode.Mh]: "marshallisch",
  [ApiCountryCode.Mk]: "nordmazedonisch",
  [ApiCountryCode.Ml]: "malisch",
  [ApiCountryCode.Mm]: "myanmarisch",
  [ApiCountryCode.Mn]: "mongolisch",
  [ApiCountryCode.Mo]: "macauisch",
  [ApiCountryCode.Mp]: "Nördliche Marianen",
  [ApiCountryCode.Mq]: "martiniquisch",
  [ApiCountryCode.Mr]: "mauretanisch",
  [ApiCountryCode.Ms]: "montserratisch",
  [ApiCountryCode.Mt]: "maltesisch",
  [ApiCountryCode.Mu]: "mauritisch",
  [ApiCountryCode.Mv]: "maledivisch",
  [ApiCountryCode.Mw]: "malawisch",
  [ApiCountryCode.Mx]: "mexikanisch",
  [ApiCountryCode.My]: "malaysisch",
  [ApiCountryCode.Mz]: "mosambikanisch",
  [ApiCountryCode.Na]: "namibisch",
  [ApiCountryCode.Nc]: "neukaledonisch",
  [ApiCountryCode.Ne]: "nigrisch",
  [ApiCountryCode.Nf]: "Norfolkinsel",
  [ApiCountryCode.Ng]: "nigerianisch",
  [ApiCountryCode.Ni]: "nicaraguanisch",
  [ApiCountryCode.Nl]: "niederländisch",
  [ApiCountryCode.No]: "norwegisch",
  [ApiCountryCode.Np]: "nepalesisch",
  [ApiCountryCode.Nr]: "nauruisch",
  [ApiCountryCode.Nu]: "niueanisch",
  [ApiCountryCode.Nz]: "neuseeländisch",
  [ApiCountryCode.Om]: "omanisch",
  [ApiCountryCode.Pa]: "panamaisch",
  [ApiCountryCode.Pe]: "peruanisch",
  [ApiCountryCode.Pf]: "französisch-polynesisch",
  [ApiCountryCode.Pg]: "papua-neuguineisch",
  [ApiCountryCode.Ph]: "philippinisch",
  [ApiCountryCode.Pk]: "pakistanisch",
  [ApiCountryCode.Pl]: "polnisch",
  [ApiCountryCode.Pm]: "St. Pierre und Miquelon",
  [ApiCountryCode.Pn]: "Pitcairninseln",
  [ApiCountryCode.Pr]: "puerto-ricanisch",
  [ApiCountryCode.Ps]: "palästinensisch",
  [ApiCountryCode.Pt]: "portugiesisch",
  [ApiCountryCode.Pw]: "palauisch",
  [ApiCountryCode.Py]: "paraguayisch",
  [ApiCountryCode.Qa]: "katarisch",
  [ApiCountryCode.Re]: "Réunion",
  [ApiCountryCode.Ro]: "rumänisch",
  [ApiCountryCode.Rs]: "serbisch",
  [ApiCountryCode.Ru]: "russisch",
  [ApiCountryCode.Rw]: "ruandisch",
  [ApiCountryCode.Sa]: "saudisch",
  [ApiCountryCode.Sb]: "salomonisch",
  [ApiCountryCode.Sc]: "seychellisch",
  [ApiCountryCode.Sd]: "sudanesisch",
  [ApiCountryCode.Se]: "schwedisch",
  [ApiCountryCode.Sg]: "singapurisch",
  [ApiCountryCode.Sh]: "St. Helena",
  [ApiCountryCode.Si]: "slowenisch",
  [ApiCountryCode.Sj]: "Svalbard und Jan Mayen",
  [ApiCountryCode.Sk]: "slowakisch",
  [ApiCountryCode.Sl]: "sierra-leonisch",
  [ApiCountryCode.Sm]: "san-marinesisch",
  [ApiCountryCode.Sn]: "senegalesisch",
  [ApiCountryCode.So]: "somalisch",
  [ApiCountryCode.Sr]: "surinamisch",
  [ApiCountryCode.Ss]: "südsudanesisch",
  [ApiCountryCode.St]: "São-toméisch",
  [ApiCountryCode.Sv]: "salvadorianisch",
  [ApiCountryCode.Sx]: "Sint Maarten",
  [ApiCountryCode.Sy]: "syrisch",
  [ApiCountryCode.Sz]: "eswatinisch",
  [ApiCountryCode.Tc]: "Turks- und Caicosinseln",
  [ApiCountryCode.Td]: "tschadisch",
  [ApiCountryCode.Tf]: "Französische Süd- und Antarktisgebiete",
  [ApiCountryCode.Tg]: "togoisch",
  [ApiCountryCode.Th]: "thailändisch",
  [ApiCountryCode.Tj]: "tadschikisch",
  [ApiCountryCode.Tk]: "tokelauisch",
  [ApiCountryCode.Tl]: "timoresisch",
  [ApiCountryCode.Tm]: "turkmenisch",
  [ApiCountryCode.Tn]: "tunesisch",
  [ApiCountryCode.To]: "tongaisch",
  [ApiCountryCode.Tr]: "türkisch",
  [ApiCountryCode.Tt]: "trinidadisch",
  [ApiCountryCode.Tv]: "tuvaluisch",
  [ApiCountryCode.Tw]: "taiwanisch",
  [ApiCountryCode.Tz]: "tansanisch",
  [ApiCountryCode.Ua]: "ukrainisch",
  [ApiCountryCode.Ug]: "ugandisch",
  [ApiCountryCode.Um]: "Amerikanische Überseeinseln",
  [ApiCountryCode.Us]: "amerikanisch",
  [ApiCountryCode.Uy]: "uruguayisch",
  [ApiCountryCode.Uz]: "usbekisch",
  [ApiCountryCode.Va]: "vatikanisch",
  [ApiCountryCode.Vc]: "St. Vincent und die Grenadinen",
  [ApiCountryCode.Ve]: "venezolanisch",
  [ApiCountryCode.Vg]: "Britische Jungferninseln",
  [ApiCountryCode.Vi]: "Amerikanische Jungferninseln",
  [ApiCountryCode.Vn]: "vietnamesisch",
  [ApiCountryCode.Vu]: "vanuatuisch",
  [ApiCountryCode.Wf]: "Wallis und Futuna",
  [ApiCountryCode.Ws]: "samoanisch",
  [ApiCountryCode.Ye]: "jemenitisch",
  [ApiCountryCode.Yt]: "Mayotte",
  [ApiCountryCode.Za]: "südafrikanisch",
  [ApiCountryCode.Zm]: "sambisch",
  [ApiCountryCode.Zw]: "simbabwisch",
  [ApiCountryCode.Xk]: "kosovarisch",
  [ApiCountryCode.Unknown]: "unbekannt",
  [ApiCountryCode.Stateless]: "staatenlos",
};

export const NATIONALITY_OPTIONS = buildEnumOptions(NATIONALITY_VALUES, false);

export const CertificateType = {
  fullName: "FULL_NAME",
  alias: "ALIAS",
} as const;

export type CertificateType =
  (typeof CertificateType)[keyof typeof CertificateType];

export const CERTIFICATE_TYPE_VALUES = {
  [CertificateType.fullName]: "Klarname",
  [CertificateType.alias]: "Alias",
} as const;

export const PROCEDURE_STATUS_COLORS: EnumMap<
  ApiProcedureStatus,
  ChipProps["color"]
> = {
  [ApiProcedureStatus.Aborted]: "warning",
  [ApiProcedureStatus.Closed]: "success",
  [ApiProcedureStatus.Draft]: "neutral",
  [ApiProcedureStatus.InProgress]: "primary",
  [ApiProcedureStatus.Open]: "neutral",
};

export const PROCEDURE_STATUS_VALUES: EnumMap<ApiProcedureStatus> = {
  [ApiProcedureStatus.Aborted]: "Abgebrochen",
  [ApiProcedureStatus.Closed]: "Geschlossen",
  [ApiProcedureStatus.Draft]: "Entwurf",
  [ApiProcedureStatus.InProgress]: "In Arbeit",
  [ApiProcedureStatus.Open]: "Offen",
};

export const REQUIRED_PROCEDURE_AREAS: EnumMap<string> = {
  DETAILS: "Vorgangsdaten",
  CONSULTATION_PARAGRAPH_7: "Beratung nach $7",
  CONSULTATION_PARAGRAPH_10: "Beratung nach $10",
};

export const REQUIRED_PROCEDURE_PROPERTIES: EnumMap<ApiProcedureProperty> = {
  ALIAS: PERSON_FIELD_NAME.alias,
  FIRST_NAME: PERSON_FIELD_NAME.firstName,
  LAST_NAME: PERSON_FIELD_NAME.lastName,
  DATE_OF_BIRTH: PERSON_FIELD_NAME.dateOfBirth,
  NATIONALITY: PERSON_FIELD_NAME.nationality,
  DOCUMENT_TYPE: PERSON_FIELD_NAME.documentType,
  LEGAL_ADVICES: CONSULTATION_FIELD_NAME.legalAdvices,
  HEALTH_AND_SOCIAL_INSURANCE: CONSULTATION_FIELD_NAME.healthAndSocialInsurance,
  CONSULTING_SERVICES: CONSULTATION_FIELD_NAME.consultingServices,
  EMERGENCY_HELP: CONSULTATION_FIELD_NAME.emergencyHelp,
  TAX_LIABILITY: CONSULTATION_FIELD_NAME.taxLiability,
  DISEASE_PREVENTION: CONSULTATION_FIELD_NAME.diseasePrevention,
  BIRTH_CONTROL: CONSULTATION_FIELD_NAME.birthControl,
  PREGNANCY: CONSULTATION_FIELD_NAME.pregnancy,
  ALCOHOL_AND_DRUG_USAGE: CONSULTATION_FIELD_NAME.alcoholAndDrugUsage,
};

export const OPTIONAL_TAG = "(optional)";
