/*
 * Copyright 2025 cronn GmbH
 * SPDX-License-Identifier: Apache-2.0
 */

package de.eshg.officialmedicalservice.procedure;

public enum OmsProgressEntryType {
  UPDATE_AFFECTED_PERSON,
  SYNC_AFFECTED_PERSON,
  SYNC_FACILITY,
  PHYSICIAN_CHANGED,
  PROCEDURE_STARTED,
  DOCUMENT_DELETED,
  APPOINTMENT_FOR_SELF_BOOKING_ADDED,
  APPOINTMENT_ADDED_WITH_BOOKING,
  APPOINTMENT_BOOKED,
  APPOINTMENT_REBOOKED,
  APPOINTMENT_CANCELED,
  APPOINTMENT_OPTION_WITHDRAWN,
  APPOINTMENT_CLOSED,
  DOCUMENT_MISSING_BY_CITIZEN,
  DOCUMENT_MISSING_BY_EMPLOYEE,
  DOCUMENT_ACCEPTED,
  DOCUMENT_INFORMATION_CHANGED,
  DOCUMENT_STATUS_CHANGE_ACCEPTED,
  FACILITY_ADDED,
  MEDICAL_OPINION_STATUS_CHANGED,
  CONCERN_CHANGED,
}
