/*
 * Copyright 2025 SCOOP Software GmbH, cronn GmbH
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package de.eshg.officialmedicalservice.procedure;

public enum OmsProgressEntryType {
  UPDATE_AFFECTED_PERSON,
  UPDATE_FACILITY,
  SYNC_AFFECTED_PERSON,
  SYNC_FACILITY,
  PROCEDURE_STARTED,
  DOCUMENT_DELETED,
  DOCUMENT_REVIEWED,
  APPOINTMENT_FOR_SELF_BOOKING_ADDED,
  APPOINTMENT_ADDED_WITH_BOOKING,
  APPOINTMENT_BOOKED,
  APPOINTMENT_REBOOKED,
  APPOINTMENT_CANCELED,
  APPOINTMENT_OPTION_WITHDRAWN,
  APPOINTMENT_CLOSED,
  DOCUMENT_MISSING_BY_CITIZEN,
  DOCUMENT_MISSING_BY_EMPLOYEE,
  DOCUMENT_ACCEPTED,
  DOCUMENT_INFORMATION_CHANGED,
  DOCUMENT_STATUS_CHANGE_ACCEPTED,
  FACILITY_ADDED,
  MEDICAL_OPINION_STATUS_CHANGED,
  ADDITIONAL_INFO_CHANGED,
  CONCERN_CHANGED,
  ANAMNESIS_CHANGED_BY_EMPLOYEE,
  ANAMNESIS_CHANGED_BY_CITIZEN
}
