spring.datasource.url=jdbc:postgresql://localhost:5452/infection_briefing
spring.datasource.username=testuser
spring.datasource.password=testpassword

server.port=8103

spring.security.oauth2.client.registration.module-client.client-id=system-infection-briefing
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

spring.jpa.hibernate.ddl-auto=validate

eshg.population.default-number-of-entities-to-populate.appointment-block-group=0
eshg.population.default-number-of-entities-to-populate.infection-briefing-procedure=30

# Liquibase
# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

logging.level.org.zalando.logbook=TRACE

de.eshg.department-info.use-department-info-from-base-module=true

de.eshg.lib.procedure.search-guard.enabled=false

de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[INFECTION_BRIEFING_NEW]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[INFECTION_BRIEFING_REPLACEMENT]=30m
de.eshg.lib.appointmentblock.createAppointmentBlockForCurrentUser=false

de.eshg.opening-hours.enabled=false

de.eshg.infectionbriefing.new-certificate-appointment-confirmation-mail.subject=Terminbestätigung Infektionsschutzbelehrung
de.eshg.infectionbriefing.new-certificate-appointment-confirmation-mail.body=classpath:mail/de/newAppointmentConfirmationMail.txt
