plugins {
  id 'next-app'
  id 'reverse-proxy'
  id 'next-loading-files'
  id 'next-error-files'
}

next {
  port = '3001'
  sonarProjectKey = project.findProperty("sonar-project-key-citizen-portal")
}

nextLoadingFiles {
  includeDirs = ['[lang]/(privatpersonen)', '[lang]/unternehmen', '[lang]/(static)']
}

nextErrorFiles {
  includeDirs = ['[lang]/(privatpersonen)', '[lang]/unternehmen', '[lang]/(static)']
}

reverseProxy {
  serviceName = "citizen-portal-reverse-proxy"
  mainConfigFile = "citizen-portal.conf"
}
