plugins {
  id 'source-checks'
  id 'vitest'
}

prettier {
  include = ['**/*.ts', '**/*.tsx', '**/*.cjs', '**/*.json']
}

eslint {
  include = ['src/**/*.ts', 'src/**/*.tsx']
}

typescript {
  // ⚠⚠⚠ Note ⚠⚠⚠: Please adjust the tsconfig.json when changing includes/excludes here
  include = ['src/**/*.ts', 'src/**/*.tsx']
}

tasks.named('prepareEnvironment').configure {
  dependsOn project(":employee-portal-api").tasks.named('assemble')
}

tasks.named('lint').configure {
  inputs.files "${rootDir}/config/eslint.next.cjs"
}

tasks.named('lintFix').configure {
  inputs.files "${rootDir}/config/eslint.next.cjs"
}

tasks.named('test').configure {
  inputs.file "${rootDir}/config/tsconfig.lib.json"
}

tasks.register('assemble') {
  dependsOn 'compile'
}

tasks.register('build') {
  dependsOn 'check'
  dependsOn 'assemble'
}
