de.eshg.lib.procedure.mailreminder.schedule=-
de.eshg.lib.procedure.housekeeping.inbox.schedule=-
de.eshg.lib.procedure.housekeeping.archiving.schedule=-
de.eshg.lib.procedure.housekeeping.cemetery.schedule=-

de.eshg.lib.procedure.housekeeping.archiving.details[INSPECTION].years=1
de.eshg.lib.procedure.housekeeping.archiving.details[INSPECTION].relevance=RELEVANT
de.eshg.lib.procedure.housekeeping.archiving.details[REGULAR_EXAMINATION].years=5
de.eshg.lib.procedure.housekeeping.archiving.details[REGULAR_EXAMINATION].relevance=IRRELEVANT
