de.eshg.envers.auditing.enabled=true

# Workaround until fixed in Hibernate:
# Cache can cause ConcurrentModificationException https://hibernate.atlassian.net/browse/HHH-19429
# ToDo 5894 see if this can be removed
spring.jpa.properties.hibernate.query.plan_cache_enabled=false
