#
# Needed to overwrite the DNS server of a docker container to localhost (a.k.a to the sidecar)
# overwriting the DNS server via docker-compose syntax does not work
# see https://github.com/docker/compose/issues/8441
#
nameserver 127.0.0.1
