// Copyright 2026 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

project.buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        components.all { ComponentMetadataDetails details ->
            if (details.id.version =~ /(?i).+([-.])(CANDIDATE|RC|BETA|ALPHA|M\d+).*/) {
                details.status = 'milestone'
            }
        }
    }

    dependencyLocking {
        lockAllConfigurations()
    }
}
