plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':auditlog-api')
    implementation project(':rest-oauth-client-commons')
    implementation project(':business-module-commons')
    implementation project(':business-module-persistence-commons')
    implementation project(':lib-base-client')
    implementation project(':lib-auditlog')
    implementation project(':file-commons')

    implementation 'commons-io:commons-io:latest.release'
    implementation 'org.bouncycastle:bcprov-jdk18on:latest.release'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation project(':test-commons')
    testImplementation testFixtures(project(':business-module-commons'))
    testImplementation testFixtures(project(':business-module-persistence-commons'))

    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.springdoc:springdoc-openapi-starter-common:2.6.0' // Pinned to workaround https://github.com/springdoc/springdoc-openapi/issues/2776
}

dockerCompose {
    startedServices = ['auditlog', 'auditlog-db']
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-auditlog') ?: "unspecified"
}

