# Copyright 2024 cronn GmbH
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.1
info:
  description: This is the API for the auditlog service
  title: Auditlog Service API
  version: "0.1"
servers:
- url: http://localhost:8094
paths:
  /auditlog:
    get:
      operationId: readAuditLogFile
      parameters:
      - in: header
        name: decryption-key
        required: true
        schema:
          type: string
      - in: query
        name: source
        required: true
        schema:
          $ref: "#/components/schemas/AuditLogSource"
      - in: query
        name: date
        required: true
        schema:
          type: string
          format: date
      responses:
        "200":
          content:
            '*/*':
              schema:
                type: string
          description: OK
      summary: Decrypt and read an auditlog file for a service of a certain date.
      tags:
      - AuditLog
    post:
      description: POST operation to add an auditlog file for a service.
      operationId: addAuditlogFile
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                addAuditLogFileRequest:
                  $ref: "#/components/schemas/AddAuditLogFileRequest"
                file:
                  type: string
                  format: binary
              required:
              - addAuditLogFileRequest
              - file
      responses:
        "200":
          description: OK
      summary: Add an auditlog file for a service
      tags:
      - AuditLog
  /auditlog/accessible:
    get:
      operationId: getAccessibleAuditLogs
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/GetAccessibleAuditLogsResponse"
          description: OK
      summary: List all audit log files accessible to the current user.
      tags:
      - AuditLog
  /auditlog/available:
    get:
      operationId: getAvailableLogs
      parameters:
      - description: |
          Filter logic:
              - If `source` is submitted, only audit logs from the specified sources are returned.
              - If not submitted, no filtering takes place
        in: query
        name: source
        required: false
        schema:
          type: array
          items:
            $ref: "#/components/schemas/AuditLogSource"
          uniqueItems: true
      - description: |
          Can only be used in combination with endDate.

          Filter logic:
          - If `startDate` and `endDate` are submitted, only audit logs within the specified period are returned.
          - If not submitted, no filtering takes place
        in: query
        name: startDate
        required: false
        schema:
          type: string
          format: date
      - description: |
          Can only be used in combination with startDate.

          Filter logic:
          - If `startDate` and `endDate` are submitted, only audit logs within the specified period are returned.
          - If not submitted, no filtering takes place
        in: query
        name: endDate
        required: false
        schema:
          type: string
          format: date
      - description: Limit of returned procedures
        in: query
        name: pageSize
        required: false
        schema:
          type: integer
          format: int32
          default: 25
          maximum: 200
          minimum: 1
      - description: Offset used for pagination
        in: query
        name: pageNumber
        required: false
        schema:
          type: integer
          format: int32
          default: 0
          maximum: 2000
          minimum: 0
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/GetAvailableAuditLogsResponse"
          description: OK
      summary: Get a list of all available logs.
      tags:
      - AuditLog
  /auditlog/grant-access:
    get:
      operationId: getAuditLogGrantedAccesses
      parameters:
      - in: query
        name: source
        required: true
        schema:
          $ref: "#/components/schemas/AuditLogSource"
      - in: query
        name: date
        required: true
        schema:
          type: string
          format: date
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/GetAuditLogGrantedAccessesResponse"
          description: OK
      summary: List all granted accesses of audit log.
      tags:
      - AuditLog
    post:
      operationId: grantAuditLogAccess
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GrantAuditLogAccessRequest"
        required: true
      responses:
        "200":
          description: OK
      summary: Grant access to an auditlog file for a service of a certain date to
        a certain user.
      tags:
      - AuditLog
  /auditlog/grantees-candidates:
    get:
      operationId: getAuditLogGranteesCandidates
      parameters:
      - in: query
        name: source
        required: true
        schema:
          $ref: "#/components/schemas/AuditLogSource"
      - in: query
        name: date
        required: true
        schema:
          type: string
          format: date
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/GetUsersResponse"
          description: OK
      summary: List all user candidates for audit log grant access.
      tags:
      - AuditLog
  /auditlog/key:
    get:
      operationId: getEncryptedSymmetricKey
      parameters:
      - in: query
        name: source
        required: true
        schema:
          $ref: "#/components/schemas/AuditLogSource"
      - in: query
        name: date
        required: true
        schema:
          type: string
          format: date
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/GetEncryptedSymmetricKeyResponse"
          description: OK
      summary: Get user specific asymmetrically encrypted symmetric key.
      tags:
      - AuditLog
  /feature-toggles:
    get:
      operationId: getFeatureToggles
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/GetAuditLogFeatureTogglesResponse"
          description: OK
      tags:
      - AuditLogFeatureToggles
  /test-helper/archiving-job:
    post:
      operationId: runArchivingJob
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/audit-log-storage:
    delete:
      operationId: clearAuditLogStorageDirectory
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/enabled-new-features/{featureToEnable}:
    post:
      operationId: enableNewFeature
      parameters:
      - in: path
        name: featureToEnable
        required: true
        schema:
          $ref: "#/components/schemas/AuditLogFeature"
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/population:
    post:
      operationId: populateDefaults
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DefaultPopulationResponse"
          description: OK
      tags:
      - TestHelper
  /test-helper/request-interceptor:
    post:
      operationId: interceptNextRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InsertRequestInterceptionTestHelperRequest"
        required: true
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/request-interceptor/barriers:
    post:
      operationId: addBarrier
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestHelperInterceptionRequestFilter"
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AddBarrierTestHelperResponse"
          description: OK
      tags:
      - TestHelper
  /test-helper/request-interceptor/barriers/{barrierId}/await:
    post:
      operationId: awaitBarrier
      parameters:
      - in: path
        name: barrierId
        required: true
        schema:
          type: integer
          format: int64
      - in: query
        name: timeoutInMillis
        required: false
        schema:
          type: integer
          format: int64
          minimum: 0
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/request-interceptor/reset:
    post:
      operationId: resetInterceptionsAndBarriers
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/reset:
    post:
      operationId: reset
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TestHelperClockUpdateResponse"
          description: OK
      tags:
      - TestHelper
  /test-helper/set-clock:
    patch:
      operationId: setClock
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestHelperClockSetRequest"
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TestHelperClockUpdateResponse"
          description: OK
      tags:
      - TestHelper
  /test-helper/wind-clock:
    patch:
      operationId: windClockForward
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestHelperClockWindForwardRequest"
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TestHelperClockUpdateResponse"
          description: OK
      tags:
      - TestHelper
components:
  schemas:
    AccessibleAuditLog:
      type: object
      properties:
        auditLog:
          $ref: "#/components/schemas/AuditLog"
        expiresAt:
          type: string
          format: date-time
      required:
      - auditLog
      - expiresAt
    AddAuditLogFileRequest:
      type: object
      properties:
        date:
          type: string
          format: date
        source:
          $ref: "#/components/schemas/AuditLogSource"
      required:
      - date
      - source
    AddBarrierTestHelperResponse:
      type: object
      properties:
        barrierId:
          type: integer
          format: int64
          minimum: 1
      required:
      - barrierId
    AuditLog:
      type: object
      properties:
        date:
          type: string
          format: date
        source:
          $ref: "#/components/schemas/AuditLogSource"
      required:
      - date
      - source
    AuditLogFeature:
      type: string
      enum:
      - AUDIT_LOG_ACCESSIBLE_TABLE
    AuditLogGrantedAccessCount:
      type: object
      properties:
        auditLog:
          $ref: "#/components/schemas/AuditLog"
        validGrantedAccessCount:
          type: integer
          format: int32
          description: Number of users having granted access
      required:
      - auditLog
      - validGrantedAccessCount
    AuditLogSource:
      type: string
      enum:
      - BASE
      - INSPECTION
      - SCHOOL_ENTRY
      - TRAVEL_MEDICINE
      - MEASLES_PROTECTION
      - STI_PROTECTION
      - AUDITLOG
      - STATISTICS
    DefaultPopulationResponse:
      type: object
      properties:
        populations:
          type: array
          items:
            $ref: "#/components/schemas/Population"
    GetAccessibleAuditLogsResponse:
      type: object
      properties:
        accessibleAuditLogs:
          type: array
          items:
            $ref: "#/components/schemas/AccessibleAuditLog"
      required:
      - accessibleAuditLogs
    GetAuditLogFeatureTogglesResponse:
      type: object
      properties:
        disabledOldFeatures:
          type: array
          items:
            $ref: "#/components/schemas/AuditLogFeature"
          uniqueItems: true
        enabledNewFeatures:
          type: array
          items:
            $ref: "#/components/schemas/AuditLogFeature"
          uniqueItems: true
      required:
      - disabledOldFeatures
      - enabledNewFeatures
    GetAuditLogGrantedAccessesResponse:
      type: object
      properties:
        grantedAccesses:
          type: array
          items:
            $ref: "#/components/schemas/GrantedAccess"
        resolvedUsers:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/User"
      required:
      - grantedAccesses
      - resolvedUsers
    GetAvailableAuditLogsResponse:
      type: object
      properties:
        logs:
          type: array
          items:
            $ref: "#/components/schemas/AuditLogGrantedAccessCount"
        totalElements:
          type: integer
          format: int64
          description: Total number of result elements
        totalPages:
          type: integer
          format: int32
          description: Total number of result pages
      required:
      - logs
      - totalElements
      - totalPages
    GetEncryptedSymmetricKeyResponse:
      type: object
      properties:
        encapsulatedKey:
          type: string
          format: byte
        encryptedSymmetricKey:
          type: string
          format: byte
      required:
      - encapsulatedKey
      - encryptedSymmetricKey
    GetUsersResponse:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: "#/components/schemas/User"
      required:
      - users
    GrantAuditLogAccessRequest:
      type: object
      properties:
        date:
          type: string
          format: date
        idsOfGrantedUser:
          type: array
          items:
            type: string
            format: uuid
          maxItems: 2147483647
          minItems: 1
          uniqueItems: true
        source:
          $ref: "#/components/schemas/AuditLogSource"
      required:
      - date
      - idsOfGrantedUser
      - source
    GrantedAccess:
      type: object
      properties:
        expiresAt:
          type: string
          format: date-time
        idOfGrantedUser:
          type: string
          format: uuid
      required:
      - expiresAt
      - idOfGrantedUser
    HttpMethod:
      type: string
      enum:
      - GET
      - HEAD
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
      - TRACE
    InsertRequestInterceptionTestHelperRequest:
      type: object
      properties:
        filter:
          $ref: "#/components/schemas/TestHelperInterceptionRequestFilter"
        type:
          $ref: "#/components/schemas/InterceptionType"
      required:
      - type
    InterceptionType:
      type: string
      enum:
      - BAD_REQUEST
      - UNAUTHORIZED
      - FORBIDDEN
      - NOT_FOUND
      - INTERNAL_SERVER_ERROR
    Population:
      type: object
      properties:
        numberOfPopulatedEntities:
          type: integer
          format: int32
        populatorName:
          type: string
        totalNumberOfEntities:
          type: integer
          format: int64
      required:
      - numberOfPopulatedEntities
      - totalNumberOfEntities
    TestHelperClockSetRequest:
      type: object
      properties:
        newInstant:
          type: string
          format: date-time
      required:
      - newInstant
    TestHelperClockUpdateResponse:
      type: object
      properties:
        instant:
          type: string
          format: date-time
      required:
      - instant
    TestHelperClockWindForwardRequest:
      type: object
      properties:
        days:
          type: integer
          format: int32
          minimum: 0
        hours:
          type: integer
          format: int32
          minimum: 0
        minutes:
          type: integer
          format: int32
          minimum: 0
        months:
          type: integer
          format: int32
          minimum: 0
        seconds:
          type: integer
          format: int32
          minimum: 0
        weeks:
          type: integer
          format: int32
          minimum: 0
      required:
      - days
      - hours
      - minutes
      - months
      - seconds
      - weeks
    TestHelperInterceptionRequestFilter:
      type: object
      properties:
        httpMethodFilter:
          $ref: "#/components/schemas/HttpMethod"
        queryPatternFilter:
          type: string
        urlPatternFilter:
          type: string
    User:
      type: object
      properties:
        email:
          type: string
          description: The email address of a user.
          example: example@mail.de
        enabled:
          type: boolean
          description: "True, if the user can login"
          example: false
        externalChatUsername:
          type: string
          description: The chat username of the gematik TI-Messenger (matrix chat).
          example: '@username:server'
        firstName:
          type: string
          description: The given name(s) of a user.
          example: John
        lastName:
          type: string
          description: The last name of a user.
          example: Doe
        phoneNumber:
          type: string
          description: The phone number of a user.
          example: "+491234567890"
        userId:
          type: string
          format: uuid
          description: The Id of the user.
          example: fe9831d4-dc25-48d8-9bfe-4c0b54bfb2c1
        username:
          type: string
          description: The username which is displayed in the application and can
            be used for the login.
          example: testuser
      required:
      - enabled
      - firstName
      - lastName
      - userId
      - username
