server.port=8096
logging.level.org.zalando.logbook=TRACE
spring.jackson.serialization.indent_output=true

spring.datasource.url=jdbc:postgresql://localhost:5446/opendata
spring.datasource.username=testuser
spring.datasource.password=testpassword

spring.jpa.hibernate.ddl-auto=validate

# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

de.eshg.opendata.author=GA Frankfurt
de.eshg.opendata.terms-of-use=classpath:/terms-of-use.md

spring.security.oauth2.client.registration.module-client.client-id=system-opendata
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token
