server.port=8096
logging.level.org.zalando.logbook=TRACE
spring.jackson.serialization.indent_output=true

spring.datasource.url=jdbc:postgresql://localhost:5446/opendata
spring.datasource.username=testuser
spring.datasource.password=testpassword

spring.jpa.hibernate.ddl-auto=create

# TODO remove once the final document is there configure it in application-health-department-frankfurt.properties and move the property and the test pdf to the test resources folder
de.eshg.opendata.terms-of-use=classpath:/terms-of-use.pdf