# **************************************************************************************** #
#    Make sure any health-department specific configuration is present in the database     #
#                    See de.eshg.config.EshgConfigurationService                           #
#                                                                                          #
#                      !!! These properties are only defaults !!!                          #
#  !!! Changes and new properties will not be migrated to already populated databases !!!  #
#             !!! All changes need database migrations via liquibase !!!                   #
# **************************************************************************************** #

de.eshg.opendata.author=GA Frankfurt

# TODO adjust once the final document is available
de.eshg.opendata.terms-of-use=classpath:/terms-of-use.pdf

# **************************************************************************************** #
#    Make sure any health-department specific configuration is present in the database     #
#                    See de.eshg.config.EshgConfigurationService                           #
#                                                                                          #
#                      !!! These properties are only defaults !!!                          #
#  !!! Changes and new properties will not be migrated to already populated databases !!!  #
#             !!! All changes need database migrations via liquibase !!!                   #
# **************************************************************************************** #