server.port=8096
logging.level.org.zalando.logbook=TRACE
spring.jackson.serialization.indent_output=true

spring.datasource.url=jdbc:postgresql://localhost:5446/opendata
spring.datasource.username=testuser
spring.datasource.password=testpassword

spring.jpa.hibernate.ddl-auto=create
