# Copyright 2024 cronn GmbH
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.1
info:
  description: This is a the generic API for all modules that use the four-eyes principle
  title: The generic four-eyes principle library API
  version: "0.1"
servers:
- url: http://localhost:8080
paths:
  /approval-requests/{approvalRequestId}:
    get:
      operationId: getApprovalRequest
      parameters:
      - in: path
        name: approvalRequestId
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApprovalRequest"
          description: OK
      tags:
      - ApprovalRequest
  /approval-requests/{approvalRequestId}/decision:
    put:
      operationId: decideApprovalRequest
      parameters:
      - in: path
        name: approvalRequestId
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Decision"
        required: true
      responses:
        "200":
          description: OK
      tags:
      - ApprovalRequest
  /test-helper/population:
    post:
      operationId: populateDefaults
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DefaultPopulationResponse"
          description: OK
      tags:
      - TestHelper
  /test-helper/request-interceptor:
    post:
      operationId: interceptNextRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InsertRequestInterceptionTestHelperRequest"
        required: true
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/request-interceptor/barriers:
    post:
      operationId: addBarrier
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestHelperInterceptionRequestFilter"
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AddBarrierTestHelperResponse"
          description: OK
      tags:
      - TestHelper
  /test-helper/request-interceptor/barriers/{barrierId}/await:
    post:
      operationId: awaitBarrier
      parameters:
      - in: path
        name: barrierId
        required: true
        schema:
          type: integer
          format: int64
      - in: query
        name: timeoutInMillis
        required: false
        schema:
          type: integer
          format: int64
          minimum: 0
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/request-interceptor/reset:
    post:
      operationId: resetInterceptionsAndBarriers
      responses:
        "200":
          description: OK
      tags:
      - TestHelper
  /test-helper/reset:
    post:
      operationId: reset
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TestHelperClockUpdateResponse"
          description: OK
      tags:
      - TestHelper
  /test-helper/set-clock:
    patch:
      operationId: setClock
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestHelperClockSetRequest"
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TestHelperClockUpdateResponse"
          description: OK
      tags:
      - TestHelper
  /test-helper/wind-clock:
    patch:
      operationId: windClockForward
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestHelperClockWindForwardRequest"
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TestHelperClockUpdateResponse"
          description: OK
      tags:
      - TestHelper
components:
  schemas:
    AddBarrierTestHelperResponse:
      type: object
      properties:
        barrierId:
          type: integer
          format: int64
          minimum: 1
      required:
      - barrierId
    ApprovalRequest:
      type: object
      properties:
        approvalRequestId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
          format: uuid
        decidedAt:
          type: string
          format: date-time
        decidedBy:
          type: string
          format: uuid
        decision:
          $ref: "#/components/schemas/Decision"
        entity:
          oneOf:
          - $ref: "#/components/schemas/TestEntityDto"
        operation:
          $ref: "#/components/schemas/Operation"
        reason:
          type: string
        status:
          $ref: "#/components/schemas/ApprovalRequestStatus"
      required:
      - approvalRequestId
      - createdAt
      - createdBy
      - operation
      - reason
      - status
    ApprovalRequestEntity:
      type: object
      discriminator:
        propertyName: '@type'
      properties:
        '@type':
          type: string
      required:
      - '@type'
    ApprovalRequestStatus:
      type: string
      enum:
      - OPEN
      - CLOSED
    Decision:
      type: string
      enum:
      - GRANTED
      - DENIED
    DefaultPopulationResponse:
      type: object
      properties:
        populations:
          type: array
          items:
            $ref: "#/components/schemas/Population"
    HttpMethod:
      type: string
      enum:
      - GET
      - HEAD
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
      - TRACE
    InsertRequestInterceptionTestHelperRequest:
      type: object
      properties:
        filter:
          $ref: "#/components/schemas/TestHelperInterceptionRequestFilter"
        type:
          $ref: "#/components/schemas/InterceptionType"
      required:
      - type
    InterceptionType:
      type: string
      enum:
      - BAD_REQUEST
      - UNAUTHORIZED
      - FORBIDDEN
      - NOT_FOUND
      - INTERNAL_SERVER_ERROR
    Operation:
      type: string
      enum:
      - DELETE
    Population:
      type: object
      properties:
        numberOfPopulatedEntities:
          type: integer
          format: int32
        populatorName:
          type: string
        totalNumberOfEntities:
          type: integer
          format: int64
      required:
      - numberOfPopulatedEntities
      - totalNumberOfEntities
    TestEntityDto:
      type: object
      allOf:
      - $ref: "#/components/schemas/ApprovalRequestEntity"
      - type: object
        properties:
          id:
            type: string
            format: uuid
          locked:
            type: boolean
    TestHelperClockSetRequest:
      type: object
      properties:
        newInstant:
          type: string
          format: date-time
      required:
      - newInstant
    TestHelperClockUpdateResponse:
      type: object
      properties:
        instant:
          type: string
          format: date-time
      required:
      - instant
    TestHelperClockWindForwardRequest:
      type: object
      properties:
        days:
          type: integer
          format: int32
          minimum: 0
        hours:
          type: integer
          format: int32
          minimum: 0
        minutes:
          type: integer
          format: int32
          minimum: 0
        months:
          type: integer
          format: int32
          minimum: 0
        seconds:
          type: integer
          format: int32
          minimum: 0
        weeks:
          type: integer
          format: int32
          minimum: 0
      required:
      - days
      - hours
      - minutes
      - months
      - seconds
      - weeks
    TestHelperInterceptionRequestFilter:
      type: object
      properties:
        httpMethodFilter:
          $ref: "#/components/schemas/HttpMethod"
        queryPatternFilter:
          type: string
        urlPatternFilter:
          type: string
