eshg.synapse.internal.url=http://${DOCKER_HOSTNAME:localhost}:8008
eshg.synapse.refresh-clock-skew=PT1M
eshg.synapse.registration-shared-secret=k.@ukx06IL;5RcXHIo=^m4LI7lF*x-BgNegdB367MEyR@oe&~K
eshg.synapse.admin.name=admin
eshg.synapse.admin.password=admin

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5441/chat_management
spring.datasource.username=testuser
spring.datasource.password=testpassword

spring.jpa.hibernate.ddl-auto=validate
# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

# Note: Keep the port in-sync with de.eshg.chat.config.ApiDocsConfig
server.port=8088
# Logging
logging.level.org.zalando.logbook=TRACE
logbook.obfuscate.json-body-fields[0]=password
logbook.obfuscate.json-body-fields[1]=access_token
logbook.obfuscate.json-body-fields[2]=refresh_token
logbook.obfuscate.json-body-fields[3]=token
logbook.obfuscate.json-body-fields[4]=refreshToken
logbook.obfuscate.json-body-fields[5]=accessToken

# Synapse AccessToken is not aware of test-helper clock timeline
eshg.testclock.enabled=false
