# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5441/chat_management
spring.datasource.username=testuser
spring.datasource.password=testpassword

spring.jpa.hibernate.ddl-auto=validate
# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

# Note: Keep the port in-sync with de.eshg.chat.config.ApiDocsConfig
server.port=8088
# Logging
logging.level.org.zalando.logbook=TRACE
logbook.obfuscate.json-body-fields[0]=password
logbook.obfuscate.json-body-fields[1]=access_token
logbook.obfuscate.json-body-fields[2]=refresh_token
