# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5440/statistics
spring.datasource.username=testuser
spring.datasource.password=testpassword
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.batch_size=250

# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

server.port=8087

logging.level.org.zalando.logbook=TRACE

spring.security.oauth2.client.registration.module-client.client-id=system-statistics
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

eshg.statistics.businessmodule.original-data-permissions[0].business-module=SCHOOL_ENTRY
eshg.statistics.businessmodule.original-data-permissions[0].permission=SCHOOL_ENTRY_ADMIN

eshg.statistics.businessmodule.original-data-permissions[1].business-module=INSPECTION
eshg.statistics.businessmodule.original-data-permissions[1].permission=INSPECTION_PROCEDURE_EDIT
