spring.datasource.url=jdbc:postgresql://localhost:5448/dental
spring.datasource.username=testuser
spring.datasource.password=testpassword

# The port should match the one specified in the configuration annotated with @OpenAPIDefinition.
server.port=8098

spring.jpa.hibernate.ddl-auto=validate

# Liquibase
# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

logging.level.org.zalando.logbook=TRACE

eshg.population.default-number-of-entities-to-populate.child=50
