server.port=8094
logging.level.org.zalando.logbook=TRACE
logging.level.de.eshg.auditlog=DEBUG
spring.jackson.serialization.indent_output=true

spring.datasource.url=jdbc:postgresql://localhost:5444/auditlog
spring.datasource.username=testuser
spring.datasource.password=testpassword

# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

spring.jpa.hibernate.ddl-auto=validate
#the auditlog service writes audit logs as well
#it uses it's very own controller directly and does not use tcp communication
de.eshg.auditlog.log-storage-dir=${java.io.tmpdir}/auditlog-storage-dir

# see http://localhost:9090/realms/eshg/.well-known/openid-configuration
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

spring.security.oauth2.client.registration.module-client.client-id=system-auditlog
spring.security.oauth2.client.registration.module-client.client-secret=password
