# Setting these defaults in application.properties prevents overwrite from
# @TestProperty imported files due to Spring precedence of properties!
eshg.keycloak.muk-test-realm.enabled=false
eshg.keycloak.citizen-realm.muk-idp.enabled=false
