eshg.keycloak.muk-test-realm.enabled=false
eshg.keycloak.citizen-realm.muk-idp.enabled=true
eshg.keycloak.citizen-realm.muk-idp.entity-id=https://e4k-portal.een.elster.de
eshg.keycloak.citizen-realm.muk-idp.single-sign-on-service-url=https://e4k-portal.een.elster.de/ekona/sso
eshg.keycloak.citizen-realm.muk-idp.single-logout-service-url=https://e4k-portal.een.elster.de/ekona/slo
