# This is a workaround for a unique constraint column order regression in Hibernate 6.2
# See https://hibernate.atlassian.net/browse/HHH-16943
# and https://hibernate.atlassian.net/browse/HHH-17065
spring.jpa.properties.hibernate.column_ordering_strategy=legacy
