plugins {
    id "eshg.service"
}

dependencies {
    implementation project(':api-commons')
    implementation project(':lib-base-client')
    implementation project(':lib-central-repository-client')
    implementation project(':lib-procedures')
    implementation project(':lib-calendar')
    implementation project(':lib-notification')
    implementation project(':lib-document-generator')
    implementation project(':lib-editor')
    implementation project(':business-module-persistence-commons')
    implementation project(':file-commons')

    implementation 'de.topobyte:osm4j-core:latest.release'
    implementation 'de.topobyte:osm4j-pbf:latest.release'
    implementation 'net.javacrumbs.shedlock:shedlock-spring:latest.release'
    implementation 'net.javacrumbs.shedlock:shedlock-provider-jdbc-template:latest.release'
    implementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'
    implementation 'org.bouncycastle:bcprov-jdk18on:latest.release'

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation testFixtures(project(':lib-service-directory-admin-api'))
    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':lib-document-generator'))
}

dockerCompose {
    startedServices = ['inspection', 'inspection-db']
}

tasks.named("test").configure {
    dependsOn project(':base').tasks.named("composeUp")
    dependsOn project(':central-repository').tasks.named("composeUp")

    inputs.files(project(':central-repository').tasks.named("bootJar")).withNormalizer(ClasspathNormalizer.class)
    inputs.files(project(':service-directory').tasks.named("bootJar")).withNormalizer(ClasspathNormalizer.class)
    inputs.files(project(':base').tasks.named("bootJar")).withNormalizer(ClasspathNormalizer.class)
    inputs.files(project(':keycloak').tasks.named("jar")).withNormalizer(ClasspathNormalizer.class)
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-inspection') ?: "unspecified"
}
