plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
    id "eshg.central-repository-test-dependency"
}

dependencies {
    implementation project(':api-commons')
    implementation project(':lib-base-client')
    implementation project(':lib-central-repository-client')
    implementation project(':lib-procedures')
    implementation project(':lib-calendar')
    implementation project(':lib-notification')
    implementation project(':lib-department-info')
    implementation project(':lib-document-generator')
    implementation project(':lib-editor')
    implementation project(':lib-scheduling')
    implementation project(":lib-statistics")
    implementation project(':lib-xlsx-import')
    implementation project(':business-module-persistence-commons')
    implementation project(':file-commons')

    implementation 'de.topobyte:osm4j-core:latest.release'
    implementation 'de.topobyte:osm4j-pbf:latest.release'
    implementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'
    implementation 'org.bouncycastle:bcprov-jdk18on:latest.release'
    implementation 'org.apache.poi:poi:latest.release'
    implementation 'org.apache.poi:poi-ooxml:latest.release'

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation testFixtures(project(':lib-service-directory-admin-api'))
    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':lib-procedures'))
    testImplementation testFixtures(project(':lib-document-generator'))
    testImplementation testFixtures(project(':lib-xlsx-import'))
    testImplementation testFixtures(project(':lib-statistics'))
    testImplementation testFixtures(project(':lib-auditlog'))
}

dockerCompose {
    startedServices = ['inspection', 'inspection-db']
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-inspection') ?: "unspecified"
}
