plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':lib-appointmentblock')
    implementation project(':lib-base-client')
    implementation project(':lib-calendar')
    implementation project(':lib-contact')
    implementation project(":lib-document-generator")
    implementation project(':lib-procedures')
    implementation project(":lib-statistics")
    implementation project(":lib-xlsx-import")
    implementation project(':business-module-persistence-commons')
    implementation project(':file-commons')

    implementation 'org.apache.commons:commons-math3:latest.release'
    implementation 'de.cronn:reflection-util:latest.release'
    implementation 'com.google.zxing:core:latest.release'
    implementation 'org.apache.xmlgraphics:batik-svggen:latest.release'
    implementation 'org.apache.xmlgraphics:batik-dom:latest.release'

    implementation 'com.google.guava:guava:latest.release'
    implementation 'org.apache.commons:commons-csv:latest.release'
    implementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'
    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    compileOnly 'org.jetbrains:annotations:latest.release'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':lib-procedures'))
    testImplementation testFixtures(project(':lib-contact'))
    testImplementation 'com.google.zxing:javase:latest.release'
    testImplementation testFixtures(project(':lib-document-generator'))
    testImplementation testFixtures(project(':lib-xlsx-import'))
}

dockerCompose {
    startedServices = [
        'school-entry',
        'school-entry-db'
    ]
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-school-entry') ?: "unspecified"
}
