// Copyright 2026 cronn GmbH
// SPDX-License-Identifier: AGPL-3.0-only

plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
    id "eshg.central-repository-test-dependency"
}

dependencies {
    implementation project(':business-module-persistence-commons')
    implementation project(':lib-aggregation')
    implementation project(':lib-auditlog')
    implementation project(':lib-base-client')
    implementation project(':lib-central-repository-client')
    implementation project(':lib-scheduling')
    implementation project(':lib-statistics-api')
    implementation project(':rest-oauth-client-commons')
    implementation project(':file-commons')

    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation 'org.apache.poi:poi:latest.release'
    implementation 'org.apache.poi:poi-ooxml:latest.release'
    // explicitly tell gradle to use the latest release of commons-compress (currently 1.28.0),
    // because otherwise gradle chooses the version from poi-ooxml`s dependencies (currently 1.27.1)
    // which is not compatible with the current version of tika 3.2.2 (e.g. https://issues.apache.org/jira/browse/TIKA-4469 )
    implementation 'org.apache.commons:commons-compress:latest.release'

    // arx + dependencies
    implementation files('lib/org/deidentifier/arx/libarx-3.9.1-min.jar')
    implementation files('lib/de/linearbits/jhpl/jhpl-0.0.1.jar')
    implementation 'com.carrotsearch:hppc:0.6.0'
    implementation 'colt:colt:1.2.0'
    implementation 'org.apache.commons:commons-math3:latest.release'

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':lib-auditlog'))
}

dockerCompose {
    startedServices = [
        "statistics",
        "statistics-db"
    ]
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-statistics') ?: "unspecified"
}
