/*
 * Copyright 2024 cronn GmbH
 * SPDX-License-Identifier: Apache-2.0
 */

package de.eshg.medicalregistry.domain.model;

public enum ProfessionalTitle {
  DOCTORS,
  DENTISTS,
  PSYCHOLOGICAL_PSYCHOTHERAPISTS,
  NURSING_ASSISTANTS,
  GERIATRIC_NURSES,
  DIETICIANS,
  DISINFECTORS,
  OCCUPATIONAL_THERAPISTS,
  HEALTH_SUPERVISORS,
  HEALTHCARE_AND_PEDIATRIC_NURSES,
  HEALTHCARE_AND_NURSING_ASSISTANTS,
  HEALTHCARE_AND_NURSING_ASSISTANTS_HELPER,
  MIDWIVES_MATERNITY_NURSES,
  ALTERNATIVE_PRACTITIONERS,
  NON_MEDICAL_PRACTITIONER_FOR_CHIROPRACTIC,
  ALTERNATIVE_PRACTITIONER_FOR_SPEECH_THERAPY,
  NON_MEDICAL_PRACTITIONER_FOR_PHYSIOTHERAPY,
  NON_MEDICAL_PRACTITIONERS_FOR_PSYCHOTHERAPY,
  CHILD_AND_YOUTH_PSYCHOTHERAPISTS,
  SPEECH_THERAPISTS,
  MASSEURS_AND_MEDICAL_BATH_ATTENDANTS,
  MEDICAL_DOCUMENTALISTS,
  MEDICAL_TECHNICAL_LABORATORY_ASSISTANTS,
  MEDICAL_TECHNICAL_RADIOLOGY_ASSISTANTS,
  MEDICAL_TECHNICAL_ASSISTANTS_FOR_FUNCTIONAL_DIAGNOSTICS,
  EMERGENCY_PARAMEDICS,
  ORTHOPTISTS,
  CARE_ASSISTANTS,
  NURSING_SERVICES,
  NURSING_SERVICE_MANAGERS,
  PHARMACEUTICAL_TECHNICAL_ASSISTANTS,
  PHYSIOTHERAPISTS,
  PODIATRISTS,
  RADIOLOGY_ASSISTANTS,
  SPORTS_THERAPISTS,
  PHARMACISTS,
  VETERINARIANS,
}
