# https://github.com/spring-projects/spring-boot/issues/7107
spring.jpa.open-in-view=false

# Should only be enabled explicitly and per business module
spring.liquibase.enabled=false

spring.jpa.properties.hibernate.dialect=de.eshg.persistence.EshgPostgreSQLDialect

# Enable batched inserts and updates
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true

spring.jpa.properties.hibernate.jdbc.fetch_size=100
