plugins {
    id 'eshg.service'
}

dependencies {
    implementation project(':business-module-commons')
    implementation project(':lib-lsd-api')
    implementation project(':lib-service-directory-api')
    implementation project(':lib-service-directory-admin-api')

    implementation 'org.springframework.retry:spring-retry'
    implementation 'com.google.guava:guava'

    implementation libs.keycloak.client.admin.client
    implementation 'io.github.java-diff-utils:java-diff-utils:latest.release'

    testImplementation project(':lib-service-directory-admin-api')
    testImplementation testFixtures(project(':lib-lsd-api'))
    testImplementation testFixtures(project(':lib-service-directory-admin-api'))
    testImplementation testFixtures(project(':business-module-commons'))
}

dockerCompose {
    startedServices = ['local-service-directory']
}

tasks.named("test").configure {
    dependsOn ':service-directory:buildDockerImage'
    dependsOn ':keycloak:composeBuild'

    inputs.files(project(':service-directory').tasks.named("bootJar")).withNormalizer(ClasspathNormalizer.class)
    inputs.files(project(':keycloak').tasks.named("jar")).withNormalizer(ClasspathNormalizer.class)
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-local-service-directory') ?: "unspecified"
}
