plugins {
    id 'eshg.service'
}


dependencies {
    implementation project(':business-module-persistence-commons')
    implementation project(':rest-client-commons')
    implementation project(':lib-commons')
    implementation project(':lib-central-repository-api')
    implementation project(':lib-service-directory-api')

    implementation 'org.springframework.retry:spring-retry'

    implementation 'org.apache.commons:commons-fileupload2:latest.release'
    implementation 'org.apache.commons:commons-fileupload2-jakarta-servlet6:latest.release'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation project(':test-commons')
    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':lib-service-directory-admin-api'))
    testImplementation project(':lib-service-directory-admin-api')
    testImplementation testFixtures(project(':business-module-commons'))

    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
}


dockerCompose {
    startedServices = [
        'central-repository',
        'central-repository-db'
    ]
}

tasks.named("composeUp").configure {
    dependsOn ':service-directory:composeUp'
}

tasks.named("test").configure {
    dependsOn ':service-directory:buildDockerImage'
    dependsOn ':keycloak:composeBuild'
    inputs.files(project(':service-directory').tasks.named("bootJar")).withNormalizer(ClasspathNormalizer.class)
    inputs.files(project(':keycloak').tasks.named("jar")).withNormalizer(ClasspathNormalizer.class)
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-central-repository') ?: "unspecified"
}

