/*
 * Copyright 2026 cronn GmbH
 * SPDX-License-Identifier: Apache-2.0
 */

package de.eshg.lib.common;

import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Locale;

// ISO 3166-1
@Schema(
    name = "CountryCode",
    description =
        "List of country codes in ISO 3166-1 alpha-2 format. With custom extensions for stateless, non-standard countries, and unknown countries.")
public enum CountryCode {
  AD(Continents.EUROPE),
  AE(Continents.ASIA),
  AF(Continents.ASIA),
  AG(Continents.NORTHAMERICA),
  AI(Continents.NORTHAMERICA),
  AL(Continents.EUROPE),
  AM(Continents.ASIA),
  AO(Continents.AFRICA),
  AQ(Continents.ANTARCTICA),
  AR(Continents.SOUTHAMERICA),
  AS(Continents.OCEANIA),
  AT(Continents.EUROPE),
  AU(Continents.OCEANIA),
  AW(Continents.NORTHAMERICA),
  AX(Continents.EUROPE),
  AZ(Continents.ASIA),
  BA(Continents.EUROPE),
  BB(Continents.NORTHAMERICA),
  BD(Continents.ASIA),
  BE(Continents.EUROPE),
  BF(Continents.AFRICA),
  BG(Continents.EUROPE),
  BH(Continents.ASIA),
  BI(Continents.AFRICA),
  BJ(Continents.AFRICA),
  BL(Continents.NORTHAMERICA),
  BM(Continents.NORTHAMERICA),
  BN(Continents.ASIA),
  BO(Continents.SOUTHAMERICA),
  BQ(Continents.NORTHAMERICA),
  BR(Continents.SOUTHAMERICA),
  BS(Continents.NORTHAMERICA),
  BT(Continents.ASIA),
  BV(Continents.ANTARCTICA),
  BW(Continents.AFRICA),
  BY(Continents.EUROPE),
  BZ(Continents.NORTHAMERICA),
  CA(Continents.NORTHAMERICA),
  CC(Continents.ASIA),
  CD(Continents.AFRICA),
  CF(Continents.AFRICA),
  CG(Continents.AFRICA),
  CH(Continents.EUROPE),
  CI(Continents.AFRICA),
  CK(Continents.OCEANIA),
  CL(Continents.SOUTHAMERICA),
  CM(Continents.AFRICA),
  CN(Continents.ASIA),
  CO(Continents.SOUTHAMERICA),
  CR(Continents.NORTHAMERICA),
  CU(Continents.NORTHAMERICA),
  CV(Continents.AFRICA),
  CW(Continents.NORTHAMERICA),
  CX(Continents.ASIA),
  CY(Continents.ASIA),
  CZ(Continents.EUROPE),
  DE(Continents.EUROPE),
  DJ(Continents.AFRICA),
  DK(Continents.EUROPE),
  DM(Continents.NORTHAMERICA),
  DO(Continents.NORTHAMERICA),
  DZ(Continents.AFRICA),
  EC(Continents.SOUTHAMERICA),
  EE(Continents.EUROPE),
  EG(Continents.AFRICA),
  EH(Continents.AFRICA),
  ER(Continents.AFRICA),
  ES(Continents.EUROPE),
  ET(Continents.AFRICA),
  FI(Continents.EUROPE),
  FJ(Continents.OCEANIA),
  FK(Continents.SOUTHAMERICA),
  FM(Continents.OCEANIA),
  FO(Continents.EUROPE),
  FR(Continents.EUROPE),
  GA(Continents.AFRICA),
  GB(Continents.EUROPE),
  GD(Continents.NORTHAMERICA),
  GE(Continents.ASIA),
  GF(Continents.SOUTHAMERICA),
  GG(Continents.EUROPE),
  GH(Continents.AFRICA),
  GI(Continents.EUROPE),
  GL(Continents.NORTHAMERICA),
  GM(Continents.AFRICA),
  GN(Continents.AFRICA),
  GP(Continents.NORTHAMERICA),
  GQ(Continents.AFRICA),
  GR(Continents.EUROPE),
  GS(Continents.ANTARCTICA),
  GT(Continents.NORTHAMERICA),
  GU(Continents.OCEANIA),
  GW(Continents.AFRICA),
  GY(Continents.SOUTHAMERICA),
  HK(Continents.ASIA),
  HM(Continents.ANTARCTICA),
  HN(Continents.NORTHAMERICA),
  HR(Continents.EUROPE),
  HT(Continents.NORTHAMERICA),
  HU(Continents.EUROPE),
  ID(Continents.ASIA),
  IE(Continents.EUROPE),
  IL(Continents.ASIA),
  IM(Continents.EUROPE),
  IN(Continents.ASIA),
  IO(Continents.ASIA),
  IQ(Continents.ASIA),
  IR(Continents.ASIA),
  IS(Continents.EUROPE),
  IT(Continents.EUROPE),
  JE(Continents.EUROPE),
  JM(Continents.NORTHAMERICA),
  JO(Continents.ASIA),
  JP(Continents.ASIA),
  KE(Continents.AFRICA),
  KG(Continents.ASIA),
  KH(Continents.ASIA),
  KI(Continents.OCEANIA),
  KM(Continents.AFRICA),
  KN(Continents.NORTHAMERICA),
  KP(Continents.ASIA),
  KR(Continents.ASIA),
  KW(Continents.ASIA),
  KY(Continents.NORTHAMERICA),
  KZ(Continents.ASIA),
  LA(Continents.ASIA),
  LB(Continents.ASIA),
  LC(Continents.NORTHAMERICA),
  LI(Continents.EUROPE),
  LK(Continents.ASIA),
  LR(Continents.AFRICA),
  LS(Continents.AFRICA),
  LT(Continents.EUROPE),
  LU(Continents.EUROPE),
  LV(Continents.EUROPE),
  LY(Continents.AFRICA),
  MA(Continents.AFRICA),
  MC(Continents.EUROPE),
  MD(Continents.EUROPE),
  ME(Continents.EUROPE),
  MF(Continents.NORTHAMERICA),
  MG(Continents.AFRICA),
  MH(Continents.OCEANIA),
  MK(Continents.EUROPE),
  ML(Continents.AFRICA),
  MM(Continents.ASIA),
  MN(Continents.ASIA),
  MO(Continents.ASIA),
  MP(Continents.OCEANIA),
  MQ(Continents.NORTHAMERICA),
  MR(Continents.AFRICA),
  MS(Continents.NORTHAMERICA),
  MT(Continents.EUROPE),
  MU(Continents.AFRICA),
  MV(Continents.ASIA),
  MW(Continents.AFRICA),
  MX(Continents.NORTHAMERICA),
  MY(Continents.ASIA),
  MZ(Continents.AFRICA),
  NA(Continents.AFRICA),
  NC(Continents.OCEANIA),
  NE(Continents.AFRICA),
  NF(Continents.OCEANIA),
  NG(Continents.AFRICA),
  NI(Continents.NORTHAMERICA),
  NL(Continents.EUROPE),
  NO(Continents.EUROPE),
  NP(Continents.ASIA),
  NR(Continents.OCEANIA),
  NU(Continents.OCEANIA),
  NZ(Continents.OCEANIA),
  OM(Continents.ASIA),
  PA(Continents.NORTHAMERICA),
  PE(Continents.SOUTHAMERICA),
  PF(Continents.OCEANIA),
  PG(Continents.OCEANIA),
  PH(Continents.ASIA),
  PK(Continents.ASIA),
  PL(Continents.EUROPE),
  PM(Continents.NORTHAMERICA),
  PN(Continents.OCEANIA),
  PR(Continents.NORTHAMERICA),
  PS(Continents.ASIA),
  PT(Continents.EUROPE),
  PW(Continents.OCEANIA),
  PY(Continents.SOUTHAMERICA),
  QA(Continents.ASIA),
  RE(Continents.AFRICA),
  RO(Continents.EUROPE),
  RS(Continents.EUROPE),
  RU(Continents.EUROPE),
  RW(Continents.AFRICA),
  SA(Continents.ASIA),
  SB(Continents.OCEANIA),
  SC(Continents.AFRICA),
  SD(Continents.AFRICA),
  SE(Continents.EUROPE),
  SG(Continents.ASIA),
  SH(Continents.AFRICA),
  SI(Continents.EUROPE),
  SJ(Continents.EUROPE),
  SK(Continents.EUROPE),
  SL(Continents.AFRICA),
  SM(Continents.EUROPE),
  SN(Continents.AFRICA),
  SO(Continents.AFRICA),
  SR(Continents.SOUTHAMERICA),
  SS(Continents.AFRICA),
  ST(Continents.AFRICA),
  SV(Continents.NORTHAMERICA),
  SX(Continents.NORTHAMERICA),
  SY(Continents.ASIA),
  SZ(Continents.AFRICA),
  TC(Continents.NORTHAMERICA),
  TD(Continents.AFRICA),
  TF(Continents.ANTARCTICA),
  TG(Continents.AFRICA),
  TH(Continents.ASIA),
  TJ(Continents.ASIA),
  TK(Continents.OCEANIA),
  TL(Continents.ASIA),
  TM(Continents.ASIA),
  TN(Continents.AFRICA),
  TO(Continents.OCEANIA),
  TR(Continents.ASIA),
  TT(Continents.NORTHAMERICA),
  TV(Continents.OCEANIA),
  TW(Continents.ASIA),
  TZ(Continents.AFRICA),
  UA(Continents.EUROPE),
  UG(Continents.AFRICA),
  UM(Continents.OCEANIA),
  US(Continents.NORTHAMERICA),
  UY(Continents.SOUTHAMERICA),
  UZ(Continents.ASIA),
  VA(Continents.EUROPE),
  VC(Continents.NORTHAMERICA),
  VE(Continents.SOUTHAMERICA),
  VG(Continents.NORTHAMERICA),
  VI(Continents.NORTHAMERICA),
  VN(Continents.ASIA),
  VU(Continents.OCEANIA),
  WF(Continents.OCEANIA),
  WS(Continents.OCEANIA),
  YE(Continents.ASIA),
  YT(Continents.AFRICA),
  ZA(Continents.AFRICA),
  ZM(Continents.AFRICA),
  ZW(Continents.AFRICA),
  // Custom definitions
  XK(Continents.EUROPE),
  UNKNOWN("Unbekanntes Land"),
  STATELESS("Staatenlos"),
  ;

  private final String continent;

  CountryCode(String continent) {
    this.continent = continent;
  }

  public String getContinent() {
    return continent;
  }

  public static String getCountryName(CountryCode countryCode) {
    return switch (countryCode) {
      case null -> null;
      case XK -> "Kosovo";
      case UNKNOWN -> "Unbekanntes Land";
      case STATELESS -> "Staatenlos";
      default -> getCountryNameWithLocale(countryCode);
    };
  }

  private static String getCountryNameWithLocale(CountryCode countryCode) {
    Locale locale = new Locale.Builder().setRegion(countryCode.name()).setLanguage("DE").build();
    return locale.getDisplayCountry(locale);
  }

  private static class Continents {
    public static final String EUROPE = "Europa";
    public static final String OCEANIA = "Ozeanien";
    public static final String ASIA = "Asien";
    public static final String AFRICA = "Afrika";
    public static final String SOUTHAMERICA = "Südamerika";
    public static final String NORTHAMERICA = "Nordamerika";
    public static final String ANTARCTICA = "Antarktika";
  }
}
