// Copyright 2025 SCOOP Software GmbH, cronn GmbH
// SPDX-License-Identifier: Apache-2.0

plugins {
    id "eshg.java-lib"
}

dependencies {
    api project(':lib-central-repository-api')

    implementation project(':rest-client-commons')
    implementation project(':test-helper-commons-spring')

    implementation 'org.springframework.boot:spring-boot'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework:spring-context'

    implementation 'com.fasterxml.jackson.core:jackson-databind'
}
