// Copyright 2026 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

plugins {
    id "eshg.java-lib"
    id "eshg.base-test-dependency"
    id "java-test-fixtures"
}

dependencies {
    api project(':lib-appointmentblock-api')

    implementation project(':business-module-persistence-commons')
    implementation project(':base-api')
    implementation project(':lib-contact')
    implementation project(':business-module-commons')
    implementation project(':lib-config')

    implementation 'jakarta.persistence:jakarta.persistence-api'
    implementation 'org.springframework.data:spring-data-jpa'
    implementation 'org.openapitools:jackson-databind-nullable:latest.release'
    implementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'
    implementation 'org.apache.commons:commons-text:latest.release'
    compileOnly 'org.jetbrains:annotations:latest.release'

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    testFixturesApi testFixtures(project(':business-module-persistence-commons'))
    testFixturesApi testFixtures(project(':lib-auditlog'))
    testFixturesApi project(':lib-config')
    testFixturesImplementation 'org.springframework.boot:spring-boot-test'
    testFixturesImplementation 'org.assertj:assertj-core'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    testRuntimeOnly project(':lib-base-client')
    testRuntimeOnly 'org.postgresql:postgresql'
}
