plugins {
    id "eshg.java-lib"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':business-module-persistence-commons')
    implementation project(':lib-base-client')
    implementation project(':lib-contact')
    implementation project(':business-module-commons')

    implementation 'jakarta.persistence:jakarta.persistence-api'
    implementation 'org.springframework.data:spring-data-jpa'
    implementation 'org.openapitools:jackson-databind-nullable:latest.release'
    implementation 'org.springdoc:springdoc-openapi-starter-common:2.6.0' // Pinned to workaround https://github.com/springdoc/springdoc-openapi/issues/2776
    compileOnly 'org.jetbrains:annotations:latest.release'

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation "org.testcontainers:junit-jupiter"
    testImplementation 'org.testcontainers:postgresql'

    testRuntimeOnly 'org.postgresql:postgresql'
}
