// Copyright 2025 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

plugins {
    id "eshg.java-lib"
}

dependencies {
    testImplementation(getRootProject().getSubprojects())

    testImplementation 'com.tngtech.archunit:archunit:latest.release'
    testImplementation 'org.reflections:reflections:latest.release'
    testImplementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'
    testImplementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    testImplementation 'com.google.guava:guava:latest.release'

    testCompileOnly('org.hibernate.orm:hibernate-envers')
}
