plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':business-module-commons')
    implementation project(':file-commons')
    implementation project(':business-module-persistence-commons')
    implementation project(':auditlog-api')
    implementation project(':lib-base-client')
    implementation 'org.springdoc:springdoc-openapi-starter-common:2.6.0' // Pinned to workaround https://github.com/springdoc/springdoc-openapi/issues/2776
    implementation 'commons-io:commons-io:latest.release'
    runtimeOnly 'org.postgresql:postgresql'
    testImplementation project(':test-commons')
    testImplementation testFixtures(project(':business-module-commons'))
    testImplementation testFixtures(project(':business-module-persistence-commons'))
    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.springdoc:springdoc-openapi-starter-common:2.6.0' // Pinned to workaround https://github.com/springdoc/springdoc-openapi/issues/2776
}

dockerCompose {
    startedServices = ['opendata', 'opendata-db']
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-opendata') ?: "unspecified"
}

