// Copyright 2026 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':business-module-commons')
    implementation project(':file-commons')
    implementation project(':business-module-persistence-commons')
    implementation project(':auditlog-api')
    implementation project(':lib-base-client')
    implementation project(':lib-config')
    implementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'
    implementation 'commons-io:commons-io:latest.release'
    runtimeOnly 'org.postgresql:postgresql'
    testImplementation project(':test-commons')
    testImplementation testFixtures(project(':business-module-commons'))
    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':lib-auditlog'))
    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    testImplementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'
}

dockerCompose {
    startedServices = ['opendata', 'opendata-db']
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-opendata') ?: "unspecified"
}

