// Copyright 2025 SCOOP Software GmbH, cronn GmbH
// SPDX-License-Identifier: AGPL-3.0-only

plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':lib-base-client')
    implementation project(':lib-procedures')
    implementation project(':lib-calendar')
    implementation project(':lib-config')
    implementation project(':business-module-commons')
    implementation project(':business-module-persistence-commons')
    implementation project(':rest-oauth-client-commons')
    implementation project(':lib-appointmentblock')
    implementation project(":lib-statistics")
    implementation project(':lib-scheduling')
    implementation project(':file-commons')

    implementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation testFixtures(project(':business-module-persistence-commons'))
    testImplementation testFixtures(project(':lib-procedures'))
    testImplementation testFixtures(project(':lib-statistics'))
    testImplementation testFixtures(project(':base-api'))
    testImplementation testFixtures(project(':lib-auditlog'))
    testImplementation testFixtures(project(':lib-appointmentblock'))
}

dockerCompose {
    startedServices = [
        'official-medical-service',
        'official-medical-service-db'
    ]
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-official-medical-service') ?: "unspecified"
}



