# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5443/centralrepository
spring.datasource.username=testuser
spring.datasource.password=testpassword
spring.mvc.async.request-timeout=100s

# We want to handle multipart manually as Spring doesn't support streaming of large files there
spring.servlet.multipart.enabled=false

# We have to disable logbook for those paths.
# Otherwise, it will try to buffer and log the whole possibly huge request / response.
logbook.predicate.exclude[0].path=/versioned/**

# Hibernate
spring.jpa.hibernate.ddl-auto=validate

# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

server.port=8091

logging.level.org.zalando.logbook=TRACE

eshg.servicedirectory.baseUrl=http://localhost:8083
