// Copyright 2026 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

plugins {
    id "eshg.service"
    id "eshg.base-test-dependency"
}

dependencies {
    implementation project(':lib-base-client')
    implementation project(':business-module-commons')

    testImplementation testFixtures(project(':business-module-commons'))
    implementation 'org.springdoc:springdoc-openapi-starter-common:latest.release'
}

dockerCompose {
    startedServices = ['file-jockey']
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-file-jockey') ?: "unspecified"
}
