plugins {
    id 'eshg.service'
}

dependencies {
    compileOnly project(':rest-service-commons')
    compileOnly 'org.zalando:logbook-api:latest.release'

    implementation project(':lib-service-directory-api')
    implementation project(':lib-service-directory-admin-api')
    implementation project(':business-module-persistence-commons')
    implementation project(':lib-commons')
    implementation 'org.apache.commons:commons-collections4:latest.release'
    implementation 'org.bouncycastle:bcpkix-jdk18on:latest.release'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation testFixtures(project(':lib-service-directory-admin-api'))
    testImplementation testFixtures(project(':business-module-persistence-commons'))

    testImplementation project(':test-commons')
}

dockerCompose {
    startedServices = [
        'service-directory',
        'service-directory-db'
    ]
}

// This is required otherwise `./gradlew --parallel service-directory:build local-service-directory:build` doesn't run in parallel
tasks.named('test').configure {
    mustRunAfter tasks.named('buildDockerImage')
}

dependencyTrack {
    projectId = project.findProperty('dependency-track-project-id-service-directory') ?: "unspecified"
}
