parent=keycloak.v2
styles=css/styles.css css/custom-styles.css

# TODO: Remove these once https://github.com/keycloak/keycloak/issues/45162 is closed
kcSelectAuthListItemArrowIconClass=fa fa-angle-right fa-lg
kcAuthenticatorDefaultClass=fa fa-list list-view-pf-icon-lg
kcAuthenticatorWebAuthnPasswordlessClass=fa fa-key list-view-pf-icon-lg
kcFeedbackErrorIcon=fa fa-fw fa-exclamation-circle
kcFeedbackWarningIcon=fa fa-fw fa-exclamation-triangle
kcFeedbackSuccessIcon=fa fa-fw fa-check-circle
kcFeedbackInfoIcon=fa fa-fw fa-info-circle
kcWebAuthnKeyIcon=fa fa-key
