spring.datasource.url=jdbc:postgresql://localhost:5449/official_medical_service
spring.datasource.username=testuser
spring.datasource.password=testpassword

# The port should match the one specified in the configuration annotated with @OpenAPIDefinition.
server.port=8099

spring.jpa.hibernate.ddl-auto=validate

# Liquibase
# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

logging.level.org.zalando.logbook=TRACE

spring.security.oauth2.client.registration.module-client.client-id=system-official-medical-service
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

de.eshg.opening-hours.de[0]=Sprechzeiten nur nach Terminvereinbarung:
de.eshg.opening-hours.de[1]=Mo bis Fr 08:00 bis 12:00 Uhr
de.eshg.opening-hours.de[2]=Telefonische Terminvereinbarung:
de.eshg.opening-hours.de[3]=Mo bis Do 08:00 bis 11:00 Uhr und 14:00 bis 15:00 Uhr\nFr 08:00 bis 11:00 Uhr

de.eshg.opening-hours.en[0]=Consultation hours only with appointment:
de.eshg.opening-hours.en[1]=Mon to Fri 08:00 to 12:00
de.eshg.opening-hours.en[2]=Make an appointment by telephone:
de.eshg.opening-hours.en[3]=Mon to Thu 08:00 to 11:00 a.m. and 02:00 to 03:00 p.m.\nFri 08:00 to 11:00 a.m.

de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[OFFICIAL_MEDICAL_SERVICE_SHORT]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[OFFICIAL_MEDICAL_SERVICE_LONG]=120m
de.eshg.lib.appointmentblock.createAppointmentBlockForCurrentUser=false

eshg.population.default-number-of-entities-to-populate.appointment-block-group=0

eshg.citizen-portal.reverse-proxy.url=http://localhost:4001

de.eshg.official-medical-service.concerns.templates.path=concerns

de.eshg.official-medical-service.concerns.config=classpath:${de.eshg.official-medical-service.concerns.templates.path}/concerns.yaml

de.eshg.official-medical-service.landing.templates.path=landing/default

de.eshg.official-medical-service.landing.config.de=classpath:${de.eshg.official-medical-service.landing.templates.path}/landing_DE.md
de.eshg.official-medical-service.landing.config.en=classpath:${de.eshg.official-medical-service.landing.templates.path}/landing_EN.md

# standard notifications (by mail)
de.eshg.official-medical-service.notification.templates.path=notifications/default/de
de.eshg.official-medical-service.notification.template.new_citizen_user.subject=Bestätigung
de.eshg.official-medical-service.notification.template.new_citizen_user.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/new_citizen_user.html
de.eshg.official-medical-service.notification.template.new_citizen_procedure.subject=Eingangsbestätigung
de.eshg.official-medical-service.notification.template.new_citizen_procedure.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/new_citizen_procedure.html
de.eshg.official-medical-service.notification.template.new_document.subject=Neues Dokument
de.eshg.official-medical-service.notification.template.new_document.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/new_document.html
de.eshg.official-medical-service.notification.template.new_appointment_with_booking.subject=Neuer Termin
de.eshg.official-medical-service.notification.template.new_appointment_with_booking.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/new_appointment_with_booking.html
de.eshg.official-medical-service.notification.template.new_appointment_self_booking.subject=Neue Terminbuchungsoption
de.eshg.official-medical-service.notification.template.new_appointment_self_booking.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/new_appointment_self_booking.html
de.eshg.official-medical-service.notification.template.cancel_appointment.subject=Termin abgesagt
de.eshg.official-medical-service.notification.template.cancel_appointment.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/cancel_appointment.html
de.eshg.official-medical-service.notification.template.cancel_appointment_with_reason.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/cancel_appointment_with_reason.html
de.eshg.official-medical-service.notification.template.rebook_appointment.subject=Termin ungebucht
de.eshg.official-medical-service.notification.template.rebook_appointment.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/rebook_appointment.html
de.eshg.official-medical-service.notification.template.close_appointment.subject=Termin zurückgezogen
de.eshg.official-medical-service.notification.template.close_appointment.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/close_appointment.html
de.eshg.official-medical-service.notification.template.book_appointment_cp.subject=Termin gebucht
de.eshg.official-medical-service.notification.template.book_appointment_cp.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/book_appointment_cp.html
de.eshg.official-medical-service.notification.template.rebook_appointment_cp.subject=Termin umgebucht
de.eshg.official-medical-service.notification.template.rebook_appointment_cp.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/rebook_appointment_cp.html
de.eshg.official-medical-service.notification.template.cancel_appointment_cp.subject=Termin abgesagt
de.eshg.official-medical-service.notification.template.cancel_appointment_cp.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/cancel_appointment_cp.html
de.eshg.official-medical-service.notification.template.review_document_accepted.subject=Dokumentenprüfung erfolgreich
de.eshg.official-medical-service.notification.template.review_document_accepted.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/review_document_accepted.html
de.eshg.official-medical-service.notification.template.review_document_rejected.subject=Dokumentenprüfung erfordert Nachbesserung
de.eshg.official-medical-service.notification.template.review_document_rejected.body=classpath:${de.eshg.official-medical-service.notification.templates.path}/review_document_rejected.html

de.eshg.official-medical-service.keycloak-user-cleanup-job.overdue-duration=30d

de.eshg.department-info.use-privacy-documents-from-base-module=false
de.eshg.department-info.privacy-notice=classpath:privacy_documents/privacy_notice.pdf

# activates the alert (to complete a medical opinion) a number of days prior to the cut-off date of the resp. procedure
de.eshg.official-medical-service.cutOffDate.leadTime=0

de.eshg.official-medical-service.anamnesis.anamnesis-enabled=true
