de.eshg.official-medical-service.opening-hours.de[0]=Termine nach Vereinbarung
de.eshg.official-medical-service.opening-hours.de[1]=Mo - Fr: 08:00 - 12:00 Uhr
de.eshg.official-medical-service.opening-hours.de[2]=Mo - Do: 08:00 - 11:00 Uhr und 14:00 - 15:00 Uhr
de.eshg.official-medical-service.opening-hours.de[3]=telefonische Terminvereinbarung
de.eshg.official-medical-service.opening-hours.de[4]=Fr: 08:00 - 11:00 Uhr
de.eshg.official-medical-service.opening-hours.de[5]=telefonische Terminvereinbarung
de.eshg.official-medical-service.opening-hours.en[0]=Dates by arrangement
de.eshg.official-medical-service.opening-hours.en[1]=Mon - Fri: 08:00 - 12:00
de.eshg.official-medical-service.opening-hours.en[2]=Mon - Thu: 08:00 - 11:00 a.m. and 02:00 - 03:00 p.m.
de.eshg.official-medical-service.opening-hours.en[3]=telephone appointment
de.eshg.official-medical-service.opening-hours.en[4]=Fri: 08:00 - 11:00 a.m.
de.eshg.official-medical-service.opening-hours.en[5]=telephone appointment


# can be set individually to overwrite base department infos
# de.eshg.official-medical-service.department-info.name=
# de.eshg.official-medical-service.department-info.abbreviation=
# de.eshg.official-medical-service.department-info.street=
# de.eshg.official-medical-service.department-info.houseNumber=
# de.eshg.official-medical-service.department-info.postalCode=
# de.eshg.official-medical-service.department-info.city=
# de.eshg.official-medical-service.department-info.country=
de.eshg.official-medical-service.department-info.phoneNumber=069 212 33622
# de.eshg.official-medical-service.department-info.homepage=
de.eshg.official-medical-service.department-info.email=info.amtsaerztlicherdienst@stadt-frankfurt.de
# de.eshg.official-medical-service.department-info.latitude=
# de.eshg.official-medical-service.department-info.longitude=

# notifications (by mail)
de.eshg.official-medical-service.notification.fromAddress=tba@stadt-frankfurt.de
de.eshg.official-medical-service.notification.greeting=Ihr TBA-Team der Stadt Frankfurt
de.eshg.official-medical-service.notification.templates.path=notifications/ga_frankfurt/de

de.eshg.official-medical-service.privacy-notice-location=classpath:privacy_documents/privacy_notice.pdf
de.eshg.official-medical-service.privacy-policy-location=classpath:privacy_documents/privacy_policy.pdf
