# **************************************************************************************** #
#    Make sure any health-department specific configuration is present in the database     #
#                    See de.eshg.config.EshgConfigurationService                           #
#                                                                                          #
#                      !!! These properties are only defaults !!!                          #
#  !!! Changes and new properties will not be migrated to already populated databases !!!  #
#             !!! All changes need database migrations via liquibase !!!                   #
# **************************************************************************************** #

de.eshg.opening-hours.de[0]=Sprechzeiten nur nach Terminvereinbarung:
de.eshg.opening-hours.de[1]=Mo bis Fr 08:00 bis 12:00 Uhr
de.eshg.opening-hours.de[2]=Telefonische Terminvereinbarung:
de.eshg.opening-hours.de[3]=Mo bis Do 08:00 bis 11:00 Uhr und 14:00 bis 15:00 Uhr\nFr 08:00 bis 11:00 Uhr

de.eshg.opening-hours.en[0]=Consultation hours only with appointment:
de.eshg.opening-hours.en[1]=Mon to Fri 08:00 to 12:00
de.eshg.opening-hours.en[2]=Make an appointment by telephone:
de.eshg.opening-hours.en[3]=Mon to Thu 08:00 to 11:00 a.m. and 02:00 to 03:00 p.m.\nFri 08:00 to 11:00 a.m.

# can be set individually to overwrite base department infos
de.eshg.department-info.use-department-info-from-base-module=false
# de.eshg.departmentinfo-info.name=
# de.eshg.departmentinfo-info.abbreviation=
# de.eshg.departmentinfo-info.street=
# de.eshg.departmentinfo-info.houseNumber=
# de.eshg.departmentinfo-info.postalCode=
# de.eshg.departmentinfo-info.city=
# de.eshg.departmentinfo-info.country=
de.eshg.department-info.phoneNumber=069 212 33622
# de.eshg.departmentinfo-info.homepage=
de.eshg.department-info.email=info.amtsaerztlicherdienst@stadt-frankfurt.de
# de.eshg.departmentinfo-info.latitude=
# de.eshg.departmentinfo-info.longitude=


# config service
de.eshg.official-medical-service.config.landing.templates.path=landing/ga_frankfurt
# de.eshg.official-medical-service.config.concerns=
# de.eshg.official-medical-service.config.landing-content-de=
# de.eshg.official-medical-service.config.landing-content-en=
# de.eshg.official-medical-service.config.keycloak-user-cleanup-job-overdue-duration=
# de.eshg.official-medical-service.config.medical-opinion-cut-off-date-lead-time=
# de.eshg.official-medical-service.config.citizen-portal-anamnesis-enabled=


# notifications (by mail)
de.eshg.official-medical-service.notification.templates.path=notifications/ga_frankfurt/de

de.eshg.department-info.use-privacy-documents-from-base-module=false
de.eshg.department-info.privacy-notice=classpath:privacy_documents/privacy_notice.pdf


# **************************************************************************************** #
#    Make sure any health-department specific configuration is present in the database     #
#                    See de.eshg.config.EshgConfigurationService                           #
#                                                                                          #
#                      !!! These properties are only defaults !!!                          #
#  !!! Changes and new properties will not be migrated to already populated databases !!!  #
#             !!! All changes need database migrations via liquibase !!!                   #
# **************************************************************************************** #
