de.eshg.opening-hours.de[0]=Sprechzeiten nur nach Terminvereinbarung:
de.eshg.opening-hours.de[1]=Mo bis Fr 08:00 bis 12:00 Uhr
de.eshg.opening-hours.de[2]=Telefonische Terminvereinbarung:
de.eshg.opening-hours.de[3]=Mo bis Do 08:00 bis 11:00 Uhr und 14:00 bis 15:00 Uhr\nFr 08:00 bis 11:00 Uhr

de.eshg.opening-hours.en[0]=Consultation hours only with appointment:
de.eshg.opening-hours.en[1]=Mon to Fri 08:00 to 12:00
de.eshg.opening-hours.en[2]=Make an appointment by telephone:
de.eshg.opening-hours.en[3]=Mon to Thu 08:00 to 11:00 a.m. and 02:00 to 03:00 p.m.\nFri 08:00 to 11:00 a.m.

de.eshg.department-info.use-privacy-documents-from-base-module=false
de.eshg.department-info.privacy-notice=classpath:privacy_documents/privacy_notice.pdf
