# **************************************************************************************** #
#    Make sure any health-department specific configuration is present in the database     #
#                    See de.eshg.config.EshgConfigurationService                           #
#                                                                                          #
#                      !!! These properties are only defaults !!!                          #
#  !!! Changes and new properties will not be migrated to already populated databases !!!  #
#             !!! All changes need database migrations via liquibase !!!                   #
# **************************************************************************************** #

de.eshg.opening-hours.de[0]=Termine nach Vereinbarung
de.eshg.opening-hours.de[1]=Mo - Fr: 08:00 - 12:00 Uhr
de.eshg.opening-hours.de[2]=Mo - Do: 08:00 - 11:00 Uhr und 14:00 - 15:00 Uhr
de.eshg.opening-hours.de[3]=telefonische Terminvereinbarung
de.eshg.opening-hours.de[4]=Fr: 08:00 - 11:00 Uhr
de.eshg.opening-hours.de[5]=telefonische Terminvereinbarung
de.eshg.opening-hours.en[0]=Dates by arrangement
de.eshg.opening-hours.en[1]=Mon - Fri: 08:00 - 12:00
de.eshg.opening-hours.en[2]=Mon - Thu: 08:00 - 11:00 a.m. and 02:00 - 03:00 p.m.
de.eshg.opening-hours.en[3]=telephone appointment
de.eshg.opening-hours.en[4]=Fri: 08:00 - 11:00 a.m.
de.eshg.opening-hours.en[5]=telephone appointment

# can be set individually to overwrite base department infos
de.eshg.department-info.use-department-info-from-base-module=false
# de.eshg.departmentinfo-info.name=
# de.eshg.departmentinfo-info.abbreviation=
# de.eshg.departmentinfo-info.street=
# de.eshg.departmentinfo-info.houseNumber=
# de.eshg.departmentinfo-info.postalCode=
# de.eshg.departmentinfo-info.city=
# de.eshg.departmentinfo-info.country=
de.eshg.department-info.phoneNumber=069 212 33622
# de.eshg.departmentinfo-info.homepage=
de.eshg.department-info.email=info.amtsaerztlicherdienst@stadt-frankfurt.de
# de.eshg.departmentinfo-info.latitude=
# de.eshg.departmentinfo-info.longitude=

# notifications (by mail)
de.eshg.official-medical-service.notification.templates.path=notifications/ga_frankfurt/de

de.eshg.department-info.use-privacy-documents-from-base-module=false
de.eshg.department-info.privacy-notice=classpath:privacy_documents/privacy_notice.pdf

# landing config
de.eshg.official-medical-service.landing.templates.path=landing/ga_frankfurt

# **************************************************************************************** #
#    Make sure any health-department specific configuration is present in the database     #
#                    See de.eshg.config.EshgConfigurationService                           #
#                                                                                          #
#                      !!! These properties are only defaults !!!                          #
#  !!! Changes and new properties will not be migrated to already populated databases !!!  #
#             !!! All changes need database migrations via liquibase !!!                   #
# **************************************************************************************** #
