spring.datasource.url=jdbc:postgresql://localhost:5449/official_medical_service
spring.datasource.username=testuser
spring.datasource.password=testpassword

# The port should match the one specified in the configuration annotated with @OpenAPIDefinition.
server.port=8099

spring.jpa.hibernate.ddl-auto=create

# Liquibase
# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=false
# spring.liquibase.change-log=classpath:/migrations/changelog.xml

logging.level.org.zalando.logbook=TRACE

spring.security.oauth2.client.registration.module-client.client-id=system-official-medicine-service
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

de.eshg.official-medical-service.opening-hours.de[0]=Termine nach Vereinbarung
de.eshg.official-medical-service.opening-hours.de[1]=Mo - Fr: 08:00 - 12:00 Uhr
de.eshg.official-medical-service.opening-hours.de[2]=Mo - Do: 08:00 - 11:00 Uhr und 14:00 - 15:00 Uhr
de.eshg.official-medical-service.opening-hours.de[3]=telefonische Terminvereinbarung
de.eshg.official-medical-service.opening-hours.de[4]=Fr: 08:00 - 11:00 Uhr
de.eshg.official-medical-service.opening-hours.de[5]=telefonische Terminvereinbarung

de.eshg.official-medical-service.opening-hours.en[0]=Dates by arrangement
de.eshg.official-medical-service.opening-hours.en[1]=Mon - Fri: 08:00 - 12:00
de.eshg.official-medical-service.opening-hours.en[2]=Mon - Thu: 08:00 - 11:00 a.m. and 14:00 - 15:00
de.eshg.official-medical-service.opening-hours.en[3]=telephone appointment
de.eshg.official-medical-service.opening-hours.en[4]=Fri: 08:00 - 11:00 a.m.
de.eshg.official-medical-service.opening-hours.en[5]=telephone appointment

de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[OFFICIAL_MEDICAL_SERVICE]=30m
de.eshg.lib.appointmentblock.createAppointmentBlockForCurrentUser=false

eshg.population.default-number-of-entities-to-populate.appointment-block-group=0
