server {
    listen       4002;
    server_name  reverse-proxy;

    location /adminapi/ {
        proxy_set_header x-eshg-cert-subject "CN=admin-nginx.central-services.ga-lotse";
        proxy_pass http://host.docker.internal:8083/adminapi/;
    }

    location /audit/ {
        proxy_set_header x-eshg-cert-subject "CN=admin-nginx.central-services.ga-lotse";
        proxy_pass http://host.docker.internal:8083/audit/;
    }

    location / {
        proxy_pass http://host.docker.internal:3002/;
    }

    location /_next/webpack-hmr {
        proxy_pass http://host.docker.internal:3002/_next/webpack-hmr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
