server {
    listen       4003;
    server_name  reverse-proxy;

    #access_log  /var/log/nginx/host.access.log  main;

    location /js/ {
        proxy_pass http://host.docker.internal:9090/;
    }

    location /resources/ {
        proxy_pass http://host.docker.internal:9090/resources/;
    }

    location = /robots.txt {
        proxy_pass http://host.docker.internal:9090/robots.txt;
    }

    location = / {
        proxy_pass http://host.docker.internal:9090/;
    }

    location = /admin/ {
        proxy_pass http://host.docker.internal:9090/admin/;
    }

    location = /admin/serverinfo {
        proxy_pass http://host.docker.internal:9090/admin/serverinfo;
    }

    location /admin/master/console/ {
        proxy_pass http://host.docker.internal:9090/admin/master/console/;
    }

    location /admin/realms/ {
        proxy_pass http://host.docker.internal:9090/admin/realms/;
    }

    location /realms/master/ {
        proxy_pass http://host.docker.internal:9090/realms/master/;
    }

    location /realms/citizens/ {
        proxy_pass http://host.docker.internal:9090/realms/citizens/;
    }

    location /realms/eshg/ {
        proxy_pass http://host.docker.internal:9090/realms/eshg/;
    }

    # only for local testing with MUK simulated in muk-test realm
    location /realms/muk-test/ {
        proxy_pass http://host.docker.internal:9090/realms/muk-test/;
    }

 # specify a custom error page for all common HTTP errors
  error_page
      400 401 402 403 404 405 406 408 409 410 411 412 413 414 415 416 421 429
      500 501 502 503 504 505 507
      @errors;

  # location block for our custom error page
  location @errors {
      internal;
      default_type "text/html; charset=utf-8";
      return 200 '
              <!DOCTYPE html>
              <html lang="en">
              <head>
                  <meta charset="UTF-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1.0">
                  <title>Error</title>
                  <style>
                      body { font-family: Arial, sans-serif; text-align: center; }
                      .error-container { margin-top: 50px; }
                  </style>
              </head>
              <body>
                  <div class="error-container">
                      <h1>Oh-weh! Da ging etwas schief.</h1>
                      <p>Wir haben technische Schwierigkeiten. Bitte versuchen Sie es sp&auml;ter noch einmal.</p>
                  </div>
                  <div class="error-container">
                      <h1>Oops! Something went wrong.</h1>
                      <p>We\'re experiencing technical difficulties. Please try again later.</p>
                  </div>
              </body>
              </html>
          ';
  }
}
