plugins {
    id "eshg.java-lib"
}

dependencies {
    implementation 'org.slf4j:slf4j-api'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-actuator-autoconfigure'
    implementation 'org.springframework:spring-web'
    implementation 'org.apache.tomcat.embed:tomcat-embed-core'

    implementation project(":logging-commons")
    implementation project(':test-helper-commons-spring')

    compileOnly 'org.jetbrains:annotations:latest.release'

    runtimeOnly "org.zalando:logbook-spring-boot-starter:latest.release"
}
