eshg.realm=citizens

eshg.reverse-proxy.url=http://localhost:4001

spring.security.oauth2.client.registration.keycloak.client-secret=tstj3RgLtqF4Kbh3hVNRRXTwxLkhmq

eshg.auth.language-path-prefixes=/de, /en
eshg.auth.access-code-url-patterns=/einschulungsuntersuchung/termin, /impfberatung/meine-termine
eshg.auth.muk-url-patterns=/unternehmen/**
eshg.auth.bund-id-url-patterns=/mein-bereich/**
