eshg.realm=citizens

eshg.reverse-proxy.url=http://localhost:4001

spring.security.oauth2.client.registration.keycloak.client-secret=tstj3RgLtqF4Kbh3hVNRRXTwxLkhmq

eshg.auth.language-path-prefixes=/de, /en

eshg.auth.access-code-url-patterns[SCHOOL_ENTRY]=/einschulungsuntersuchung/termin
eshg.auth.access-code-url-patterns[TRAVEL_MEDICINE]=/impfberatung/meine-termine
eshg.auth.access-code-url-patterns[STI_PROTECTION]=/sexuelle-gesundheit/mein-bereich
eshg.auth.access-code-url-patterns[OFFICIAL_MEDICAL_SERVICE]=/amtsaerztlicherdienst/mein-bereich

eshg.auth.muk-url-patterns=/unternehmen/**
eshg.auth.bund-id-url-patterns=/mein-bereich/**
