# align tomcat's session management with the configuration of Spring managed sessions
server.servlet.session.timeout=${spring.session.timeout}
server.servlet.session.cookie.name=SESSION

# this prevents RedisSessionConfiguration from creating any beans
# might break in future spring boot versions!
spring.session.redis.repository-type=
management.health.redis.enabled=false
