server.port=8092
server.tomcat.max-http-response-header-size=24KB

spring.security.oauth2.client.registration.keycloak.client-id=system-eshg-auth-service
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=${eshg.reverse-proxy.url}/auth/login/keycloak

eshg.keycloak.url=http://${DOCKER_HOSTNAME:localhost}:4003
eshg.keycloak.internal.url=http://${DOCKER_HOSTNAME:localhost}:9090

spring.security.oauth2.client.provider.keycloak.token-uri=${eshg.keycloak.internal.url}/realms/${eshg.realm}/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.authorization-uri=${eshg.keycloak.url}/realms/${eshg.realm}/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=${eshg.keycloak.internal.url}/realms/${eshg.realm}/protocol/openid-connect/certs

eshg.keycloak.logout.url=${eshg.keycloak.url}/realms/${eshg.realm}/protocol/openid-connect/logout

logging.level.de.eshg.security.auth=DEBUG
logging.level.org.springframework.security=DEBUG

logging.level.org.zalando.logbook=TRACE

# Keep this setting in sync with "eshg.keycloak.session-timeout" of the "base" module
spring.session.timeout=30m

spring.data.redis.host=${DOCKER_HOSTNAME:localhost}
spring.data.redis.password=redis_secret

spring.web.resources.static-locations=classpath:/static

eshg.auth.user-agent-filter.enabled=true

server.forward-headers-strategy=native

spring.config.import=classpath:/user-agent-filter.yaml
