/*
 * Copyright 2025 cronn GmbH
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package de.eshg.schoolentry.mapper;

import de.eshg.schoolentry.SchoolInfoLetterValidator.Property;
import de.eshg.schoolentry.api.ProcedureProperty;

public final class ProcedurePropertyMapper {

  private ProcedurePropertyMapper() {}

  public static ProcedureProperty toDto(Property property) {
    return switch (property) {
      case HEARING_TEST_EXAMINATION_RESULT -> ProcedureProperty.HEARING_TEST_EXAMINATION_RESULT;
      case EYE_EXAMINATION_EYE_EXAMINATION -> ProcedureProperty.EYE_EXAMINATION_EYE_EXAMINATION;
      case EYE_EXAMINATION_ISHIHARA_EXAMINATION ->
          ProcedureProperty.EYE_EXAMINATION_ISHIHARA_EXAMINATION;
      case EYE_EXAMINATION_LANG_EXAMINATION -> ProcedureProperty.EYE_EXAMINATION_LANG_EXAMINATION;
      case ANAMNESIS_BIRTH_WEIGHT -> ProcedureProperty.ANAMNESIS_BIRTH_WEIGHT;
      case ANAMNESIS_CHILD_LANGUAGE_SCREENING ->
          ProcedureProperty.ANAMNESIS_CHILD_LANGUAGE_SCREENING;
      case ANAMNESIS_COUNTRY_OF_BIRTH_CHILD -> ProcedureProperty.ANAMNESIS_COUNTRY_OF_BIRTH_CHILD;
      case ANAMNESIS_COUNTRY_OF_BIRTH_FIRST_PARENT ->
          ProcedureProperty.ANAMNESIS_COUNTRY_OF_BIRTH_FIRST_PARENT;
      case ANAMNESIS_COUNTRY_OF_BIRTH_SECOND_PARENT ->
          ProcedureProperty.ANAMNESIS_COUNTRY_OF_BIRTH_SECOND_PARENT;
      case ANAMNESIS_EARLY_SUPPORT -> ProcedureProperty.ANAMNESIS_EARLY_SUPPORT;
      case ANAMNESIS_ERGOTHERAPY -> ProcedureProperty.ANAMNESIS_ERGOTHERAPY;
      case ANAMNESIS_INTEGRATION_PLACE -> ProcedureProperty.ANAMNESIS_INTEGRATION_PLACE;
      case ANAMNESIS_NATIONALITY_CHILD -> ProcedureProperty.ANAMNESIS_NATIONALITY_CHILD;
      case ANAMNESIS_NATIONALITY_FIRST_PARENT ->
          ProcedureProperty.ANAMNESIS_NATIONALITY_FIRST_PARENT;
      case ANAMNESIS_NATIONALITY_SECOND_PARENT ->
          ProcedureProperty.ANAMNESIS_NATIONALITY_SECOND_PARENT;
      case ANAMNESIS_NUMBER_OF_SIBLINGS -> ProcedureProperty.ANAMNESIS_NUMBER_OF_SIBLINGS;
      case ANAMNESIS_PHYSIOTHERAPY -> ProcedureProperty.ANAMNESIS_PHYSIOTHERAPY;
      case ANAMNESIS_PRELIMINARY_COURSE -> ProcedureProperty.ANAMNESIS_PRELIMINARY_COURSE;
      case ANAMNESIS_SPEECH_THERAPY -> ProcedureProperty.ANAMNESIS_SPEECH_THERAPY;
      case ANAMNESIS_U_2 -> ProcedureProperty.ANAMNESIS_U_2;
      case ANAMNESIS_U_3 -> ProcedureProperty.ANAMNESIS_U_3;
      case ANAMNESIS_U_4 -> ProcedureProperty.ANAMNESIS_U_4;
      case ANAMNESIS_U_5 -> ProcedureProperty.ANAMNESIS_U_5;
      case ANAMNESIS_U_6 -> ProcedureProperty.ANAMNESIS_U_6;
      case ANAMNESIS_U_7 -> ProcedureProperty.ANAMNESIS_U_7;
      case ANAMNESIS_U_7_A -> ProcedureProperty.ANAMNESIS_U_7_A;
      case ANAMNESIS_U_8 -> ProcedureProperty.ANAMNESIS_U_8;
      case ANAMNESIS_U_9 -> ProcedureProperty.ANAMNESIS_U_9;
      case VACCINATION_STATUS_DIPHTHERIA -> ProcedureProperty.VACCINATION_STATUS_DIPHTHERIA;
      case VACCINATION_STATUS_HEPATITIS_A -> ProcedureProperty.VACCINATION_STATUS_HEPATITIS_A;
      case VACCINATION_STATUS_HEPATITIS_B -> ProcedureProperty.VACCINATION_STATUS_HEPATITIS_B;
      case VACCINATION_STATUS_HIB -> ProcedureProperty.VACCINATION_STATUS_HIB;
      case VACCINATION_STATUS_MENINGOCOCCUS_B ->
          ProcedureProperty.VACCINATION_STATUS_MENINGOCOCCUS_B;
      case VACCINATION_STATUS_MENINGOCOCCUS_C ->
          ProcedureProperty.VACCINATION_STATUS_MENINGOCOCCUS_C;
      case VACCINATION_STATUS_MMR -> ProcedureProperty.VACCINATION_STATUS_MMR;
      case VACCINATION_STATUS_PERKOMBI_HBV -> ProcedureProperty.VACCINATION_STATUS_PERKOMBI_HBV;
      case VACCINATION_STATUS_PERTUSSIS -> ProcedureProperty.VACCINATION_STATUS_PERTUSSIS;
      case VACCINATION_STATUS_PNEUMOCOCCUS -> ProcedureProperty.VACCINATION_STATUS_PNEUMOCOCCUS;
      case VACCINATION_STATUS_POLIO -> ProcedureProperty.VACCINATION_STATUS_POLIO;
      case VACCINATION_STATUS_ROTA -> ProcedureProperty.VACCINATION_STATUS_ROTA;
      case VACCINATION_STATUS_TBE -> ProcedureProperty.VACCINATION_STATUS_TBE;
      case VACCINATION_STATUS_TETANUS -> ProcedureProperty.VACCINATION_STATUS_TETANUS;
      case VACCINATION_STATUS_VACCINATION_SCHEME ->
          ProcedureProperty.VACCINATION_STATUS_VACCINATION_SCHEME;
      case VACCINATION_STATUS_VARICELLA -> ProcedureProperty.VACCINATION_STATUS_VARICELLA;
      case SOPESS_EXAMINATION_AUDITIVE_PROCESSING_RESULT ->
          ProcedureProperty.SOPESS_EXAMINATION_AUDITIVE_PROCESSING_RESULT;
      case SOPESS_EXAMINATION_COUNTING_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_COUNTING_POINTS;
      case SOPESS_EXAMINATION_FINE_MOTOR_SKILLS ->
          ProcedureProperty.SOPESS_EXAMINATION_FINE_MOTOR_SKILLS;
      case SOPESS_EXAMINATION_FORMATION_CH_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_FORMATION_CH_POINTS;
      case SOPESS_EXAMINATION_FORMATION_SCH_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_FORMATION_SCH_POINTS;
      case SOPESS_EXAMINATION_FORMATIONS_TR_DR_KR_GR_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_FORMATIONS_TR_DR_KR_GR_POINTS;
      case SOPESS_EXAMINATION_GROSS_MOTOR_SKILLS ->
          ProcedureProperty.SOPESS_EXAMINATION_GROSS_MOTOR_SKILLS;
      case SOPESS_EXAMINATION_JUMP_COUNT -> ProcedureProperty.SOPESS_EXAMINATION_JUMP_COUNT;
      case SOPESS_EXAMINATION_KNOWLEDGE_THINKING_RESULT ->
          ProcedureProperty.SOPESS_EXAMINATION_KNOWLEDGE_THINKING_RESULT;
      case SOPESS_EXAMINATION_LETTER_B_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_LETTER_B_POINTS;
      case SOPESS_EXAMINATION_LETTER_F_AND_FORMATION_PF_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_LETTER_F_AND_FORMATION_PF_POINTS;
      case SOPESS_EXAMINATION_LETTER_R_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_LETTER_R_POINTS;
      case SOPESS_EXAMINATION_LETTERS_G_AND_K_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_LETTERS_G_AND_K_POINTS;
      case SOPESS_EXAMINATION_LETTERS_L_AND_N_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_LETTERS_L_AND_N_POINTS;
      case SOPESS_EXAMINATION_LETTERS_S_AND_Z_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_LETTERS_S_AND_Z_POINTS;
      case SOPESS_EXAMINATION_LETTERS_T_AND_D_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_LETTERS_T_AND_D_POINTS;
      case SOPESS_EXAMINATION_PLURAL_POINTS -> ProcedureProperty.SOPESS_EXAMINATION_PLURAL_POINTS;
      case SOPESS_EXAMINATION_PREPOSITION_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_PREPOSITION_POINTS;
      case SOPESS_EXAMINATION_PRIMARY_LANGUAGE ->
          ProcedureProperty.SOPESS_EXAMINATION_PRIMARY_LANGUAGE;
      case SOPESS_EXAMINATION_PSEUDOWORD_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_PSEUDOWORD_POINTS;
      case SOPESS_EXAMINATION_PSYCHOLOGICAL_BEHAVIOR_RESULT ->
          ProcedureProperty.SOPESS_EXAMINATION_PSYCHOLOGICAL_BEHAVIOR_RESULT;
      case SOPESS_EXAMINATION_QUANTITY_KNOWLEDGE_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_QUANTITY_KNOWLEDGE_POINTS;
      case SOPESS_EXAMINATION_SELECTIVE_ATTENTION_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_SELECTIVE_ATTENTION_POINTS;
      case SOPESS_EXAMINATION_SPEECH_RESULT -> ProcedureProperty.SOPESS_EXAMINATION_SPEECH_RESULT;
      case SOPESS_EXAMINATION_VISUAL_PERCEPTION_POINTS ->
          ProcedureProperty.SOPESS_EXAMINATION_VISUAL_PERCEPTION_POINTS;
      case SOPESS_EXAMINATION_VISUAL_PERCEPTION_RESULT ->
          ProcedureProperty.SOPESS_EXAMINATION_VISUAL_PERCEPTION_RESULT;
      case SOPESS_EXAMINATION_VISUO_MOTOR -> ProcedureProperty.SOPESS_EXAMINATION_VISUO_MOTOR;
      case DEVELOPMENT_SCREENING_ABDOMEN -> ProcedureProperty.DEVELOPMENT_SCREENING_ABDOMEN;
      case DEVELOPMENT_SCREENING_ABDOMEN_RESULT ->
          ProcedureProperty.DEVELOPMENT_SCREENING_ABDOMEN_RESULT;
      case DEVELOPMENT_SCREENING_CHRONIC_DISEASE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_CHRONIC_DISEASE;
      case DEVELOPMENT_SCREENING_DIASTOLE -> ProcedureProperty.DEVELOPMENT_SCREENING_DIASTOLE;
      case DEVELOPMENT_SCREENING_DISABILITY -> ProcedureProperty.DEVELOPMENT_SCREENING_DISABILITY;
      case DEVELOPMENT_SCREENING_EAR_NOSE_THROAT ->
          ProcedureProperty.DEVELOPMENT_SCREENING_EAR_NOSE_THROAT;
      case DEVELOPMENT_SCREENING_EAR_NOSE_THROAT_RESULT ->
          ProcedureProperty.DEVELOPMENT_SCREENING_EAR_NOSE_THROAT_RESULT;
      case DEVELOPMENT_SCREENING_EAR_NOSE_THROAT_DOCTOR_LETTER ->
          ProcedureProperty.DEVELOPMENT_SCREENING_EAR_NOSE_THROAT_DOCTOR_LETTER;
      case DEVELOPMENT_SCREENING_NUTRITIONAL_CONDITION_RESULT ->
          ProcedureProperty.DEVELOPMENT_SCREENING_NUTRITIONAL_CONDITION_RESULT;
      case DEVELOPMENT_SCREENING_NUTRITIONAL_CONDITION_DOCTOR_LETTER ->
          ProcedureProperty.DEVELOPMENT_SCREENING_NUTRITIONAL_CONDITION_DOCTOR_LETTER;
      case DEVELOPMENT_SCREENING_RESPIRATORY_CARDIOVASCULAR_RESULT ->
          ProcedureProperty.DEVELOPMENT_SCREENING_RESPIRATORY_CARDIOVASCULAR_RESULT;
      case DEVELOPMENT_SCREENING_RESPIRATORY_CARDIOVASCULAR_DOCTOR_LETTER ->
          ProcedureProperty.DEVELOPMENT_SCREENING_RESPIRATORY_CARDIOVASCULAR_DOCTOR_LETTER;
      case DEVELOPMENT_SCREENING_NEUROLOGY_RESULT ->
          ProcedureProperty.DEVELOPMENT_SCREENING_NEUROLOGY_RESULT;
      case DEVELOPMENT_SCREENING_NEUROLOGY_DOCTOR_LETTER ->
          ProcedureProperty.DEVELOPMENT_SCREENING_NEUROLOGY_DOCTOR_LETTER;
      case DEVELOPMENT_SCREENING_SKIN_RESULT -> ProcedureProperty.DEVELOPMENT_SCREENING_SKIN_RESULT;
      case DEVELOPMENT_SCREENING_SKIN_DOCTOR_LETTER ->
          ProcedureProperty.DEVELOPMENT_SCREENING_SKIN_DOCTOR_LETTER;
      case DEVELOPMENT_SCREENING_MUSCULATURE_SKELETON_RESULT ->
          ProcedureProperty.DEVELOPMENT_SCREENING_MUSCULATURE_SKELETON_RESULT;
      case DEVELOPMENT_SCREENING_MUSCULATURE_SKELETON_DOCTOR_LETTER ->
          ProcedureProperty.DEVELOPMENT_SCREENING_MUSCULATURE_SKELETON_DOCTOR_LETTER;
      case DEVELOPMENT_SCREENING_METABOLISM_RESULT ->
          ProcedureProperty.DEVELOPMENT_SCREENING_METABOLISM_RESULT;
      case DEVELOPMENT_SCREENING_METABOLISM_DOCTOR_LETTER ->
          ProcedureProperty.DEVELOPMENT_SCREENING_METABOLISM_DOCTOR_LETTER;
      case DEVELOPMENT_SCREENING_EDUCATIONAL_ADVICE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_EDUCATIONAL_ADVICE;
      case DEVELOPMENT_SCREENING_EXTRA_EFFORT ->
          ProcedureProperty.DEVELOPMENT_SCREENING_EXTRA_EFFORT;
      case DEVELOPMENT_SCREENING_HEIGHT -> ProcedureProperty.DEVELOPMENT_SCREENING_HEIGHT;
      case DEVELOPMENT_SCREENING_INFO_LETTER -> ProcedureProperty.DEVELOPMENT_SCREENING_INFO_LETTER;
      case DEVELOPMENT_SCREENING_LANGUAGE_ADVICE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_LANGUAGE_ADVICE;
      case DEVELOPMENT_SCREENING_METABOLISM -> ProcedureProperty.DEVELOPMENT_SCREENING_METABOLISM;
      case DEVELOPMENT_SCREENING_MOTOR_PROMOTION ->
          ProcedureProperty.DEVELOPMENT_SCREENING_MOTOR_PROMOTION;
      case DEVELOPMENT_SCREENING_MUSCULATURE_SKELETON ->
          ProcedureProperty.DEVELOPMENT_SCREENING_MUSCULATURE_SKELETON;
      case DEVELOPMENT_SCREENING_NEUROLOGY -> ProcedureProperty.DEVELOPMENT_SCREENING_NEUROLOGY;
      case DEVELOPMENT_SCREENING_NUTRITIONAL_ADVICE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_NUTRITIONAL_ADVICE;
      case DEVELOPMENT_SCREENING_NUTRITIONAL_CONDITION ->
          ProcedureProperty.DEVELOPMENT_SCREENING_NUTRITIONAL_CONDITION;
      case DEVELOPMENT_SCREENING_OTHER_SUPPORT ->
          ProcedureProperty.DEVELOPMENT_SCREENING_OTHER_SUPPORT;
      case DEVELOPMENT_SCREENING_RE_INTRODUCTION ->
          ProcedureProperty.DEVELOPMENT_SCREENING_RE_INTRODUCTION;
      case DEVELOPMENT_SCREENING_RESPIRATORY_CARDIOVASCULAR ->
          ProcedureProperty.DEVELOPMENT_SCREENING_RESPIRATORY_CARDIOVASCULAR;
      case DEVELOPMENT_SCREENING_SCHOOL_COUNSELLING ->
          ProcedureProperty.DEVELOPMENT_SCREENING_SCHOOL_COUNSELLING;
      case DEVELOPMENT_SCREENING_SCHOOL_RECOMMENDATION ->
          ProcedureProperty.DEVELOPMENT_SCREENING_SCHOOL_RECOMMENDATION;
      case DEVELOPMENT_SCREENING_SKIN -> ProcedureProperty.DEVELOPMENT_SCREENING_SKIN;
      case DEVELOPMENT_SCREENING_SOCIAL_SERVICE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_SOCIAL_SERVICE;
      case DEVELOPMENT_SCREENING_SYSTOLE -> ProcedureProperty.DEVELOPMENT_SCREENING_SYSTOLE;
      case DEVELOPMENT_SCREENING_VACCINATION_ADVICE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_VACCINATION_ADVICE;
      case DEVELOPMENT_SCREENING_WEIGHT -> ProcedureProperty.DEVELOPMENT_SCREENING_WEIGHT;
      case HEARING_TEST_RIGHT_EAR -> ProcedureProperty.HEARING_TEST_RIGHT_EAR;
      case HEARING_TEST_LEFT_EAR -> ProcedureProperty.HEARING_TEST_LEFT_EAR;
      case HEARING_TEST_NOTE -> ProcedureProperty.HEARING_TEST_NOTE;
      case ANAMNESIS_ADDITIONAL_THERAPIES -> ProcedureProperty.ANAMNESIS_ADDITIONAL_THERAPIES;
      case ANAMNESIS_ALLERGIES -> ProcedureProperty.ANAMNESIS_ALLERGIES;
      case ANAMNESIS_CAN_SWIM -> ProcedureProperty.ANAMNESIS_CAN_SWIM;
      case ANAMNESIS_CHRONIC_ILLNESS_OR_DISABILITY_IN_FAMILY ->
          ProcedureProperty.ANAMNESIS_CHRONIC_ILLNESS_OR_DISABILITY_IN_FAMILY;
      case ANAMNESIS_CLUB_SPORT -> ProcedureProperty.ANAMNESIS_CLUB_SPORT;
      case ANAMNESIS_DAYCARE_NAME -> ProcedureProperty.ANAMNESIS_DAYCARE_NAME;
      case ANAMNESIS_DEVELOPMENT_CONSPICUITIES ->
          ProcedureProperty.ANAMNESIS_DEVELOPMENT_CONSPICUITIES;
      case ANAMNESIS_ERGO_THERAPY_END -> ProcedureProperty.ANAMNESIS_ERGO_THERAPY_END;
      case ANAMNESIS_ERGO_THERAPY_START -> ProcedureProperty.ANAMNESIS_ERGO_THERAPY_START;
      case ANAMNESIS_GESTATIONAL_AGE -> ProcedureProperty.ANAMNESIS_GESTATIONAL_AGE;
      case ANAMNESIS_MIGRATION_BACKGROUND -> ProcedureProperty.ANAMNESIS_MIGRATION_BACKGROUND;
      case ANAMNESIS_SEAHORSE_BADGE -> ProcedureProperty.ANAMNESIS_SEAHORSE_BADGE;
      case ANAMNESIS_HEARING_AID -> ProcedureProperty.ANAMNESIS_HEARING_AID;
      case ANAMNESIS_HEARING_IMPAIRMENT -> ProcedureProperty.ANAMNESIS_HEARING_IMPAIRMENT;
      case ANAMNESIS_HOSPITALIZATIONS_OR_OPERATIONS ->
          ProcedureProperty.ANAMNESIS_HOSPITALIZATIONS_OR_OPERATIONS;
      case ANAMNESIS_IN_DAYCARE_SINCE -> ProcedureProperty.ANAMNESIS_IN_DAYCARE_SINCE;
      case ANAMNESIS_INFANCY_CONSPICUITIES -> ProcedureProperty.ANAMNESIS_INFANCY_CONSPICUITIES;
      case ANAMNESIS_OTHER_INTERESTS -> ProcedureProperty.ANAMNESIS_OTHER_INTERESTS;
      case ANAMNESIS_PERSONAL_CONSPICUITIES -> ProcedureProperty.ANAMNESIS_PERSONAL_CONSPICUITIES;
      case ANAMNESIS_PHYSIO_THERAPY_END -> ProcedureProperty.ANAMNESIS_PHYSIO_THERAPY_END;
      case ANAMNESIS_PHYSIO_THERAPY_START -> ProcedureProperty.ANAMNESIS_PHYSIO_THERAPY_START;
      case ANAMNESIS_REGULAR_MEDICATION -> ProcedureProperty.ANAMNESIS_REGULAR_MEDICATION;
      case ANAMNESIS_RESPONSIBLE_PHYSICIAN -> ProcedureProperty.ANAMNESIS_RESPONSIBLE_PHYSICIAN;
      case ANAMNESIS_SCHOOL_NAME -> ProcedureProperty.ANAMNESIS_SCHOOL_NAME;
      case ANAMNESIS_SEVERE_ILLNESSES -> ProcedureProperty.ANAMNESIS_SEVERE_ILLNESSES;
      case ANAMNESIS_SIBLINGS_BIRTH_YEARS -> ProcedureProperty.ANAMNESIS_SIBLINGS_BIRTH_YEARS;
      case ANAMNESIS_SPECTACLES_IN_FAMILY -> ProcedureProperty.ANAMNESIS_SPECTACLES_IN_FAMILY;
      case ANAMNESIS_SPECTACLES_SINCE -> ProcedureProperty.ANAMNESIS_SPECTACLES_SINCE;
      case ANAMNESIS_SPEECH_IMPAIRMENT -> ProcedureProperty.ANAMNESIS_SPEECH_IMPAIRMENT;
      case ANAMNESIS_SPEECH_THERAPY_END -> ProcedureProperty.ANAMNESIS_SPEECH_THERAPY_END;
      case ANAMNESIS_SPEECH_THERAPY_START -> ProcedureProperty.ANAMNESIS_SPEECH_THERAPY_START;
      case ANAMNESIS_UNDER_MEDICAL_TREATMENT_FOR ->
          ProcedureProperty.ANAMNESIS_UNDER_MEDICAL_TREATMENT_FOR;
      case ANAMNESIS_VISION_IMPAIRMENT -> ProcedureProperty.ANAMNESIS_VISION_IMPAIRMENT;
      case ANAMNESIS_VISION_SCHOOL_SINCE -> ProcedureProperty.ANAMNESIS_VISION_SCHOOL_SINCE;
      case ANAMNESIS_WAS_IN_DAYCARE -> ProcedureProperty.ANAMNESIS_WAS_IN_DAYCARE;
      case ANAMNESIS_NOTE -> ProcedureProperty.ANAMNESIS_NOTE;
      case ANAMNESIS_LANGUAGE_SCREENING_CONSENT ->
          ProcedureProperty.ANAMNESIS_LANGUAGE_SCREENING_CONSENT;
      case ANAMNESIS_DAILY_TEETH_BRUSHING -> ProcedureProperty.ANAMNESIS_DAILY_TEETH_BRUSHING;
      case ANAMNESIS_TEETH_BRUSHING_AFTER_CARE ->
          ProcedureProperty.ANAMNESIS_TEETH_BRUSHING_AFTER_CARE;
      case ANAMNESIS_ELECTRIC_TOOTH_BRUSH -> ProcedureProperty.ANAMNESIS_ELECTRIC_TOOTH_BRUSH;
      case ANAMNESIS_FLUORIDE_TOOTH_PASTE -> ProcedureProperty.ANAMNESIS_FLUORIDE_TOOTH_PASTE;
      case ANAMNESIS_MEDIA_CONSUMPTION -> ProcedureProperty.ANAMNESIS_MEDIA_CONSUMPTION;
      case EYE_EXAMINATION_AMBLYOPIA -> ProcedureProperty.EYE_EXAMINATION_AMBLYOPIA;
      case EYE_EXAMINATION_ASTIGMATISM -> ProcedureProperty.EYE_EXAMINATION_ASTIGMATISM;
      case EYE_EXAMINATION_COLOR_VISION_DISORDER ->
          ProcedureProperty.EYE_EXAMINATION_COLOR_VISION_DISORDER;
      case EYE_EXAMINATION_HYPEROPIA -> ProcedureProperty.EYE_EXAMINATION_HYPEROPIA;
      case EYE_EXAMINATION_LEFT_EYE -> ProcedureProperty.EYE_EXAMINATION_LEFT_EYE;
      case EYE_EXAMINATION_MYOPIA -> ProcedureProperty.EYE_EXAMINATION_MYOPIA;
      case EYE_EXAMINATION_NOTE -> ProcedureProperty.EYE_EXAMINATION_NOTE;
      case EYE_EXAMINATION_OTHER_DIAGNOSIS -> ProcedureProperty.EYE_EXAMINATION_OTHER_DIAGNOSIS;
      case EYE_EXAMINATION_RIGHT_EYE -> ProcedureProperty.EYE_EXAMINATION_RIGHT_EYE;
      case EYE_EXAMINATION_STRABISMUS -> ProcedureProperty.EYE_EXAMINATION_STRABISMUS;
      case VACCINATION_STATUS_OTHER_VACCINATIONS ->
          ProcedureProperty.VACCINATION_STATUS_OTHER_VACCINATIONS;
      case VACCINATION_STATUS_VACCINATION_PASS_PRESENTED ->
          ProcedureProperty.VACCINATION_STATUS_VACCINATION_PASS_PRESENTED;
      case VACCINATION_STATUS_MEASLES_CONTRA_INDICATION ->
          ProcedureProperty.VACCINATION_STATUS_MEASLES_CONTRA_INDICATION;
      case VACCINATION_STATUS_MEASLES_CONTRA_INDICATION_IS_PERMANENT ->
          ProcedureProperty.VACCINATION_STATUS_MEASLES_CONTRA_INDICATION_IS_PERMANENT;
      case VACCINATION_STATUS_MEASLES_CONTRA_INDICATION_UNTIL ->
          ProcedureProperty.VACCINATION_STATUS_MEASLES_CONTRA_INDICATION_UNTIL;
      case SOPESS_EXAMINATION_DOCTOR_LETTER_AUDITIVE_PROCESSING ->
          ProcedureProperty.SOPESS_EXAMINATION_DOCTOR_LETTER_AUDITIVE_PROCESSING;
      case SOPESS_EXAMINATION_DOCTOR_LETTER_FINE_MOTOR_SKILLS ->
          ProcedureProperty.SOPESS_EXAMINATION_DOCTOR_LETTER_FINE_MOTOR_SKILLS;
      case SOPESS_EXAMINATION_DOCTOR_LETTER_GROSS_MOTOR_SKILLS ->
          ProcedureProperty.SOPESS_EXAMINATION_DOCTOR_LETTER_GROSS_MOTOR_SKILLS;
      case SOPESS_EXAMINATION_DOCTOR_LETTER_KNOWLEDGE_THINKING ->
          ProcedureProperty.SOPESS_EXAMINATION_DOCTOR_LETTER_KNOWLEDGE_THINKING;
      case SOPESS_EXAMINATION_DOCTOR_LETTER_PSYCHOLOGICAL_BEHAVIOR ->
          ProcedureProperty.SOPESS_EXAMINATION_DOCTOR_LETTER_PSYCHOLOGICAL_BEHAVIOR;
      case SOPESS_EXAMINATION_DOCTOR_LETTER_SPEECH ->
          ProcedureProperty.SOPESS_EXAMINATION_DOCTOR_LETTER_SPEECH;
      case SOPESS_EXAMINATION_DOCTOR_LETTER_VISUAL_PERCEPTION ->
          ProcedureProperty.SOPESS_EXAMINATION_DOCTOR_LETTER_VISUAL_PERCEPTION;
      case SOPESS_EXAMINATION_FAMILY_LANGUAGE ->
          ProcedureProperty.SOPESS_EXAMINATION_FAMILY_LANGUAGE;
      case SOPESS_EXAMINATION_GERMAN_KNOWLEDGE_CHILD ->
          ProcedureProperty.SOPESS_EXAMINATION_GERMAN_KNOWLEDGE_CHILD;
      case SOPESS_EXAMINATION_GERMAN_KNOWLEDGE_PRIMARY_CARER ->
          ProcedureProperty.SOPESS_EXAMINATION_GERMAN_KNOWLEDGE_PRIMARY_CARER;
      case SOPESS_EXAMINATION_IN_GERMANY_SINCE ->
          ProcedureProperty.SOPESS_EXAMINATION_IN_GERMANY_SINCE;
      case SOPESS_EXAMINATION_HANDEDNESS_VALUE ->
          ProcedureProperty.SOPESS_EXAMINATION_HANDEDNESS_VALUE;
      case SOPESS_EXAMINATION_NOTE -> ProcedureProperty.SOPESS_EXAMINATION_NOTE;
      case DEVELOPMENT_SCREENING_BMI -> ProcedureProperty.DEVELOPMENT_SCREENING_BMI;
      case DEVELOPMENT_SCREENING_BMI_PERCENTILE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_BMI_PERCENTILE;
      case DEVELOPMENT_SCREENING_ABDOMEN_DOCTOR_LETTER ->
          ProcedureProperty.DEVELOPMENT_SCREENING_ABDOMEN_DOCTOR_LETTER;
      case DEVELOPMENT_SCREENING_DISABILITY_TYPE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_DISABILITY_TYPE;
      case DEVELOPMENT_SCREENING_FAMILY -> ProcedureProperty.DEVELOPMENT_SCREENING_FAMILY;
      case DEVELOPMENT_SCREENING_HANDICAP_NOTE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_HANDICAP_NOTE;
      case DEVELOPMENT_SCREENING_HEIGHT_PERCENTILE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_HEIGHT_PERCENTILE;
      case DEVELOPMENT_SCREENING_MIGRATION -> ProcedureProperty.DEVELOPMENT_SCREENING_MIGRATION;
      case DEVELOPMENT_SCREENING_NON_COMPLIANCE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_NON_COMPLIANCE;
      case DEVELOPMENT_SCREENING_OTHER_RISK -> ProcedureProperty.DEVELOPMENT_SCREENING_OTHER_RISK;
      case DEVELOPMENT_SCREENING_PHYSICAL_EXAMINATION_NOTE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_PHYSICAL_EXAMINATION_NOTE;
      case DEVELOPMENT_SCREENING_SCHOOL_FEEDBACK ->
          ProcedureProperty.DEVELOPMENT_SCREENING_SCHOOL_FEEDBACK;
      case DEVELOPMENT_SCREENING_SOCIAL -> ProcedureProperty.DEVELOPMENT_SCREENING_SOCIAL;
      case DEVELOPMENT_SCREENING_WEIGHT_PERCENTILE ->
          ProcedureProperty.DEVELOPMENT_SCREENING_WEIGHT_PERCENTILE;
      case VACCINATION_STATUS_NOTE -> ProcedureProperty.VACCINATION_STATUS_NOTE;
      case SCHOOL_ID -> ProcedureProperty.SCHOOL_ID;
      case SCHOOL_YEAR -> ProcedureProperty.SCHOOL_YEAR;
      case APPOINTMENT -> ProcedureProperty.APPOINTMENT;
      case EXAMINATION_DATE -> ProcedureProperty.EXAMINATION_DATE;
      case HEARING_TEST_EXAMINATION_RESULT_DOCTOR_LETTER ->
          ProcedureProperty.HEARING_TEST_EXAMINATION_RESULT_DOCTOR_LETTER;
      case EYE_EXAMINATION_EYE_EXAMINATION_DOCTOR_LETTER ->
          ProcedureProperty.EYE_EXAMINATION_EYE_EXAMINATION_DOCTOR_LETTER;
      case EYE_EXAMINATION_ISHIHARA_EXAMINATION_DOCTOR_LETTER ->
          ProcedureProperty.EYE_EXAMINATION_ISHIHARA_EXAMINATION_DOCTOR_LETTER;
      case EYE_EXAMINATION_LANG_EXAMINATION_DOCTOR_LETTER ->
          ProcedureProperty.EYE_EXAMINATION_LANG_EXAMINATION_DOCTOR_LETTER;
      case DEVELOPMENT_SCREENING_CHRONIC_DISEASE_RESULT ->
          ProcedureProperty.DEVELOPMENT_SCREENING_CHRONIC_DISEASE_RESULT;
      case DEVELOPMENT_SCREENING_CHRONIC_DISEASE_ICD10 ->
          ProcedureProperty.DEVELOPMENT_SCREENING_CHRONIC_DISEASE_ICD10;
      case DEVELOPMENT_SCREENING_DISABILITY_RESULT ->
          ProcedureProperty.DEVELOPMENT_SCREENING_DISABILITY_RESULT;
      case DEVELOPMENT_SCREENING_DISABILITY_ICD10 ->
          ProcedureProperty.DEVELOPMENT_SCREENING_DISABILITY_ICD10;
    };
  }
}
