plugins {
    id 'eshg.java-lib'
}

dependencies {
    api project(':lib-commons')
    api project(':test-helper-commons-api')
    api project(':api-commons')

    api 'org.springframework:spring-webmvc'
    api 'org.springframework.security:spring-security-core'
    implementation 'jakarta.servlet:jakarta.servlet-api'

    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'jakarta.servlet:jakarta.servlet-api'
    implementation 'org.springdoc:springdoc-openapi-starter-common:2.6.0' // Pinned to workaround https://github.com/springdoc/springdoc-openapi/issues/2776
}


