# Note: Unfortunately we cannot set the logging level here (logging.level.org.zalando.logbook=TRACE)
# See https://docs.spring.io/spring-boot/docs/3.2.1/reference/html/features.html#features.logging.custom-log-configuration
logbook.format.style=http
logbook.predicate.exclude[0].path=/actuator/health
logbook.predicate.exclude[1].path=/actuator/prometheus

logbook.filter.enabled=false
logbook.secure-filter.enabled=false
