### Login
POST http://localhost:8008/_matrix/client/r0/login
Accept: application/json
Content-Type: application/json

{
  "type":"m.login.password",
  "user": "testuser1",
  "password": "password"
}

### get 3pid
GET http://localhost:8008/_matrix/client/v3/account/3pid
Accept: application/json
Content-Type: application/json
Authorization: Bearer [SYNAPSE_ACCESS_TOKEN]


#### send 3pid
POST http://localhost:8008/_matrix/client/v3/account/3pid/email/requestToken
Accept: application/json
Content-Type: application/json
Authorization: Bearer [SYNAPSE_ACCESS_TOKEN]

{
  "client_secret": "random_uuid_string_asdfgasdf",
  "email": "user@example.com",
  "send_attempt": 1,
  "next_link": null
}

### Now, go to maildev http://localhost:1080/ and click confirmation link in new email message


### bind 3pid - first call to get the session
POST http://localhost:8008/_matrix/client/v3/account/3pid/add
Accept: application/json
Content-Type: application/json
Authorization: Bearer [SYNAPSE_ACCESS_TOKEN]

{
  "sid": "[SID_FROM_REQUEST_TOKEN_REQUEST]",
  "client_secret": "random_uuid_string_asdfgasdf"
}


### bind 3pid - second call with session AND mandatory auth credentials (username + password)
POST http://localhost:8008/_matrix/client/v3/account/3pid/add
Accept: application/json
Content-Type: application/json
Authorization: Bearer [SYNAPSE_ACCESS_TOKEN]

{
  "sid": "WxKSyBqxERgADHKs",
  "client_secret": "random_uuid_string_asdfgasdf",
  "auth": {
    "type": "m.login.password",
    "user": "testuser1",
    "password": "password",
    "session": "[SESSION_FROM_PREVIOUS_BIND_3PID_REQUEST]"
  }
}


### check if email was added to 3pids
GET http://localhost:8008/_matrix/client/v3/account/3pid
Accept: application/json
Content-Type: application/json
Authorization: Bearer [SYNAPSE_ACCESS_TOKEN]


