### Login as admin

POST http://localhost:8008/_matrix/client/r0/login
Accept: application/json
Content-Type: application/json

{
  "type":"m.login.password",
  "user": "admin",
  "password": "admin"
}


### Allow replacing master cross-signing key without User-Interactive Auth (for next 10 minutes)

POST http://localhost:8008/_synapse/admin/v1/users/@testuser1:synapse.local.dev/_allow_cross_signing_replacement_without_uia
Accept: application/json
Content-Type: application/json
Authorization: Bearer [SYNAPSE_ACCESS_TOKEN]


### Delete room
DELETE http://localhost:8008/_synapse/admin/v1/rooms/%21nUdhTpOnqvcglhLhGG%3Asynapse.local.dev
Accept: application/json
Content-Type: application/json
Authorization: Bearer [SYNAPSE_ACCESS_TOKEN]

{
  "purge": true,
  "force_purge": true,
  "block": true
}

### Find user in user_directory
POST http://localhost:8008/_matrix/client/v3/user_directory/search
Accept: application/json
Content-Type: application/json
Authorization: Bearer [SYNAPSE_ACCESS_TOKEN]

{
"limit": 10,
"search_term":"synapse.local.dev"
}

### Get user details
GET  http://localhost:8008/_synapse/admin/v2/users/%40testuser1%3Asynapse.local.dev
Accept: application/json
Content-Type: application/json
Authorization: Bearer [SYNAPSE_ACCESS_TOKEN]
