### Login
POST http://localhost:8008/_matrix/client/r0/login
Accept: application/json
Content-Type: application/json

{
  "type":"m.login.password",
  "user": "testuser1",
  "password": "password"
}


### Deactivate account
POST http://localhost:8008/_matrix/client/v3/account/deactivate
Accept: application/json
Content-Type: application/json
Authorization: Bearer [ACCESS_TOKEN]

{
  "auth": {
    "type": "m.login.password",
    "user": "testuser1",
    "password": "password"
  }
}


### Try to login to check if user does not exist anymore
POST http://localhost:8008/_matrix/client/r0/login
Accept: application/json
Content-Type: application/json

{
  "type":"m.login.password",
  "user": "testuser1",
  "password": "password"
}
