### Login with username and password to obtain AccessToken
POST http://localhost:8008/_matrix/client/r0/login
Accept: application/json
Content-Type: application/json

{
  "type":"m.login.password",
  "user": "testuser1",
  "password": "password"
}

### Get whoami user data (requires Authorization)
GET http://localhost:8008/_matrix/client/v3/account/whoami
Accept: application/json
Content-Type: application/json
Authorization: Bearer <SYNAPSE_ACCESS_TOKEN>

