/*
 * Copyright 2026 cronn GmbH
 * SPDX-License-Identifier: Apache-2.0
 */

package de.eshg.config;

public enum ConfigurationEndpoint {
  PRIVACY_POLICY,
  PRIVACY_NOTICE,
  OPENING_HOURS,
  DEPARTMENT_INFO,
  SCHOOL_ENTRY,
  DEVICE_REGISTRY,
  MEASLES_PROTECTION_APPOINTMENT_STANDARD_DURATION,
  OMS_APPOINTMENT_STANDARD_DURATION,
  SCHOOL_ENTRY_APPOINTMENT_STANDARD_DURATION,
  SEX_WORK_APPOINTMENT_STANDARD_DURATION,
  HIV_STI_CONSULTATION_APPOINTMENT_STANDARD_DURATION,
  TRAVEL_MEDICINE_APPOINTMENT_STANDARD_DURATION,
  MEDS_ABROAD_APPOINTMENT_STANDARD_DURATION,
  PROSTITUTE_PROTECTION_APPOINTMENT_STANDARD_DURATION,
  INFECTION_BRIEFING_APPOINTMENT_STANDARD_DURATION,
  OFFICIAL_MEDICAL_SERVICE,
  INSPECTION,
  APPOINTMENT_BLOCK_AVAILABILITY,
}
