de.eshg.department-info.name=Gesundheitsamt Schwalm-Eder-Kreis
de.eshg.department-info.abbreviation=GA SEK
de.eshg.department-info.street=Behördenzentrum - Hans-Scholl-Straße
de.eshg.department-info.house-number=5
de.eshg.department-info.postal-code=34576
de.eshg.department-info.city=Homberg (Efze)
de.eshg.department-info.country=DE
de.eshg.department-info.phone-number=+49 5681 775 7553
de.eshg.department-info.homepage=schwalm-eder-kreis.de/gesundheit
de.eshg.department-info.email=gesundheitswesen@schwalm-eder-kreis.de
de.eshg.department-info.latitude=51.017505
de.eshg.department-info.longitude=9.412242

de.eshg.department-info.privacy-policy=classpath:health-department-sek/privacy_policy_sek.pdf

eshg.department.logo=classpath:health-department-sek/logo-health-department-sek.svg
eshg.department.municipality-directory=classpath:health-department-sek/municipality-directory-sek.csv
eshg.department.street-directory=classpath:health-department-sek/strassenverzeichnis-sek.csv

eshg.department.citizen-portal-accessibility-statement-markdown-de=classpath:health-department-sek/citizen/accessibility.md
eshg.department.imprint-markdown-de=classpath:health-department-sek/citizen/imprint.md
eshg.department.citizen-portal-privacy-policy-markdown-de=classpath:health-department-sek/citizen/privacy.md

eshg.department.employee-portal-accessibility-statement-markdown-de=classpath:health-department-sek/employee/accessibility.md
eshg.department.contact-markdown-de=classpath:health-department-sek/employee/contact.md
eshg.department.employee-portal-privacy-policy-markdown-de=classpath:health-department-sek/employee/privacy.md

eshg.department.acknowledgements-markdown-de=classpath:health-department-sek/acknowledgements.md
