# **************************************************************************************** #
#    Make sure any health-department specific configuration is present in the database     #
#                    See de.eshg.config.EshgConfigurationService                           #
#                                                                                          #
#                      !!! These properties are only defaults !!!                          #
#  !!! Changes and new properties will not be migrated to already populated databases !!!  #
#             !!! All changes need database migrations via liquibase !!!                   #
# **************************************************************************************** #

de.eshg.department-info.name=Gesundheitsamt Stadt Frankfurt am Main
de.eshg.department-info.abbreviation=FFM
de.eshg.department-info.street=Breite Gasse
de.eshg.department-info.house-number=28
de.eshg.department-info.postal-code=60313
de.eshg.department-info.city=Frankfurt am Main
de.eshg.department-info.country=DE
de.eshg.department-info.phone-number=+49 69 212 33970
de.eshg.department-info.homepage=gesundheitsamt.stadt-frankfurt.de
de.eshg.department-info.email=info.gesundheitsamt@stadt-frankfurt.de
de.eshg.department-info.latitude=50.114296
de.eshg.department-info.longitude=8.691828

de.eshg.department-info.privacy-notice=classpath:privacy_notice.pdf
de.eshg.department-info.privacy-policy=classpath:privacy_policy.pdf

eshg.department.logo=classpath:logo-health-department-ffm.svg
eshg.department.security-txt=classpath:security-ffm.txt
eshg.department.security-txt-public-key=classpath:security-pgp-key-ffm.txt
eshg.department.street-directory=classpath:strassenverzeichnis2022.csv
eshg.department.municipality-directory=classpath:municipality-directory-ffm.csv

# **************************************************************************************** #
#    Make sure any health-department specific configuration is present in the database     #
#                    See de.eshg.config.EshgConfigurationService                           #
#                                                                                          #
#                      !!! These properties are only defaults !!!                          #
#  !!! Changes and new properties will not be migrated to already populated databases !!!  #
#             !!! All changes need database migrations via liquibase !!!                   #
# **************************************************************************************** #