spring.config.import=classpath:application-health-department-frankfurt.properties

eshg.mail.noreply=noreply@stadt-frankfurt.de
eshg.keycloak.admin-client.client-secret=admin
eshg.keycloak.employee-realm.auth-client-secret=jPKtsvmKqRqsscNnN7NMVFhmf3b9NH
eshg.keycloak.citizen-realm.auth-client-secret=tstj3RgLtqF4Kbh3hVNRRXTwxLkhmq
