de.eshg.business-modules.clients[INSPECTION].url=http://localhost:${server.port:8080}/simulator/inspection
de.eshg.business-modules.clients[SCHOOL_ENTRY].url=http://localhost:${server.port:8080}/simulator/school-entry
