eshg.keycloak.test-client-enabled=true
eshg.keycloak.provision-test-users=true
eshg.keycloak.allow-passwords-for-employees=true
eshg.keycloak.bootstrap-admin.keep-enabled=true
eshg.keycloak.setup-admin.enabled=false
eshg.keycloak.citizen-realm.sslRequired=false
eshg.keycloak.employee-realm.sslRequired=false
eshg.keycloak.employee-realm.module-client-secrets.auditlog=password
eshg.keycloak.employee-realm.module-client-secrets.base=password
eshg.keycloak.employee-realm.module-client-secrets.chat-management=password
eshg.keycloak.employee-realm.module-client-secrets.citizen-auth=password
eshg.keycloak.employee-realm.module-client-secrets.employee-auth=password
eshg.keycloak.employee-realm.module-client-secrets.inspection=password
eshg.keycloak.employee-realm.module-client-secrets.local-service-directory=password
eshg.keycloak.employee-realm.module-client-secrets.measles-protection=password
eshg.keycloak.employee-realm.module-client-secrets.school-entry=password
eshg.keycloak.employee-realm.module-client-secrets.statistics=password
eshg.keycloak.employee-realm.module-client-secrets.travel-medicine=password
eshg.keycloak.employee-realm.module-client-secrets.sti-protection=password
eshg.keycloak.employee-realm.module-client-secrets.medical-registry=password
eshg.keycloak.employee-realm.module-client-secrets.dental=password
eshg.keycloak.employee-realm.module-client-secrets.official-medical-service=password
eshg.keycloak.employee-realm.module-client-secrets.opendata=password
eshg.keycloak.employee-realm.module-client-secrets.meds-abroad=password
eshg.keycloak.employee-realm.module-client-secrets.prostitute-protection=password
eshg.keycloak.employee-realm.module-client-secrets.infection-briefing=password
eshg.keycloak.employee-realm.module-client-secrets.file-jockey=password
eshg.muk.profile=test
eshg.bund-id.profile=test
de.eshg.base.user.schedule=-
de.eshg.central-file-deletion-service.schedule=-
eshg.base.auditlog.notification.schedule=-
eshg.gdpr.cleanup.cron = -
