de.eshg.department-info.name=Gesundheitsamt Wiesbaden
de.eshg.department-info.abbreviation=WI
de.eshg.department-info.street=Konradinerallee
de.eshg.department-info.house-number=11
de.eshg.department-info.postal-code=65189
de.eshg.department-info.city=Wiesbaden
de.eshg.department-info.country=DE
de.eshg.department-info.phone-number=+49 611 31 2817
de.eshg.department-info.homepage=wiesbaden.de/vv/oe/04/53/Gesundheitsamt
de.eshg.department-info.email=gesundheitsamt@wiesbaden.de
de.eshg.department-info.latitude= 50.0635283
de.eshg.department-info.longitude=8.2540751

de.eshg.department-info.privacy-policy=classpath:health-department-wiesbaden/privacy_policy_wiesbaden.pdf

eshg.department.logo=classpath:health-department-wiesbaden/logo-health-department-wiesbaden.svg
eshg.department.municipality-directory=classpath:health-department-wiesbaden/municipality-directory-wiesbaden.csv
eshg.department.street-directory=classpath:health-department-wiesbaden/strassenverzeichnis-wiesbaden.csv

eshg.department.citizen-portal-accessibility-statement-markdown-de=classpath:health-department-wiesbaden/citizen/accessibility.md
eshg.department.imprint-markdown-de=classpath:health-department-wiesbaden/citizen/imprint.md
eshg.department.citizen-portal-privacy-policy-markdown-de=classpath:health-department-wiesbaden/citizen/privacy.md

eshg.department.employee-portal-accessibility-statement-markdown-de=classpath:health-department-wiesbaden/employee/accessibility.md
eshg.department.contact-markdown-de=classpath:health-department-wiesbaden/employee/contact.md
eshg.department.employee-portal-privacy-policy-markdown-de=classpath:health-department-wiesbaden/employee/privacy.md

eshg.department.acknowledgements-markdown-de=classpath:health-department-wiesbaden/acknowledgements.md
