spring.application.name=eshg-backend-base
spring.datasource.url=jdbc:postgresql://localhost:5433/eshgbase
spring.datasource.username=testuser
spring.datasource.password=testpassword
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true

# Enable explicitly since we disable it by default via common-persistence.properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migrations/changelog.xml

spring.jackson.serialization.indent_output=true
spring.mail.host=${DOCKER_HOSTNAME:localhost}
spring.mail.port=1025
spring.mail.username=testuser
spring.mail.password=testpassword
#Socket connection timeout, implemented by java.net.Socket
spring.mail.properties.mail.smtp.connectiontimeout=5000
#Socket read timeout, implemented by java.net.Socket
spring.mail.properties.mail.smtp.timeout=3000
#Socket write timeout, implemented by java.util.concurrent.ScheduledExecutorService
#Overhead of one thread per connection
spring.mail.properties.mail.smtp.writetimeout=5000
eshg.employee-portal.reverse-proxy.url=http://localhost:4000
eshg.citizen-portal.reverse-proxy.url=http://localhost:4001
eshg.keycloak.employee-realm.name=eshg
eshg.keycloak.employee-realm.display-name=GA-Lotse
eshg.keycloak.employee-realm.sslRequired=true
eshg.keycloak.citizen-realm.name=citizens
eshg.keycloak.citizen-realm.display-name=Online-Portal
eshg.keycloak.citizen-realm.muk-idp.signature-algorithm=RSA_SHA256_MGF1
eshg.keycloak.citizen-realm.muk-idp.encryption-algorithm=RSA-OAEP
eshg.keycloak.citizen-realm.bund-id-idp.signature-algorithm=RSA_SHA256_MGF1
eshg.keycloak.citizen-realm.bund-id-idp.encryption-algorithm=RSA-OAEP
eshg.keycloak.smtp.from=${eshg.mail.noreply}
eshg.keycloak.smtp.host=maildev
eshg.keycloak.smtp.port=1025
eshg.keycloak.smtp.ssl-enabled=false
eshg.keycloak.smtp.start-tls=false
eshg.keycloak.smtp.username=testuser
eshg.keycloak.smtp.password=testpassword
eshg.keycloak.bootstrap-admin.user=admin
eshg.keycloak.bootstrap-admin.password=admin
eshg.keycloak.bootstrap-admin.keep-enabled=false
eshg.keycloak.admin-client.client-id=ga-lotse-base
eshg.keycloak.setup-admin.enabled=false
eshg.keycloak.setup-admin.email-lifetime=3d
eshg.keycloak.event-expiration=90d
# Keep this setting in sync with "spring.session.timeout" of the "auth" module
# Note that the Keycloak session timeout needs to be higher than the session timeout, because:
# sessions are kept in Redis and do not expire immediately. Redis removes sessions in an adaptive background process.
eshg.keycloak.session-timeout=35m
eshg.keycloak.admin-session-timeout=5m
eshg.keycloak.admin-session-limit=1h
eshg.keycloak.provision-test-users=false
eshg.keycloak.allow-passwords-for-employees=false

eshg.rate-limit.suggest-users.capacity=10
eshg.rate-limit.suggest-users.reset-interval=1h

spring.security.oauth2.client.registration.module-client.client-id=system-base
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

logging.level.org.zalando.logbook=TRACE
eshg.servicedirectory.baseUrl=http://localhost:8083
de.eshg.envers.auditing.enabled=true
eshg.population.default-number-of-entities-to-populate.resource=15
eshg.population.default-number-of-entities-to-populate.inventory-item=15
eshg.population.default-number-of-entities-to-populate.contact=30

de.eshg.department-info.privacy-notice=classpath:default-documents/privacy_notice.pdf
de.eshg.department-info.privacy-policy=classpath:default-documents/privacy_policy.pdf

de.eshg.department-info.name=Gesundheitsamt
de.eshg.department-info.abbreviation=GA
de.eshg.department-info.street=Straﬂe
de.eshg.department-info.house-number=1
de.eshg.department-info.postal-code=12345
de.eshg.department-info.city=Stadt
de.eshg.department-info.country=DE
de.eshg.department-info.phone-number=+49 69 9000 9123
de.eshg.department-info.homepage=ga-lotse.de
de.eshg.department-info.email=no-reply@ga-lotse.de
de.eshg.department-info.latitude=50.114296
de.eshg.department-info.longitude=8.691828

eshg.department.logo=classpath:logo-ga-lotse.svg
eshg.department.street-directory=classpath:strassenverzeichnis.csv
eshg.department.municipality-directory=classpath:municipality-directory.csv

eshg.department.citizen-portal-accessibility-statement-markdown-de=classpath:default-documents/accessibility.md
eshg.department.employee-portal-accessibility-statement-markdown-de=classpath:default-documents/accessibility.md
eshg.department.acknowledgements-markdown-de=classpath:default-documents/acknowledgements.md
eshg.department.contact-markdown-de=classpath:default-documents/contact.md
eshg.department.imprint-markdown-de=classpath:default-documents/imprint.md
eshg.department.citizen-portal-privacy-policy-markdown-de=classpath:default-documents/privacy_policy.md
eshg.department.employee-portal-privacy-policy-markdown-de=classpath:default-documents/privacy_policy.md

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

eshg.gdpr.cleanup.cron = 0 0 2 * * ?

eshg.department.security-txt=classpath:security.txt
eshg.department.security-txt-public-key=classpath:security-pgp-key.txt

de.eshg.base.svg-sanitizer-base-url=http://${DOCKER_HOSTNAME:localhost}:8101
de.eshg.base.is-open-data-enabled=true
