eshg.department.name=Gesundheitsamt Stadt Frankfurt am Main
eshg.department.abbreviation=FFM
eshg.department.street=Breite Gasse
eshg.department.house-number=28
eshg.department.postal-code=60313
eshg.department.city=Frankfurt am Main
eshg.department.country=DE
eshg.department.phone-number=+49 69 212 33970
eshg.department.homepage=gesundheitsamt.stadt-frankfurt.de
eshg.department.email=info.gesundheitsamt@stadt-frankfurt.de
eshg.department.latitude=50.114296
eshg.department.longitude=8.691828
eshg.department.logo=classpath:logo-health-department-ffm.svg
eshg.department.security-txt=classpath:security-ffm.txt
eshg.department.security-txt-public-key=classpath:security-pgp-key-ffm.txt
eshg.department.street-directory=classpath:strassenverzeichnis2022.csv
eshg.department.municipality-directory=classpath:municipality-directory-ffm.csv
eshg.base.auditlog.minimal-configured-auditlog-keys=3
