de.eshg.department-info.name=Gesundheitsamt des Odenwaldkreises
de.eshg.department-info.abbreviation=ERB
de.eshg.department-info.street=Michelstädter Str.
de.eshg.department-info.house-number=12
de.eshg.department-info.postal-code=64711
de.eshg.department-info.city=Erbach
de.eshg.department-info.country=DE
de.eshg.department-info.phone-number=+49 6062 6014 6100
de.eshg.department-info.homepage=odenwaldkreis.de/de/dienstleistungen/gesundheit/
de.eshg.department-info.email=gesundheitsamt@odenwaldkreis.de
de.eshg.department-info.latitude=49.66309278283559
de.eshg.department-info.longitude=8.99425264276203

de.eshg.department-info.privacy-policy=classpath:health-department-odenwaldkreis/privacy_policy_odenwaldkreis.pdf

eshg.department.logo=classpath:health-department-odenwaldkreis/logo-health-department-odenwaldkreis.svg
eshg.department.street-directory=classpath:health-department-odenwaldkreis/strassenverzeichnis-odw.csv
eshg.department.municipality-directory=classpath:health-department-odenwaldkreis/municipality-directory-odenwaldkreis.csv

eshg.department.citizen-portal-accessibility-statement-markdown-de=classpath:health-department-odenwaldkreis/citizen/accessibility.md
eshg.department.imprint-markdown-de=classpath:health-department-odenwaldkreis/citizen/imprint.md
eshg.department.citizen-portal-privacy-policy-markdown-de=classpath:health-department-odenwaldkreis/citizen/privacy.md

eshg.department.employee-portal-accessibility-statement-markdown-de=classpath:health-department-odenwaldkreis/employee/accessibility.md
eshg.department.contact-markdown-de=classpath:health-department-odenwaldkreis/employee/contact.md
eshg.department.employee-portal-privacy-policy-markdown-de=classpath:health-department-odenwaldkreis/employee/privacy.md

eshg.department.acknowledgements-markdown-de=classpath:health-department-odenwaldkreis/acknowledgements.md
