de.eshg.business-modules.clients[0].type=INSPECTION
de.eshg.business-modules.clients[0].url=http://localhost:${server.port:8080}/simulator/inspection
de.eshg.business-modules.clients[1].type=SCHOOL_ENTRY
de.eshg.business-modules.clients[1].url=http://localhost:${server.port:8080}/simulator/school-entry
