spring.datasource.url=jdbc:postgresql://localhost:5445/sti_protection
spring.datasource.username=testuser
spring.datasource.password=testpassword
spring.jpa.hibernate.ddl-auto=create
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:/migrations/changelog.xml

# The port should match the one specified in the configuration annotated with @OpenAPIDefinition.
server.port=8095

logging.level.org.zalando.logbook=TRACE

spring.security.oauth2.client.registration.module-client.client-id=system-sti-protection
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[HIV_STI_CONSULTATION]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[SEX_WORK]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[RESULTS_REVIEW]=30m

eshg.population.default-number-of-entities-to-populate.sti-protection-procedure=30
eshg.population.default-number-of-entities-to-populate.text-template-dto=30
eshg.population.default-number-of-entities-to-populate.appointment-block-group=0

eshg.sti-protection.overdue-procedures.cron=0 0 1 * * *
eshg.sti-protection.overdue-procedures.overdue-days=180

de.eshg.sti-protection.medical-history.consultation-de-location=classpath:templates/documents/medical_history_consultation_printable_de.pdf
de.eshg.sti-protection.medical-history.consultation-en-location=classpath:templates/documents/medical_history_consultation_printable_en.pdf
de.eshg.sti-protection.medical-history.sexwork-de-location=classpath:templates/documents/medical_history_sexwork_printable_de.pdf
de.eshg.sti-protection.medical-history.sexwork-en-location=classpath:templates/documents/medical_history_sexwork_printable_en.pdf
