spring.datasource.url=jdbc:postgresql://localhost:5445/sti_protection
spring.datasource.username=testuser
spring.datasource.password=testpassword
spring.jpa.hibernate.ddl-auto=create
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:/migrations/changelog.xml

# The port should match the one specified in the configuration annotated with @OpenAPIDefinition.
server.port=8095

logging.level.org.zalando.logbook=TRACE

spring.security.oauth2.client.registration.module-client.client-id=system-sti-protection
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[HIV_STI_CONSULTATION]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[SEX_WORK]=30m
de.eshg.lib.appointmentblock.defaultAppointmentTypeConfiguration[RESULTS_REVIEW]=30m

eshg.population.default-number-of-entities-to-populate.sti-protection-procedure=30
eshg.population.default-number-of-entities-to-populate.text-template-dto=30
eshg.population.default-number-of-entities-to-populate.appointment-block-group=0

eshg.sti-protection.overdue-procedures.cron=0 0 1 * * *
eshg.sti-protection.overdue-procedures.overdue-duration=180d

eshg.sti-protection.unconfirmed-appointments.cron=@hourly
# https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.conversion.durations
eshg.sti-protection.unconfirmed-appointments.expire-after=1h

de.eshg.sti-protection.medical-history.consultation-de-location=classpath:templates/documents/medical_history_consultation_printable_de.pdf
de.eshg.sti-protection.medical-history.consultation-en-location=classpath:templates/documents/medical_history_consultation_printable_en.pdf
de.eshg.sti-protection.medical-history.sexwork-de-location=classpath:templates/documents/medical_history_sexwork_printable_de.pdf
de.eshg.sti-protection.medical-history.sexwork-en-location=classpath:templates/documents/medical_history_sexwork_printable_en.pdf

de.eshg.sti-protection.department-info.hiv_sti_consultation.use-department-info-from-base-module=false
de.eshg.sti-protection.department-info.hiv_sti_consultation.name=HIV/STI - Beratung
de.eshg.sti-protection.department-info.hiv_sti_consultation.abbreviation=HIV-STI-Beratung
de.eshg.sti-protection.department-info.hiv_sti_consultation.street=Breite Gasse
de.eshg.sti-protection.department-info.hiv_sti_consultation.houseNumber=28
de.eshg.sti-protection.department-info.hiv_sti_consultation.postalCode=60313
de.eshg.sti-protection.department-info.hiv_sti_consultation.city=Frankfurt am Main
de.eshg.sti-protection.department-info.hiv_sti_consultation.country=DE
de.eshg.sti-protection.department-info.hiv_sti_consultation.phoneNumber=+49 69 212 43270
de.eshg.sti-protection.department-info.hiv_sti_consultation.homepage=https://frankfurt.de/service-und-rathaus/verwaltung/aemter-und-institutionen/gesundheitsamt
de.eshg.sti-protection.department-info.hiv_sti_consultation.email=sexuelle.gesundheit@stadt-frankfurt.de
# de.eshg.sti-protection.department-info.hiv_sti_consultation.latitude=
# de.eshg.sti-protection.department-info.hiv_sti_consultation.longitude=

# can be set individually to overwrite base department infos
de.eshg.sti-protection.department-info.sex_work.use-department-info-from-base-module=false
de.eshg.sti-protection.department-info.sex_work.name=Gesundheitsamt Frankfurt am Main
de.eshg.sti-protection.department-info.sex_work.abbreviation=Sexarbeit
de.eshg.sti-protection.department-info.sex_work.street=Breite Gasse
de.eshg.sti-protection.department-info.sex_work.houseNumber=28
de.eshg.sti-protection.department-info.sex_work.postalCode=60313
de.eshg.sti-protection.department-info.sex_work.city=Frankfurt am Main
de.eshg.sti-protection.department-info.sex_work.country=DE
de.eshg.sti-protection.department-info.sex_work.phoneNumber=+49 69 212 43270
de.eshg.sti-protection.department-info.sex_work.homepage=https://frankfurt.de/service-und-rathaus/verwaltung/aemter-und-institutionen/gesundheitsamt
de.eshg.sti-protection.department-info.sex_work.email=sexuelle.gesundheit@stadt-frankfurt.de
# de.eshg.sti-protection.department-info.sex_work.latitude=
# de.eshg.sti-protection.department-info.sex_work.longitude=


de.eshg.sti-protection.opening-hours.sex_work.de[0]=Di, Mi
de.eshg.sti-protection.opening-hours.sex_work.de[1]=09:00 - 11:00 Uhr\nOffene Sprechstunde nur für Sexarbeiterinnen und Sexarbeiter

de.eshg.sti-protection.opening-hours.sex_work.en[0]=Tu, We
de.eshg.sti-protection.opening-hours.sex_work.en[1]=09:00 - 11:00 am\nOpen consultation hours only for sex workers

de.eshg.sti-protection.opening-hours.hiv_sti_consultation.de[0]=Di, Mi 09:00 - 11:00 Uhr
de.eshg.sti-protection.opening-hours.hiv_sti_consultation.de[1]=Offene Sprechstunde für alle

de.eshg.sti-protection.opening-hours.hiv_sti_consultation.en[0]=Tu, We 09:00 - 11:00 am
de.eshg.sti-protection.opening-hours.hiv_sti_consultation.en[1]=Open consultation hours for everyone
