= E2E Tests
:sectnums:

== Running e2e tests

e2e tests depend on docker containers of the required backend modules. At least the containers necessary for the actions performed in the test must be running.
A full local setup / run of the test suite can be achieved like this:

[source,shell]
----
./gradlew startLocal
# on different console
./gradlew :e2e:test
----

If you have problems during the `composeUp` tasks of the `backend`, you can try this workaround instead:

[source,shell]
----
cd backend
./gradlew buildDockerImage
docker compose up -d --wait
cd ..
./gradlew run
# on different console
./gradlew :e2e:test
----

The `startLocal` task will start the backend modules based on the currently checked out submodule in `backend` and start the frontend based on your current code.
The task will keep running as it starts the `:frontend:run` tasks which starts the next-server application to serve the frontend.

If you like to have the fronted dockerized as well you can instead use the `startLocalDocker` task which will call `composeUp` to build a docker container
also based on your local code.

Refer to the link:./gradle.adoc#e2e-tasks[e2e tasks] for an overview of the common tasks.

== Smoke testing deployed environments

The playwright configuration for smoke testing actual environments is kept a bit separate from the normal configuration.
For each environment a `src/smokeTestConfig/playwright.<env>.config.ts` file exists.

In most environments the dummy user still exists but has a different password. The project is setup to check the `DUMMY_PASSWORD` environment variable
and use its value instead. In a CI pipeline the password could be read from a kubernetes secret:

[source,shell]
----
DUMMY_PASSWORD=$(kubectl -n <namespace> get secrets/keycloak-test-user-secrets -o yaml | yq '.data["test-users-secret-override"]' | base64 -d)
export DUMMY_PASSWORD
----

All playwright tasks (`test`, `testUi` and `runDockerizedPlaywright`) check the project property `-PsmokeTestEnv` and try to match it to a configuration.

[source,shell]
----
./gradlew test -PsmokeTestEnv=playground
----

=== BundId smoke test

The BundId smoke expects a running "AusweisApp" container at post 24727 locally. To start it with the card file system as used by the smoke test run

[source,shell]
----
docker run --pull always --rm -d --name AusweisApp -p 24727:24727 -v ./e2e/resources/base/gdpr/ausweisapp-file-system.json:/fs.json -e AUSWEISAPP_AUTOMATIC_SIMULATOR=/fs.json governikus/ausweisapp2
----

== Updating Snapshots ==

Normal test runs use snapshot retries by default. When a test contains lots of retried snapshots, updating them can be take long, because each snapshot needs to time out before Playwright continues with the next snapshot.

For this reason, it is possible to disable snapshot retries by passing the `-PupdateSnapshots` parameter.

.Updating snapshots using the CLI
[source,shell]
----
./gradlew :e2e:test -Pfilter=myTest.spec.ts -PupdateSnapshots
----

.Updating snapshots using the UI mode
[source,shell]
----
./gradlew :e2e:testUi -PupdateSnapshots
----
