= Flaky Tests
:sectnums:

Due to their nature, flaky tests can be hard to reproduce locally. Sometimes, the reason for a flakiness is not obvious. Then it's essential to reproduce the test failure locally in order to identify the cause and come up with a stable fix.

== Reproducing flaky tests

=== Stressing the CPU

When flakiness comes from a high workload on the machine running the test (e.g. a Gitlab Runner), the `stress` command is a reliable utility to reproduce flakiness. It can be used to put high load on your CPUs before executing the test to be analyzed.

[source, shell]
----
stress --cpu 16
----

`--cpu` denotes the number of CPUs to put under stress. This value is depending on your system. In most cases, the number of CPUs available on your system is a good choice.

`stress` can also be used to stress your local memory and hard drive. However, stressing the CPU is usually sufficient to reproduce flakiness.

Note: `stress` is only available for UNIX systems. Windows users will need another tool.

=== Retry until failure

Flakiness can also be reproduced by retrying a test continuously. While this can be done manually, it's time-consuming and cumbersome. Test retries can be configured for the Gradle `test` task:

[source, shell]
----
./gradlew :e2e:test -Pfilter=path/to/flakyTest.spec.ts -Pretries=10
----

The test path can be copy-pasted from test logs in pipelines or test reports.

The number of retries should be adjusted as needed. Tests with a high failure rate will only need a few retries to be reproduced. Tests with a low failure rate might need much more retries.

Running tests with retries is also suggested to check new tests for flakiness before merging them.

When running tests locally, traces are enabled by default. Since capturing **traces** slows down the test execution, there can be scenarios where tests are only flaky without tracing, which is the default configuration for tests in the CI pipeline.To disable tracing locally, you can add `-PdisableTraces`. Note that you won't have traces to analyze the flakiness, but logs from Docker containers might still help.


== Common causes and fixes for flaky tests

=== The page is still loading

Before running any assertion, the page should usually be in a stable state. Otherwise, assertions might sometimes run too early, leading to flakiness.

It's recommended to use `AbstractPage.waitUntilProgressbarDisappears()` to await any loading animation. There are also scoped variants of `waitUntilProgressbarDisappears`, e.g. on `Sidebar`.

On the initial page load, it can also be useful to wait for the expected URL and page-specific information, like the header.

=== Missing loading indicator

Sometimes flakiness results from missing loading indicators in the UI. This can both be a test and UX problem, because loading states should - in general - be visible to the user.

In this case, adding a loading indicator improves the UX and enables to await a stable state when testing.

=== A button is clicked before it becomes interactive

When using JavaScript events in the browser, it can happen that early interactions on the initial page load get lost when they are triggered before JavaScript can attach the event handlers on the respective element.

A user might retry clicking the button. To mimic this behavior, the interaction can be auto-retried depending on an expected state after the interaction, e.g. opening a modal :

[,ts]
----
await expect(async () => {
  await procedureDetails.reopenProcedureButton.click();
  await procedureDetails.reopenProcedureModal.waitUntilLoaded();
}).toPass();
----
