= Flaky Tests
:sectnums:

Due to their nature, flaky tests can be hard to reproduce locally. Sometimes, the reason for a flakiness is not obvious. Then it's essential to reproduce the test failure locally in order to identify the cause and come up with a stable fix.

== Reproducing flaky tests

=== Stressing the CPU

When flakiness comes from a high workload on the machine running the test (e.g. a Gitlab Runner), the `stress` command is a reliable utility to reproduce flakiness. It can be used to put high load on your CPUs before executing the test to be analyzed.

[source, shell]
----
stress --cpu 16
----

`--cpu` denotes the number of CPUs to put under stress. This value is depending on your system. In most cases, the number of CPUs available on your system is a good choice.

`stress` can also be used to stress your local memory and hard drive. However, stressing the CPU is usually sufficient to reproduce flakiness.

Note: `stress` is only available for UNIX systems. Windows users will need another tool.

=== Retry until failure

Flakiness can also be reproduced by retrying a test continuously. While this can be done manually, it's time-consuming and cumbersome. The `retry` command helps to automate this process. It can be configured to retry a command until it fails:

[source, shell]
----
retry --until=fail [--times=50] -- command-to-retry
----

Configuring `--times` is optional, but is useful to make the command terminate in case it hits no failure.
Consider setting `--delay=0` to disable the back-off time after each attempt.
After `--` follows the command to execute the test to analyze.

.Playwright Example
[source, shell]
----
retry --until=fail -- pnpm playwright test path/to/test.spec.ts:123
----

`retry` is also a useful utility to verify whether a potential fix actually stabilizes a flaky test.

Note: `retry` is only available for UNIX systems. Windows users will need another tool.

== Common causes and fixes for flaky tests

=== The page is still loading

Before running any assertion, the page should usually be in a stable state. Otherwise, assertions might sometimes run too early, leading to flakiness.

It's recommended to use `AbstractPage.waitUntilProgressbarDisappears()` to await any loading animation. There are also scoped variants of `waitUntilProgressbarDisappears`, e.g. on `Sidebar`.

On the initial page load, it can also be useful to wait for the expected URL and page-specific information, like the header.

=== Missing loading indicator

Sometimes flakiness results from missing loading indicators in the UI. This can both be a test and UX problem, because loading states should - in general - be visible to the user.

In this case, adding a loading indicator improves the UX and enables to await a stable state when testing.

=== A button is clicked before it becomes interactive

When using JavaScript events in the browser, it can happen that early interactions on the initial page load get lost when they are triggered before JavaScript can attach the event handlers on the respective element.

A user might retry clicking the button. To mimic this behavior, the interaction can be auto-retried depending on an expected state after the interaction, e.g. opening a modal :

[,ts]
----
await expect(async () => {
  await procedureDetails.reopenProcedureButton.click();
  await procedureDetails.reopenProcedureModal.waitUntilLoaded();
}).toPass();
----
