= Migration Guide
GA-Lotse
:toc:

This document provides notes for **manual actions necessary before or during the deployment**, starting with v1.6.4.
Versions that do not require any manual action are omitted for brevity.

== Version History

=== v2.8.1 / v2.8.2

- v2.8.1 improved security checks concerning GDPR data information request download packages. This requires a database migration for existing download packages, the migration is done automatically by GA Lotse. However, the migration code path is removed with v2.8.2. Therefore, v2.8.1 needs to be deployed and up and running (at least for 20 - 30 minutes) for the migration to happen. If the migration was successful, `No packages without identification_data_hash found` or `Finished identification_data_hash migration` should appear in the log of all business modules. If no download packages exist, skipping the version / migration is fine. Skipping the migration with existing packages (only) results in "dead download links".

=== v1.10.2

- Manual action is required **during the deployment** for all environments. The release introduces the svg-sanitizer module. It's actor must be
enabled in the service directory, otherwise the base module will not be able to start. Further, after the deployment, a rule must be added to the
service directory to allow communication from the base module to the svg-sanitizer module.

=== v1.6.9

- Manual action is required **before the deployment** for all environments that already completed the bootstrapping process.
The process is described in https://gitlab.com/ga-ffm/ga-lotse/ga-lotse-code/blob/main/k8s/docs/README.md#manual-migration-for-instances-with-completed-bootstrapping.

=== v1.6.4

- The Auditlog is now a database module which needs a new permission rule in the service directory:
[source]
----
client XYZ/FM/* -> server XYZ/FM/auditlog
----
