= Migration Guide
GA-Lotse
:toc:

This document provides notes for **manual actions necessary before or during the deployment**, starting with v1.6.4.
Versions that do not require any manual action are omitted for brevity.

== Version History

=== v1.10.2

- Manual action is required **during the deployment** for all environments. The release introduces the svg-sanitizer module. It's actor must be
enabled in the service directory, otherwise the base module will not be able to start. Further, after the deployment, a rule must be added to the
service directory to allow communication from the base module to the svg-sanitizer module.

=== v1.6.9

- Manual action is required **before the deployment** for all environments that already completed the bootstrapping process.
The process is described in https://gitlab.com/ga-ffm/ga-lotse/ga-lotse-code/blob/main/k8s/docs/README.md#manual-migration-for-instances-with-completed-bootstrapping.

=== v1.6.4

- The Auditlog is now a database module which needs a new permission rule in the service directory:
[source]
----
client XYZ/FM/* -> server XYZ/FM/auditlog
----
