= CSS styling with Joy UI and MUI System
:sectnums:

The portal apps use the https://mui.com/joy-ui/getting-started/[Joy UI] component library which is based on the https://mui.com/system/getting-started/[MUI System].
The general use of the library is described in detail in the corresponding documentation.

== Styling approaches

Joy UI components can be quickly customized using the https://mui.com/joy-ui/customization/approaches/#the-sx-prop[`sx` prop].
`Box`, `Stack` and `Grid` are Joy UI's built-in components for creating layouts.
To create a custom reusable component, or to style a native component such as a `<div>`, a styled component can be created using the https://mui.com/joy-ui/customization/approaches/#reusable-component[`styled` function].

== Avoid using the style attribute

Styling a component (e.g. a simple `div`) using the `style` attribute is tempting, but is discouraged for the following reasons:

* Inconsistent styling approach
** The `style` attribute lacks access to the theme values
** The `style` attribute has a higher CSS specificity than styles generated by the `sx` prop
* Performance considerations
** The `sx` prop minimizes CSS injection into the DOM and reduces style recalculation costs
* Security
** In a strict content security policy, which we strive for, no style attributes may be used
