server.port=8104

spring.security.oauth2.client.registration.module-client.client-id=system-file-jockey
spring.security.oauth2.client.registration.module-client.client-secret=password
spring.security.oauth2.client.provider.eshg-keycloak.token-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/token

spring.config.import=classpath:file-jockey-devices.yml

logging.level.org.zalando.logbook=TRACE
