// Copyright 2026 cronn GmbH
// SPDX-License-Identifier: Apache-2.0

import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

plugins {
    id "eshg.java-lib"
    id "com.bmuschko.docker-remote-api"
    id "docker-compose"
    id "eshg.image-push-sign"
    id 'reverse-proxy'
}

java {
    sourceCompatibility = '21'
    targetCompatibility = '21'

    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

def dockerBuildContext = file(layout.buildDirectory.dir('docker'))

jar {
    archiveBaseName.set('eshg-keycloak-plugin')
    archiveClassifier.set('')
}

configurations {
    keycloakProviders
}

dependencies {
    compileOnly libs.bundles.keycloak.server
    compileOnly 'jakarta.validation:jakarta.validation-api'
    compileOnly 'io.quarkus.resteasy.reactive:resteasy-reactive-common:latest.release'
    implementation(project(':keycloak-api')) {
        transitive = false
    }
    keycloakProviders('de.arbeitsagentur.opdt:keycloak-extension-bundid:2.4.4') {
        transitive = false
    }
}

tasks.register('copyResourcesToBuildContext', Copy) {
    from layout.projectDirectory
    include('Dockerfile')
    include('resources/**')
    into dockerBuildContext
}

tasks.register('copyJarsToBuildContext', Copy) {
    def apiJar = project(':keycloak-api').tasks.named('jar', Jar).get()
    def jars = jar.outputs.files
    dependsOn apiJar
    dependsOn jar
    from jars
    from apiJar.outputs.files
    from configurations.keycloakProviders
    rename 'keycloak-extension-bundid-[-.0-9]+\\.jar', 'keycloak-extension-bundid.jar'
    into dockerBuildContext
}

tasks.register('copyFilesToBuildContext') {
    dependsOn 'copyResourcesToBuildContext', 'copyJarsToBuildContext'
}

tasks.register('buildDockerImage', DockerBuildImage) {
    dependsOn 'copyFilesToBuildContext'
    inputDir.set(dockerBuildContext)
    dockerFile.set(inputDir.file("Dockerfile"))
    // WARNING: The version from gradle's catalog is ignored since the sha digest is used without regard to the tag value
    buildArgs["keycloakVersion"] = libs.versions.keycloak.server.get() + "@sha256:fb31a59deb46f746f2aaa25adc5da39ceccac4fd22d36a519562b0bf02e8df20"

    if (project.hasProperty("tagName")) {
        images.add(getImageNameWithTag())
    } else {
        images.add(getImageNameWithLatestTag())
    }
}

tasks.named('composeBuild') {
    dependsOn 'buildDockerImage'
}

reverseProxy {
    serviceName = "keycloak-reverse-proxy"
    mainConfigFile = "keycloak.conf"
}

tasks.named('composeUp').configure {
    dependsOn tasks.named('reverseProxyComposeUp')
}

dockerCompose {
    projectName = rootProject.name
    // maildev ist started here, because it is used by keycloak
    startedServices = ['keycloak', 'maildev']
    useComposeFiles = [
        "${rootDir}/docker-compose.yaml"
    ]
}
