eshg.keycloak.url=http://${DOCKER_HOSTNAME:localhost}:4003
eshg.keycloak.internal.url=http://${DOCKER_HOSTNAME:localhost}:9090
eshg.security.oauth2.resourceserver.employee-jwt.issuer-uri=${eshg.keycloak.url}/realms/eshg
eshg.security.oauth2.resourceserver.employee-jwt.jwk-set-uri=${eshg.keycloak.internal.url}/realms/eshg/protocol/openid-connect/certs
eshg.security.oauth2.resourceserver.citizen-jwt.issuer-uri=${eshg.keycloak.url}/realms/citizens
eshg.security.oauth2.resourceserver.citizen-jwt.jwk-set-uri=${eshg.keycloak.internal.url}/realms/citizens/protocol/openid-connect/certs
