# increase max. http header size from default 8KB to 20KB
server.max-http-request-header-size=20KB

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=10s

# increase max file and request size from default 1MB to 25MB
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
