/*
 * Copyright 2026 cronn GmbH
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package de.eshg.dental.api;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(name = "OrthodonticFinding")
public enum OrthodonticFindingDto {
  ANGLE_CLASS_I,
  ANGLE_CLASS_II,
  ANGLE_CLASS_II_2,
  ANGLE_CLASS_III,
  ANGLE_CLASS,
  APLASIA,
  BUCAL_LINGUAL_OCCLUSION,
  DIASTEMA,
  ANTERIOR_CROWDING,
  ANTERIOR_CROSSBITE,
  APPLIANCE_THERAPY,
  HABITS,
  EDGE_TO_EDGE_BITE,
  BILATERAL_LATERAL_CROSSBITE,
  UNILATERAL_LATERAL_CROSSBITE,
  CLEFT_LIP_AND_PALATE,
  MIDLINE_DEVIATION,
  FIXED_APPLIANCE,
  NON_OCCLUSION,
  OPEN_BITE,
  ANTERIOR_OPEN_BITE,
  LATERAL_OPEN_BITE,
  CROWDING,
  PROGENIC_FORCED_BITE,
  PROGNATHISM,
  PSEUDOPROGNATHISM,
  NARROW_JAW,
  OTHER,
  SUPPORT_ZONE_COLLAPSE,
  DEEP_BITE,
  DEEP_BITE_WITH_GINGIVAL_CONTACT,
  INCREASED_SAGITTAL_OVERJET,
  DISPLACEMENT
}
