/*
 * Copyright 2026 cronn GmbH
 * SPDX-License-Identifier: Apache-2.0
 */

package de.eshg.lib.gdt.v35.builder;

/**
 * Builder for the Examination Request (Obj_0012 / Obj_Anforderung).
 *
 * <p>This object is the core of a "Request New Examination" (6302) record. It specifies which
 * examination the medical device should perform.
 */
public class Gdt35ExaminationRequestBuilder extends BaseBuilder<Gdt35ExaminationRequestBuilder> {

  @Override
  protected Gdt35ExaminationRequestBuilder self() {
    return this;
  }

  /**
   * Sets the Request Identifier (8310).
   *
   * <p>A unique ID generated by the AIS/PVS for this specific examination request. The device
   * should reference this ID when returning results.
   *
   * @param value The request ID (e.g., "REQ-2023-001").
   * @return This builder instance.
   */
  public Gdt35ExaminationRequestBuilder requestId(String value) {
    return addField("8310", value);
  }

  /**
   * Sets the Request-UID (8314).
   *
   * <p>A secured and unique request ID (UID) generated by the AIS/PVS. This field is mandatory in
   * GDT 3.5 when requesting a new examination.
   *
   * @param value The request UID.
   * @return This builder instance.
   */
  public Gdt35ExaminationRequestBuilder requestUid(String value) {
    return addField("8314", value);
  }

  /**
   * Sets the Device/Process Specific Characteristic Map (8402).
   *
   * <p>The field is used to group the data to be transmitted. The values are typically agreed upon
   * between AIS and Device (e.g., "EKG01", "LUFU"). This is the primary control field for the
   * device.
   *
   * @param value The test identifier code.
   * @return This builder instance.
   */
  public Gdt35ExaminationRequestBuilder measuringDevice(String value) {
    return addField("8402", value);
  }

  /**
   * Sets the Test-ID (8410).
   *
   * <p>A manufacturer-specific ID for the test. Often used in conjunction with or as an alternative
   * to 8402, depending on the device's requirements.
   *
   * @param value The manufacturer-specific test ID.
   * @return This builder instance.
   */
  public Gdt35ExaminationRequestBuilder testId(String value) {
    return addField("8410", value);
  }

  /**
   * Sets the Study-UID (8408).
   *
   * <p>A globally unique identifier (UID) for the study, often used in DICOM contexts. Allows
   * linking multiple results or images to a single study context.
   *
   * @param value The Study Instance UID.
   * @return This builder instance.
   */
  public Gdt35ExaminationRequestBuilder studyId(String value) {
    return addField("8408", value);
  }
}
