/*
 * Copyright 2026 cronn GmbH
 * SPDX-License-Identifier: Apache-2.0
 */

package de.eshg.lib.gdt.v35.builder;

import java.util.function.Consumer;

/**
 * Builder for the Examination Result (Obj_0057 / Obj_Untersuchungsergebnis_GDT).
 *
 * <p>Used in "Transmit Examination Data" (6310) records. Contains the actual data generated by the
 * medical device (values, units, timestamps).
 */
public class Gdt35ExaminationResultBuilder extends BaseBuilder<Gdt35ExaminationResultBuilder> {

  @Override
  protected Gdt35ExaminationResultBuilder self() {
    return this;
  }

  /**
   * Sets the Test-ID (8410).
   *
   * <p>Identifies the specific test that produced this result. Should correspond to the ID
   * requested in 8410/8402.
   *
   * @param value The test ID (e.g., "EKG-Lead-I").
   * @return This builder instance.
   */
  public Gdt35ExaminationResultBuilder testId(String value) {
    return addField("8410", value);
  }

  /**
   * Sets the Test Name (8411).
   *
   * <p>A human-readable description of the test or parameter (e.g., "Heart Rate", "FVC"). Useful
   * for display in the AIS.
   *
   * @param value The name of the test.
   * @return This builder instance.
   */
  public Gdt35ExaminationResultBuilder testName(String value) {
    return addField("8411", value);
  }

  /**
   * Sets the Result Value (8420).
   *
   * <p>The numeric or textual value of the measurement (e.g., "75", "Normal"). Formatted according
   * to GDT rules (ISO 8859-15).
   *
   * @param value The result value.
   * @return This builder instance.
   */
  public Gdt35ExaminationResultBuilder value(String value) {
    return addField("8420", value);
  }

  /**
   * Sets the Unit (8421).
   *
   * <p>The physical unit of the measurement (e.g., "bpm", "kg", "mm").
   *
   * @param value The unit string.
   * @return This builder instance.
   */
  public Gdt35ExaminationResultBuilder unit(String value) {
    return addField("8421", value);
  }

  /**
   * Adds the Measurement Timestamp (8225 / Obj_0054).
   *
   * <p>The exact date and time when the measurement was performed.
   *
   * @param config A consumer to configure the {@link Gdt35TimestampBuilder}.
   * @return This builder instance.
   */
  public Gdt35ExaminationResultBuilder measurementDate(Consumer<Gdt35TimestampBuilder> config) {
    return addObject("8225", "Timestamp_Messung", "Obj_0054", new Gdt35TimestampBuilder(), config);
  }
}
