plugins {
    id "eshg.java-lib"
}

dependencies {
    implementation 'org.springframework.boot:spring-boot'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.security:spring-security-oauth2-jose'
    implementation 'org.springframework.security:spring-security-oauth2-resource-server'
    implementation 'org.apache.httpcomponents.client5:httpclient5'
    implementation "org.zalando:logbook-httpclient5:latest.release"
    implementation project(":api-commons")
    implementation project(":logging-commons")

    runtimeOnly "org.zalando:logbook-spring-boot-starter:latest.release"

    testImplementation('com.squareup.okhttp3:mockwebserver') {
        exclude group: "junit", module: "junit"
    }
    // mockwebserver depends on Junit 4 interfaces that we don't want.
    // Replace those interfaces with dummy ones.
    // Remove when upgrading to mockwebserver 5
    testImplementation 'io.quarkus:quarkus-junit4-mock:latest.release'
    testImplementation 'org.springframework.boot:spring-boot-starter-web'
}
