# https://docs.spring.io/spring-security/reference/servlet/oauth2/client/client-authentication.html
# https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-boot-property-mappings
spring.security.oauth2.client.registration.module-client.provider=eshg-keycloak
spring.security.oauth2.client.registration.module-client.authorization-grant-type=client_credentials

# business modules need to provide client id (one of de.eshg.base.keycloak.ModuleClient clientId) and their client secret
#spring.security.oauth2.client.registration.module-client.client-id=
#spring.security.oauth2.client.registration.module-client.client-secret=

# business modules need to provide the token endpoint of keycloak
#spring.security.oauth2.client.provider.eshg-keycloak.token-uri=
