/*
 * Copyright 2026 cronn GmbH
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package de.eshg.medicalregistry.api;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(name = "ProfessionalTitle")
public enum ProfessionalTitleDto {
  DOCTOR,
  DENTIST,
  PSYCHOLOGICAL_PSYCHOTHERAPIST,
  NURSING_ASSISTANT,
  GERIATRIC_NURSE,
  DIETICIAN,
  DISINFECTOR,
  OCCUPATIONAL_THERAPIST,
  HEALTH_SUPERVISOR,
  HEALTHCARE_AND_PEDIATRIC_NURSE,
  HEALTHCARE_AND_NURSING_ASSISTANT,
  HEALTHCARE_AND_NURSING_ASSISTANTS_HELPER,
  MIDWIVE_MATERNITY_NURSE,
  ALTERNATIVE_PRACTITIONER,
  NON_MEDICAL_PRACTITIONER_FOR_CHIROPRACTIC,
  ALTERNATIVE_PRACTITIONER_FOR_SPEECH_THERAPY,
  NON_MEDICAL_PRACTITIONER_FOR_PHYSIOTHERAPY,
  NON_MEDICAL_PRACTITIONER_FOR_PSYCHOTHERAPY,
  CHILD_AND_YOUTH_PSYCHOTHERAPIST,
  SPEECH_THERAPIST,
  MASSEUR_AND_MEDICAL_BATH_ATTENDANT,
  MEDICAL_DOCUMENTALIST,
  MEDICAL_TECHNICAL_LABORATORY_ASSISTANT,
  MEDICAL_TECHNICAL_RADIOLOGY_ASSISTANT,
  MEDICAL_TECHNICAL_ASSISTANT_FOR_FUNCTIONAL_DIAGNOSTICS,
  EMERGENCY_PARAMEDIC,
  ORTHOPTIST,
  CARE_ASSISTANT,
  NURSING_SERVICE,
  NURSING_SERVICE_MANAGER,
  PHARMACEUTICAL_TECHNICAL_ASSISTANT,
  PHYSIOTHERAPIST,
  PODIATRIST,
  RADIOLOGY_ASSISTANT,
  SPORTS_THERAPIST,
  PHARMACIST,
  VETERINARIAN,
}
